### ISSUE TITLE
Cannot use 'False' as class name as it is reserved

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-seomatic#1277] opened 2023-02-01 13:22 UTC
I have the exact same issue as #501, using using Craft 3.7.63.1, Seomatic 3.4.48, and Webhooks 2.4.1 so it doesn't seem to be fixed.

To summarise, when I go to create a new Webhook, I get the standard "An unknown error occurred" message and see the following in the logs:

```Cannot use 'False' as class name as it is reserved in /var/www/html/vendor/nystudio107/craft-seomatic/src/models/jsonld/False.php:24```

Was the change merged?

**Comment by khalwat** [comment] 2023-02-01 22:37
It definitely was fixed, but it looks like there was a regression.

**Comment by khalwat** [comment] 2023-02-01 22:40
@howells can you provide more context for the error? What source file and line of code throws that error?

**Comment by khalwat** [comment] 2023-02-01 23:37
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d1f76ebc0d61579953319c149fe526dd924e86c0 & https://github.com/nystudio107/craft-seomatic/commit/8e35a36ff9d5c04c412b373df4d6b14c812f324c

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.49",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.20”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2023-02-01 23:37 UTC
Labels: bug
