### ISSUE TITLE
'Unsupported operand types: string * int' Error when generating sitemap

### ISSUE THREAD

**Issue by joostwaaijer** [nystudio107/craft-seomatic#1498] opened 2024-08-06 08:24 UTC
### Describe the bug
When running the Sitemap generation command, I'm running into a 
>'TypeError' with message 'Unsupported operand types: string * int'
error, and the sitemap can't complete generating.

### To reproduce
Steps to reproduce the behaviour:
1. Run the sitemap generate commando.
2. After running for a while, the commando fails with the error.

### Expected behaviour
Expected to complete the commando without errors.

### Screenshots
<img width="2208" alt="image" src="https://github.com/user-attachments/assets/c2a12962-30f3-40b3-9072-85efec9cbd29">

### Versions
- Plugin version: 4.1.1
- Craft version: 4.10.7
- Craft commerce version: 4.6.7

**Comment by khalwat** [comment] 2024-08-08 01:59
What version of PHP are you running?

I should note that with the version of SEOmatic that you're running, it's not necessary to generate the sitemap via CLI command anymore.

But that's parenthetical, I'd like to get to the bottom of this error, it looks like an incoming parameter isn't being set as expected.

**Comment by khalwat** [comment] 2024-08-08 04:14
Okay, I can reproduce it if I go in and set the Sitemap Page Size to "Single Page" -- is this what you have it set to?

**Comment by khalwat** [comment] 2024-08-08 18:22
Fixed in the above commits

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.2”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.2”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.2”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2024-08-08 18:22 UTC
Labels: bug

**Comment by joostwaaijer** [comment] 2024-08-09 06:03
Thanks for the fix! I'll try it out!
