### ISSUE TITLE
Internal server error after installing plugin

### ISSUE THREAD

**Issue by markcoogan** [nystudio107/craft-seomatic#934] opened 2021-07-27 12:17 UTC
### Question
I installed the plugin and I'm now getting an internal server error on the front and backend of the site. 

### Additional context
Add any other context or screenshots about the support request here.

2021-07-27 08:16:13 [-][1][1ac3772b9fa0fc4a8f4f240ab8b89662][error][Error] Error: Undefined class constant 'EVENT_REGISTER_GQL_SCHEMA_COMPONENTS' in /home/a578595/specialistnutrition.us/craft/vendor/nystudio107/craft-seomatic/src/Seomatic.php:685
Stack trace:
#0 /home/a578595/specialistnutrition.us/craft/vendor/nystudio107/craft-seomatic/src/Seomatic.php(488): nystudio107\seomatic\Seomatic->installGlobalEventListeners()
#1 /home/a578595/specialistnutrition.us/craft/vendor/nystudio107/craft-seomatic/src/Seomatic.php(316): nystudio107\seomatic\Seomatic->installEventListeners()
#2 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): nystudio107\seomatic\Seomatic->init()
#3 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('seomatic', Object(craft\web\Application), Array)
#5 /home/a578595/specialistnutrition.us/craft/vendor/nystudio107/craft-seomatic/src/Seomatic.php(246): craft\base\Plugin->__construct('seomatic', Object(craft\web\Application), Array)
#6 [internal function]: nystudio107\seomatic\Seomatic->__construct('seomatic', Object(craft\web\Application), Array)
#7 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#8 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('nystudio107\\seo...', Array, Array)
#9 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('nystudio107\\seo...', Array, Array)
#10 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/src/services/Plugins.php(905): yii\BaseYii::createObject(Array, Array)
#11 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('seomatic', Array)
#12 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1402): craft\services\Plugins->loadPlugins()
#13 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/src/web/Application.php(103): craft\web\Application->_postInit()
#14 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#15 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#16 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/src/web/Application.php(91): yii\base\Application->__construct(Array)
#17 [internal function]: craft\web\Application->__construct(Array)
#18 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#19 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#20 /home/a578595/specialistnutrition.us/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#21 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#22 /home/a578595/specialistnutrition.us/craft/vendor/craftcms/cms/bootstrap/web.php(51): require('/home/a578595/s...')
#23 /home/a578595/specialistnutrition.us/public_html/index.php(21): require('/home/a578595/s...')
#24 {main}
2021-07-27 08:16:12 [-][1][1ac3772b9fa0fc4a8f4f240ab8b89662][info][application] $_GET = []

**Comment by khalwat** [comment] 2021-07-27 13:22
Duplicate of: https://github.com/nystudio107/craft-seomatic/issues/933

**Closed as completed by khalwat** 2021-07-27 13:22 UTC
Labels: question

**Comment by khalwat** [comment] 2021-07-27 14:33
I will release the version today that fixes this issue

**Comment by khalwat** [comment] 2021-07-27 15:08
Released as 3.3.46 -> https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.46
