### ISSUE TITLE
Content SEO output twice in CP

### ISSUE THREAD

**Issue by thaoms** [nystudio107/craft-seomatic#98] opened 2018-05-02 18:25 UTC
The sitemap shows twice

<img width="1192" alt="screenshot 2018-05-02 20 22 24" src="https://user-images.githubusercontent.com/2323270/39541656-b0a44424-4e46-11e8-8b34-4c4db1590839.png">

Craft 3.0.5
SEOmatic 3.0.9

**Comment by khalwat** [comment] 2018-05-02 20:08
I'll be fixing this with a migration shortly. Basically there was a regression that caused `seomatic_metabundles` to be created with the incorrect `sourceBundleType` of `field`.

Then this bug was fixed, but since it then was looking for the _correct_ `sourceBundleType` it couldn't find it for that section, and created a new one.

If you're anxious, you can just delete any rows in the `seomatic_metabundles` table that have a `sourceBundleType` of `field`. But I should have a fix out tomorrow.

**Comment by khalwat** [comment] 2018-05-02 20:50
Fixed in https://github.com/nystudio107/craft-seomatic/commit/caef653db56947f4a03b14d919ae4fa815d05b6f

**Closed as completed by khalwat** 2018-05-02 20:50 UTC
Labels: bug, To Do
