### ISSUE TITLE
4.0.11 error

### ISSUE THREAD

**Issue by proximo7** [nystudio107/craft-seomatic#1233] opened 2022-11-02 19:35 UTC
After updating to 4.0.11 I'm getting errors on the front end and on Craft entries. Tried rolling back to 4.0.10 but the front end error remained.

```
An Error occurred while handling another error:
craft\web\twig\TemplateLoaderException: Unable to find the template “twigfield/twigfield” in "seomatic/settings/_includes/fields/_seoTitle.twig" at line 19. in /home/craft/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:108
Stack trace:
#0 /home/craft/vendor/craftcms/cms/src/web/twig/TemplateLoader.php(69): craft\web\twig\TemplateLoader->_resolveTemplate('twigfield/twigf...')
```

Front end:
```
TypeError
array_merge(): Argument #2 must be of type array, string given
  public function pruneFieldMetaBundleSettings(MetaBundle $metaBundle, string $fieldHandle)
    {
        /** @var SeoSettings $seoSettingsField */
        $seoSettingsField = Craft::$app->getFields()->getFieldByHandle($fieldHandle);
        if ($seoSettingsField) {
            $seoSettingsEnabledFields = array_flip(array_merge(
                $seoSettingsField->generalEnabledFields,
                $seoSettingsField->twitterEnabledFields,
                $seoSettingsField->facebookEnabledFields,
                **$seoSettingsField->sitemapEnabledFields**
            ));
            // Always include some fields, as they are calculated even if not explicitly included
            $seoSettingsEnabledFields = array_merge(
                $seoSettingsEnabledFields,
                array_flip(self::ALWAYS_INCLUDED_SEO_SETTINGS_FIELDS)
            );
            // metaGlobalVars
            $attributes = $metaBundle->metaGlobalVars->getAttributes();
```

**Comment by khalwat** [comment] 2022-11-02 23:44
Your first error looks to me like that update to 4.0.11 wasn't fully done, or you didn't clear caches on deploy, because that include is not present in that file:

https://github.com/nystudio107/craft-seomatic/blob/v4/src/templates/settings/_includes/fields/_seoTitle.twig

**Comment by khalwat** [comment] 2022-11-02 23:44
Your other issue looks like a duplicate of this issue: https://github.com/nystudio107/craft-seomatic/issues/1231

So let's discuss that one there.

**Closed as completed by khalwat** 2022-11-02 23:44 UTC
Labels: bug

**Comment by khalwat** [comment] 2022-11-03 00:28
Can you show me your field settings for the SEO Settings field in question? In particular, is it possible that you have it configured like this:

<img width="430" alt="Screenshot 2022-11-02 at 8 25 33 PM" src="https://user-images.githubusercontent.com/7570798/199626701-1e5d70db-bc56-4cba-b648-0045c87c4c33.png">

...where you have the tab enabled, but don't have any fields selected in it?

**Comment by khalwat** [comment] 2022-11-03 00:37
So I think this might be a regression in Craft CMS; what's happening is if none of the checkbox fields are checked, the value that is being saved _should_ be an empty array `[]` but instead, it's saving it as an empty string `''` for some reason.

I'll add a check to guard against this. I suspect it's a regression in Craft 4.3

**Comment by khalwat** [comment] 2022-11-03 00:44
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/aa379022d1c5d43b5635a998baaa03db5f042e8e

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.12”,
```
Then do a `composer clear-cache && composer update`

**Comment by proximo7** [comment] 2022-11-03 02:27
Ran the update as described. Craft entries now work but the front end has a new error. Checked the SEOMatic field and the Sitemap Tab was not enabled.

```
TypeError
in_array(): Argument #2 ($haystack) must be of type array, string given
1. in /home/craft/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.phpat line 579
570571572573574575576577578579580581582583584585586587588                    );
                    foreach ($fieldHandles as $fieldHandle) {
                        if (!empty($element->$fieldHandle)) {
                            /** @var MetaBundle $metaBundle */
                            $fieldMetaBundle = $element->$fieldHandle;
                            /** @var SeoSettings $seoSettingsField */
                            $seoSettingsField = Craft::$app->getFields()->getFieldByHandle($fieldHandle);
                            if ($fieldMetaBundle !== null && $seoSettingsField !== null && $seoSettingsField->sitemapTabEnabled) {
                                // If sitemaps are off for this entry, don't include the URL
                                if (in_array('sitemapUrls', $seoSettingsField->sitemapEnabledFields, false)
                                    && !$fieldMetaBundle->metaSitemapVars->sitemapUrls
                                    && !Seomatic::$plugin->helper->isInherited($fieldMetaBundle->metaSitemapVars, 'sitemapUrls')
                                ) {
                                    $includeUrl = false;
                                }
                                // If robots is set to 'none' don't include the URL
                                if ($fieldMetaBundle->metaGlobalVars->robots === 'none' || $fieldMetaBundle->metaGlobalVars->robots === 'noindex') {
                                    $includeUrl = false;
                                }
2. in /home/craft/vendor/nystudio107/craft-seomatic/src/helpers/DynamicMeta.php at line 579– in_array('sitemapUrls', '', false)
...
```

**Comment by khalwat** [comment] 2022-11-03 03:36
@proximo7 I pushed a fix for that as well; it's the same issue, in a different place.

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/e6ddee7035fd25f5c84e5f06090b0f606c257adc

Do this again, and it will update it again:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.12”,
```
Then do a `composer clear-cache && composer update`

**Comment by proximo7** [comment] 2022-11-03 19:28
Many thanks! Working now.
