### ISSUE TITLE
Don't return 503 for ungenerated sitemaps

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-seomatic#582] opened 2020-03-17 16:18 UTC
Currently, when you don't have a sitemap generated, you get back well formed XML of an empty sitemap, but with a 503 response.

Whether or not 503 is the "right" response here is a semantic debate I don't really care to dive into… https://stackoverflow.com/questions/9794696/how-do-i-choose-a-http-status-code-in-rest-api-for-not-ready-yet-try-again-lat

However, in my case, and perhaps others, a 5xx error generally indicate something more severe, and may trigger unwanted behavior. For instance, what was happening for me is repeated 503s return by submitting a sitemap with ungenerated sitemaps triggered my load balancer to think the backend was sick.

I'm thinking maybe a `202 Accepted` (as suggested in the SO) would be more agreeable? https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.3

**Comment by khalwat** [comment] 2020-03-18 13:05
Well, so, the problem is that other things such as caches are well set up to NOT cache >= 300 codes, but they WILL cache 2xx codes. And that would be a pretty bad result

 I don't know what things like Blitz, CloudFlare, FastCGI Cache, Varnish (the latter of the two will depend on custom setups) will do with a 202... but I do know they won't cache things if the returned code is >= 300

I'd also tend to agree with:

> I would argue that "accepted for processing" indicates that you're saving the request to be acted on later. If it's just being ignored, you should return a 4xx or 5xx code to indicate to the client that they might want to try again. – Luke Oct 20 '16 at 15:17

The 503 and `Retry-After` header is set specifically for bots, so that they can retry after a set period of time.

I'd suggest that you just ignore 503 result codes from `.xml` files?

**Comment by khalwat** [comment] 2020-03-24 21:21
Closing until further info is submitted.

**Closed as completed by khalwat** 2020-03-24 21:21 UTC
Labels: need info

**Comment by paddling** [comment] 2021-01-11 16:35
@khalwat the site that @timkelty was referring to was ours. The issue still exists that the 503 error occurs when crawling the sub-sitemaps.  And Lord Google doesn't approve.

![image](https://user-images.githubusercontent.com/58182286/104209713-0d9c1c80-5400-11eb-8c00-0058dd44c9c3.png)

FWIW: I ran the primary sitemap through Screaming Frog and it consistently creates the same issue:   
![image](https://user-images.githubusercontent.com/58182286/104209890-3cb28e00-5400-11eb-81a7-4ca920e03ead.png)

Here is the error we receive:
![image](https://user-images.githubusercontent.com/58182286/104210095-797e8500-5400-11eb-9cb0-0b48970f9994.png)

If you simply reload the page in the browser it reloads as a valid page (most of the time).

Can you reopen and address the issue?

**Comment by khalwat** [comment] 2021-01-11 17:16
I can re-open if you can present some new information; in my testing it's working as expected.

Are we sure there isn't some complication involved here with the Varnish setup?

**Comment by khalwat** [comment] 2021-01-11 17:18
I was able to load a number of the sitemaps on your site without issue:

https://paddling.com/sitemaps-1-sitemap.xml

https://paddling.com/sitemaps-1-section-outfitters-1-sitemap.xml

They `curl` just fine too:

```
❯ curl -I https://paddling.com/sitemaps-1-sitemap.xml
HTTP/2 200
server: openresty/1.15.8.1
date: Mon, 11 Jan 2021 17:18:10 GMT
content-type: text/xml; charset=utf-8
content-length: 3243
x-robots-tag: noindex
content-security-policy: default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src	'self' 'unsafe-inline' *; img-src 'self' data: *;font-src 'self' data: *
x-frame-options: ALLOWALL
x-content-type-options: nosniff
referrer-policy: no-referrer
feature-policy: *
age: 66
x-cache-hits: 1
accept-ranges: bytes
strict-transport-security: max-age=15724800; includeSubDomains
```

**Comment by paddling** [comment] 2021-01-11 17:55
We are moving away from varnish soon so I can reassess after that change is deployed. I will post follow up comments if further work is needed.

**Comment by paddling** [comment] 2021-01-12 14:14
@khalwat can you explain the logic as to why, when a crawler first visits the sitemap that it re-indexes the sitemaps entirely? We run a cron job on a daily basis to update the sitemaps so they are fresh (or at least fresh enough). 

Better yet, is there a way to disable that action so that the pages load on the first try and don't initiate a reindex?

**Comment by khalwat** [comment] 2021-01-13 01:50
@paddling that should not be happening. The sitemaps only regenerate when the caches expire or are cleared, or entries are modified (which then clears the cache for just that sitemap).

**Comment by paddling** [comment] 2021-01-13 20:22
It appears that the sitemaps are not being cached by our server currently so they are invalid every 120 seconds.
We are moving away from Varnish so hoping that solves it...
You can close this issue for now. I will reopen if we are still on the struggle 🚌 after we move to a new environment.
