### ISSUE TITLE
Global SEO image overrides all Content SEO images

### ISSUE THREAD

**Issue by brandondeweese** [nystudio107/craft-seomatic#790] opened 2020-12-05 16:40 UTC
If I set a Global SEO image, it overrides all Content SEO images. Much like the SEO title and the SEO Description, I expected SEOmatic to honor each Content SEO image unless one isn't set. All SEOmatic previews show the correct image, but if I look in the head, the Global SEO image is the image that's being pulled. It does this regardless of whether the Content SEO image is a link or pulled from a field. 

### Versions
- Plugin version: 3.3.25
- Craft version: Craft Solo 3.5.16

**Comment by khalwat** [comment] 2020-12-06 04:27
SEOmatic does indeed honor images set in Content SEO, which will override images set via Global SEO.

In order for me to help you, I'm going to need to see some screenshots of how things are set up, whether you have any SEO Settings fields in use, etc.

**Comment by brandondeweese** [comment] 2020-12-06 05:56
Actually, I noticed none of my custom SEO Image URLS aren't working. 


I was trying to set set an a SEO image field to be the #1, then fall back to hero image field for #2, and Global Image Field to be the #3. My original code was this:

{seomatic.helper.socialTransform(object.entry.seoImage | length ? object.entry.seoImage[0] : object.entry.hero[0], "base", 1, "crop")}

But I've even simply tried accessing the field's image url the following ways:

- {entry.hero[0].url()}
- {seomatic.helper.socialTransform(object.entry.hero[0], "base", 1, "crop")} -- this is what it defaults to when I switch to "Custom URL"
- {seomatic.helper.extractTextFromField(entry.hero[0].url())}

Nothing works, except selecting from a field. Even a direct link to a file doesn't work.

I'm using it for the title and it works great.
{seomatic.helper.extractTextFromField(object.entry.seoTitle | length ? object.entry.seoTitle : object.entry.title)}

I'm really sorry if I'm missing something here, I've just been racking my brain about this and can't figure it out. Thanks for your help.

![Screen Shot 2020-12-05 at 9 41 20 PM](https://user-images.githubusercontent.com/18017918/101272830-c194f280-3744-11eb-87ec-891180856061.png)

**Comment by khalwat** [comment] 2020-12-06 06:53
I can look at the code a bit more in depth if this doesn’t help, but what I do is if I’m putting a complex Twig expression in one of the SEOmatic fields, I first get it working in a Twig template for that Section.

Make sure you have it working as intended on the frontend in a regular Twig template.

Then I copy & paste the Twig code, add object. In front of the entry. (Or whatever) and you should be good to go

/andrew

**Comment by brandondeweese** [comment] 2020-12-07 23:10
Thank you. I will do that from now on. I was able to get my expression to work just fine in the Twig template, however, I'm unable to get any SEO Image custom URL to work, event linking directly to a file. Using a field or a custom image works just fine though.

![Screen Shot 2020-12-07 at 2 50 27 PM](https://user-images.githubusercontent.com/18017918/101416145-0da77a80-389e-11eb-934a-904d35c72b39.png)

**Comment by khalwat** [comment] 2020-12-18 13:38
@brandondeweese I can't tell if this has been resolved or not?

**Comment by brandondeweese** [comment] 2020-12-22 02:27
No. It has not been resolved. I've tried to this across multiple sites, and I'm unable to get any SEO Image Custom URLs to work. So I gave up. And just selected a field.

**Comment by khalwat** [comment] 2020-12-22 17:32
Okay, if you can clarify what you mean here:

> Thank you. I will do that from now on. I was able to get my expression to work just fine in the Twig template, however, I'm unable to get any SEO Image custom URL to work, event linking directly to a file. Using a field or a custom image works just fine though.

Maybe show me the code you're trying to use that isn't working? The more information the better!

Is this the code that's not working?
```twig
{seomatic.helper.socialTransform(object.entry.seoImage | length ? object.entry.seoImage[0] : object.entry.hero[0], "base", 1, "crop")}
```

It looks like you're trying to do a social transform on either the `entry.seoImage` or `entry.hero`... have you tried the double mustache notation?

```twig
{{ seomatic.helper.socialTransform(object.entry.seoImage | length ? object.entry.seoImage[0] : object.entry.hero[0], "base", 1, "crop") }}
```

...because you want to use `object.` only when you're using `{{`

**Comment by brandondeweese** [comment] 2020-12-22 18:12
Thanks for getting back to me. So, as I said **NO URL** works. None. Not even a URL directly to an image file. 

THis works fine...
![from-field-works](https://user-images.githubusercontent.com/18017918/102919520-dc9e7c80-443d-11eb-96f9-01613916eb05.png)

Couldn't get this to work....?
![simple-code](https://user-images.githubusercontent.com/18017918/102919513-da3c2280-443d-11eb-8f6c-6918a368e5bc.png) Also tried this one as:
`{seomatic.helper.socialTransform(entry.metaImage[0], "base", 1, "crop")}`

I tried to link directly to the file...and to no avail. 
![direct-to-file](https://user-images.githubusercontent.com/18017918/102919505-d6a89b80-443d-11eb-9b77-5634026a7117.png)

Let me know if this helps.

**Comment by khalwat** [comment] 2020-12-22 20:01
Okay so the good news is, you're not crazy. The bad news is, I think I might know what this is.

Can you check to see if your Global SEO settings have the SEO Image set to something? I think due to an internal bug/logic error, if you have not set your Global SEO Image to something, you'll see the results that you're seeing.

**Comment by brandondeweese** [comment] 2020-12-22 20:10
HAHA ok. So I set the Global SEO image and it overrides the custom URL, and I think this brings me back to why I posted this originally until I noticed the other stuff.

**Comment by khalwat** [comment] 2020-12-22 20:23
Right, but make sure that your global SEO image is set to something. Then you can try just a raw URL in the content SEO and that should work￼

The reason it was not working before is very likely because it evaluated to nothing, not that the global settings were overriding it

**Comment by brandondeweese** [comment] 2020-12-22 20:29
That's what I'm saying...the global SEO image **IS** set and it's overriding the raw URL.

![Screen Shot 2020-12-22 at 12 28 10 PM](https://user-images.githubusercontent.com/18017918/102930472-53914080-4451-11eb-95bd-1733c366fb8d.png)

**Comment by khalwat** [comment] 2020-12-22 22:14
Sorry for not understanding your initial issue @brandondeweese :(

Glad you have it resolved, though!

If you can get the raw URL working, you can get any arbitrary Twig code working too. Make sure it works in your template first, use the double `{{ }}` notation, and put `object.` in front of your `entry` or whatever, and you should be good to go.

Let me know!

**Comment by brandondeweese** [comment] 2020-12-22 22:17
Uhhh.... it's not working. That's what I'm showing you there...

**Comment by brandondeweese** [comment] 2020-12-22 22:19
If I have a Global SEO image set, the Global SEO image overrides all fields that use CUSTOM URLS. And without a Global Image set,  CUSTOM URLs don't work either.

**Comment by khalwat** [comment] 2020-12-22 22:19
...and what do you have your Twitter Image and Facebook Image sources set to?

Can you ensure that both are set to "Same as SEO Image" and re-save the settings?

**Comment by brandondeweese** [comment] 2020-12-22 22:20
Ensured and confirmed.

**Comment by brandondeweese** [comment] 2020-12-22 22:21
No CUSTOM URL works with or without a Global SEO image set.

**Comment by khalwat** [comment] 2020-12-22 22:25
Here is my global SEO Image setting:

<img width="281" alt="Screen Shot 2020-12-22 at 5 21 34 PM" src="https://user-images.githubusercontent.com/7570798/102938427-4e94b700-447a-11eb-93ca-153c993306b5.png">

Here is my Content SEO Image for the homepage single:

<img width="281" alt="Screen Shot 2020-12-22 at 5 21 52 PM" src="https://user-images.githubusercontent.com/7570798/102938447-59e7e280-447a-11eb-9269-7cbbbce93f13.png">

The Twitter Image and Facebook Image are both set to "Same as SEO Image". Here's what's in the source code when I view source:

```
<meta content="http://craft3.test/assets/content.jpg" property="og:image">
```

Ensure that:
- `devMode` is on so that your local caches last only 30 seconds
- You re-save the Twitter & Facebook Global SEO settings
- You re-save the Twitter & Facebook Content SEO settings for the section

If you're unable to replicate this, I think we should do a screenshare to sort out what is going wrong.

**Comment by brandondeweese** [comment] 2020-12-22 22:27
ok, give me a sec.

**Comment by brandondeweese** [comment] 2020-12-22 22:42
OK so... I just got it to work...however...it ONLY works if I have a CUSTOM URL set for the GLOBAL SEO Image. So if I set it the GLOBAL SEO IMAGE to a Custom Image (selecting directly from assets) Content SEO IMAGES Custom URLs don't work. So....

**THIS WORKS FINE:**

> GLOBAL SEO IMAGE SETTING:
> ![Global-works](https://user-images.githubusercontent.com/18017918/102939519-49783d80-4463-11eb-8e15-5f07b8f32038.png)
> 
> CONTENT SEO IMAGE SETTING:
> ![Content-works](https://user-images.githubusercontent.com/18017918/102939600-63b21b80-4463-11eb-9000-cb497db5d079.png)
> 
>  META IMAGE:
> ` <meta content="http://scout.build/img/hero/content.jpg" property="og:image">` 


++++++++++++++++++++++++++++++++++++++++++++++++++


**THIS _DOES NOT_ WORK:**

> 
> GLOBAL SEO IMAGE SETTING:
> ![Global-Not-working](https://user-images.githubusercontent.com/18017918/102939807-d0c5b100-4463-11eb-84be-37cdd11cd16e.png)
> 
> CONTENT SEO IMAGE SETTING:
> ![Content-works](https://user-images.githubusercontent.com/18017918/102939600-63b21b80-4463-11eb-9000-cb497db5d079.png)
> 
>  META IMAGE:
> `<meta content="http://scout.build/img/hero/_1200x630_crop_center-center_82_none/global.jpg?mtime=1606940875" property="og:image"> `
>

**Comment by brandondeweese** [comment] 2020-12-22 22:45
Hope that helps...

**Comment by khalwat** [comment] 2020-12-22 23:34
Very helpful, thank you, and thank you for your patience. Fixed in https://github.com/nystudio107/craft-seomatic/commit/32b6fb1fbdd52ea2ea3c163a60cbe896537bf75c

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.2.28",
```
Then do a `composer update`

**Closed as completed by khalwat** 2020-12-22 23:34 UTC
Labels: need info

**Comment by brandondeweese** [comment] 2020-12-23 14:29
Thank you!
