### ISSUE TITLE
Default Content SEO Site Name Position to Same as Global Site Name Position

### ISSUE THREAD

**Issue by zizther** [nystudio107/craft-seomatic#1321] opened 2023-05-15 14:18 UTC
### Describe the bug
Is there a way to have sections Content SEO `Site Name Position Source` to respect the Global SEO General `Site Name Position` so that it selects `Same as Global Site Name Position` by default.

At the moment it defaults to Custom Position

<img width="708" alt="Screenshot 2023-05-15 at 15 11 16" src="https://github.com/nystudio107/craft-seomatic/assets/1436378/92c1326a-dd74-4a65-a213-9041b6b3e759">

I only have a seomatic.php config file and a `seomatic-config/globalmeta/Creator.php` file

### Versions
- Plugin version: 4.0.24
- Craft version: 4.4.10.1

**Comment by khalwat** [comment] 2023-05-16 03:23
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/2b3c9c7f89e589640fe22ce8e28a59e3fa3ca791 & https://github.com/nystudio107/craft-seomatic/commit/608fe7d482ce9b5dc7c02e756462315a1e5a4ba8

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.54”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.25”,
```
Then do a `composer clear-cache && composer update`

Note: This will only apply to new sections or installs, it will not go back in and retroactively change your existing Content SEO settings for sections.

**Comment by zizther** [comment] 2023-06-21 10:45
I am using Craft 4.4.14 and SEOmatic 4.0.28

On a new instances of Craft even though I have set the Global SEO `Site Name Position`, by default new sections created have the `Site Name Position Source` set to `Custom Position` rather than `Same as Global Site Name Position`.

Is there something I need to manage this or should it be set to `Same as Global Site Name Position` for each new section by default from 4.0.25 onwards?

**Comment by kevinmu17** [comment] 2023-09-05 14:09
Any news on this issue?

**Comment by khalwat** [comment] 2023-09-06 01:27
This is a closed issue. I can re-open it if you're saying the same behavior discussed in the original post in the issue is still happening for you?

**Comment by kevinmu17** [comment] 2023-09-06 07:04
I experience the original issue + some more. 
`Craft CMS v4.5.3`
`SEOmatic v4.0.30`

The SiteName isn't appended at all, the settings are set on `Custom Position - Before` (I understand it has to be default to `Same as Global Site Name Position`) This happens also when adding a new section. 

I'm searching these settings in the DB or YAML files but can't find any SEOmatic related stuff. I have a client with 4 multi site setup and a lot of pages, they are all without the Site Name(!) The settings are set on custom position before. It only works if i go into Content SEO, go to a section, change the `Site Name Position Source` manually back and forth.

_Maybe worth noting: We work from a scaffold build where SEOmatic is default installed (this is why i think there has to be something corrupted somewhere (db/yaml))_

Also related issue #1333

**Comment by khalwat** [comment] 2023-09-06 23:05
Related: https://github.com/nystudio107/craft-seomatic/issues/1333

**Comment by J-Protz** [comment] 2023-09-06 23:10
> [#1333](https://github.com/nystudio107/craft-seomatic/issues/1321#issuecomment-1707786404)

I also am working off of a scaffold that started with craft 3.X, and was later upgraded. Unsure if this is relevant but worth nothing as I am finding the sitename needs to be toggled or resaved for every new section.

**Comment by khalwat** [comment] 2023-09-06 23:16
Can some give me steps to reproduce this issue? If I just add a new Section, the Site Name will not be appended until the Section settings are saved? Or is there more to it?

**Comment by J-Protz** [comment] 2023-09-06 23:23
@khalwat 

I created a new section called NEW TEST and went into the page itself and noted there is no sitename anywhere.

<img width="1911" alt="Screen Shot 2023-09-06 at 7 17 45 PM" src="https://github.com/nystudio107/craft-seomatic/assets/70289763/ba9a1c2b-1c65-46bb-a325-f81dceb4cbd2">

Confirmed when going in to content settings, which default to "custom/before"
<img width="1677" alt="Screen Shot 2023-09-06 at 7 18 08 PM" src="https://github.com/nystudio107/craft-seomatic/assets/70289763/000a8968-4e89-47c3-a031-3351fdbf6fee">

All I did was hit "save" in these settings, and it added the name.
<img width="1692" alt="Screen Shot 2023-09-06 at 7 18 18 PM" src="https://github.com/nystudio107/craft-seomatic/assets/70289763/a2818aa3-40db-4a28-92bd-b46f4f8802f6">


Ideally I would like all sections by default to mimic global settings. Not the end of the world, just a mild inconvenience to have to remember :)

**Comment by kevinmu17** [comment] 2023-09-07 06:53
I'm experiencing the same as @J-Protz.

> If I just add a new Section, the Site Name will not be appended until the Section settings are saved? Or is there more to it?

Nothing happens after saving the section. We saved everything manually now by going trough the SEOmatic > Content Seo.

So to break these 2 problems down:

1. Site Name Position Source is broken. (default should be global site settings Addressed in: https://github.com/nystudio107/craft-seomatic/commit/2b3c9c7f89e589640fe22ce8e28a59e3fa3ca791 & https://github.com/nystudio107/craft-seomatic/commit/608fe7d482ce9b5dc7c02e756462315a1e5a4ba8)
2. Site name isn't added at all to no sections (new or old ones) - (Structure/channel/singles)

**Comment by khalwat** [comment] 2023-09-08 17:56
You both mentioned that you are using some kind of scaffolding to set up projects.
 
It is possible that you have settings in `config/seomatic-config/` that are not up to date? These will override the default settings for newly created metabundles:

https://nystudio107.com/blog/tips-for-using-seomatic-effectively#customized-setup

**Comment by J-Protz** [comment] 2023-09-08 18:09
I thought this may be the case as well, but no we do not have any special config. If there are any files or even DB tables I can send over that'd help, that don't contain client secrets or anything like that, happy to help.

**Comment by kevinmu17** [comment] 2023-09-09 16:37
Here as well, zero config files for SEOmatic.

**Comment by khalwat** [comment] 2023-09-11 23:21
Tracked this down; this should be fixed now for newly created sections.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.60”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.31”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2023-09-11 23:21 UTC
Labels: bug

**Comment by khalwat** [comment] 2023-09-12 17:29
@kevinmu17 @J-Protz give this new version a whirl, and let me know if this solves the issue for you. I will cut a release once I get confirmation from you.
