### ISSUE TITLE
Content SEO page display error due to Endpoint served from HTTP

### ISSUE THREAD

**Issue by ryotadialpad** [nystudio107/craft-seomatic#451] opened 2019-08-02 18:44 UTC
When visiting admin/seomatic/content/, nothing displays only default content display due to following JS error saying API served over different protocol:

<img width="1254" alt="Screen Shot 2019-08-02 at 11 38 31 AM" src="https://user-images.githubusercontent.com/46463521/62391750-88c68700-b51a-11e9-88c8-7a56c06736b4.png">

```
Mixed Content: The page at 'https://www.SITE.com/admin/seomatic/content/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.SITE.com/seomatic/content-seo/meta-bundles/?sort=sourceName%7Casc&page=1&per_page=20&siteId=1'. 
This request has been blocked; the content must be served over HTTPS.
Vuetable.vue:772 
load-error Error: Network Error
    at e.exports (createError.js:15)
    at XMLHttpRequest.f.onerror (xhr.js:87)
```

This page does work on our local development environment, where site protocol is HTTP.

SEOMatic version: 3.2.18
CraftCMS version: 3.1.33

**Comment by khalwat** [comment] 2019-08-06 15:07
Can you clarify for me:

1) Are you running https in this environment?
2) Where is the site hosted?

I think this is likely going to be a devops / local dev setup issue.

**Comment by ryotadialpad** [comment] 2019-08-06 16:34
@khalwat thanks for reply,
Environment we're having issue is up on production environment, hosted on google app engine with HTTPS. 
It was fine up until version 3.2.17 and started having issue from version 3.2.18 (rolled back to 3.2.17 for now and that page works fine)

**Comment by khalwat** [comment] 2019-08-07 16:46
I think something is not quite right with your setup -- what is the `siteUrl` set to me for your config?

**Comment by khalwat** [comment] 2019-08-07 17:00
Can you try installing my Webperf and/or Retour plugins to see if you don't encounter the same issue?

**Comment by ryotadialpad** [comment] 2019-08-08 16:57
@khalwat 
Both baseUrl and siteUrl in general.php of Craft is set to `https` on production environment (where there's issue) and is set to `http` on local development environment (where there's NO issue).

My colleague is experiencing exactly same issue with Retour plugin and he reported issue here:
https://github.com/nystudio107/craft-retour/issues/70

**Comment by khalwat** [comment] 2019-08-09 13:44
I think these are both caused by the same root problem.

Can you show me how you're declaring your `baseUrl` and `siteUrl` in `genera.php` please?

**Comment by khalwat** [comment] 2019-08-09 14:02
The API URL is declared as a relative URL:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/assetbundles/seomatic/src/vue/ContentSeoTable.vue#L12

**something** is causing this to resolve to `http`

**Comment by khalwat** [comment] 2019-08-10 15:03
Are you using Project Config?

Do you have a `DEFAULT_SITE_URL` in your `.env` file?

I'm thinking there is probably some kind of setting in in Google App Engine setting, but I'm not familiar with it. Does this help? https://stackoverflow.com/questions/5367974/https-only-in-google-app-engine

**Comment by khalwat** [comment] 2019-08-22 00:10
Let me know if you figure anything out @ryotadialpad  -- I'm reasonably sure this is a devops issue, and not a SEOmatic issue. But I'd be happy to assist if you find otherwise.

**Comment by khalwat** [comment] 2019-08-22 12:12
Will re-open if additional information is made available.

**Comment by khalwat** [comment] 2019-09-07 20:01
So I had a lightbulb moment @ryotadialpad -- let me know if this fixes it for you:

https://github.com/nystudio107/craft-seomatic/commit/d07c1002ee212961041dede4246969e4b60338b9

Set your semVer in your `composer.json` to `"dev-develop"` and do a `composer update`

**Comment by khalwat** [comment] 2019-09-09 15:56
This should be fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.24

**Closed as completed by khalwat** 2019-09-09 15:56 UTC
Labels: need info

**Comment by ryanmasuga** [comment] 2022-07-05 18:37
We're having this exact issue today. Didn't know if I should add onto this issue, or start a new one. We don't know where this 'http' could be coming from. Environment var is https, site settings reference the env var - everything is over https.

**Entities not loading**
![seomatic-http-01](https://user-images.githubusercontent.com/988995/177392622-ed40f2fb-e8f1-42ab-b134-b95a5ab6d4b6.jpg)

**Channel list in Content SEO not displaying**
![seomatic-http-02](https://user-images.githubusercontent.com/988995/177392634-31146867-84e3-4744-98c1-1c392e1ca3a4.jpg)
 
SEOmatic is working correctly in our local environments. 

Craft CMS 4.0.6

**Plugins**
Redactor 3.0.2
SEOmatic 4.0.6

PHP 8.1.7

**Comment by khalwat** [comment] 2022-07-05 18:42
Probably your site URL is not set properly, is what I'd guess @ryanmasuga 

Make sure it is a fully qualified URL for your site URL. It's using the URL that Craft tells it to use:

```twig
{{ actionUrl('seomatic/content-seo/meta-bundles') }}
```

But if your site URL isn't properly set up, Craft's `actionUrl()` isn't going to return the right thing.

**Comment by ryanmasuga** [comment] 2022-07-05 18:57
We tracked this down and it had to do with htaccess rules we added from this Stack Exchange post about [removing index.php?p= permanently](https://craftcms.stackexchange.com/questions/19235/how-to-remove-index-phpp-permanently/19237#19237). Removing those two rules allowed SEOmatic to do its thing again. 

As an aside, one shouldn't _need_ those rules if canonicals are set on your pages.
