### ISSUE TITLE
SEO preview - css error

### ISSUE THREAD

**Issue by piotrpog** [nystudio107/craft-seomatic#849] opened 2021-03-09 21:36 UTC
WIth longer addresses, there is css bug:

![image](https://user-images.githubusercontent.com/42622545/110541304-d90abf80-8127-11eb-8bf3-6e4a439c8eb0.png)

**Comment by khalwat** [comment] 2021-03-11 02:59
Can you give me some context here? Where is this screenshot from? I'm unable to reproduce this in the sidebar, or in the Live Preview.

**Comment by khalwat** [comment] 2021-03-11 03:09
Ah never mind, I found a way to reproduce it. Fixed in https://github.com/nystudio107/craft-seomatic/commit/d728ad09892a8253418f4e4328a6e78f99137dc5

**Closed as completed by khalwat** 2021-03-11 03:09 UTC
Labels: bug
