### ISSUE TITLE
Content SEO section: category type not showing correct name and amount of entries

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft-seomatic#63] opened 2018-04-06 09:05 UTC
We noticed that in the section Content SEO the category type is not showing the correct "Name" and the amount of "Entries" that are created underneath a category.

Already cleared the cache. That's didn't help.
Any suggestions or is this a bug?

If more info is needed please let us know.

Running specs:
- Craft: 3.0.1
- SEO Matic: 3.0.0-beta.20

**Comment by khalwat** [comment] 2018-04-06 15:53
Will investigate, and try to replicate locally here, thanks!

**Comment by khalwat** [comment] 2018-04-12 07:45
I'm unable to reproduce this; can you tell me anything more in terms of how to reproduce it? Did you add/delete Category Groups or such?

**Comment by boldenamsterdam** [comment] 2018-04-12 08:08
From some of the category groups we changed the "name" and the "handle".

In total we have 4 category groups.

3 groups have a "Max level" of 1
1 group has a "Max level" of 2

All categories have 2 or more entries.

**Comment by khalwat** [comment] 2018-04-14 01:22
Ahhhh.  I think it may not be handling the case of changing the handle.

**Comment by khalwat** [comment] 2018-04-14 01:55
Addressed in https://github.com/nystudio107/craft-seomatic/commit/13390452fcb2bf8ac798b28519780432c2ab0329

**Closed as completed by khalwat** 2018-04-14 01:55 UTC
Labels: bug
