### ISSUE TITLE
Facebook and Twitter image tags aren't rendered when tabs are present without image field

### ISSUE THREAD

**Issue by robmcfadden** [nystudio107/craft-seomatic#261] opened 2018-11-05 18:59 UTC
Facebook and Twitter images are set to "Same as SEO Image" in Global SEO and Content SEO settings. Populating the SEO Image field on an entry does not show in the previews or the front-end source, however. If I add the "Twitter Image" and "Facebook OpenGraph Image" fields to their respective tabs on the field, the previews still don't work, but the images do show up on the front-end. Thanks in advance!

cc: @timkelty 

PHP version | 7.1.21
MySQL 5.7.23
Craft Pro 3.0.29
Seomatic 3.1.25

**Comment by khalwat** [comment] 2018-11-05 19:25
Just to be clear, this sounds like a regression in 3.1.25 yes? It worked as expected in previous versions?

**Comment by robmcfadden** [comment] 2018-11-05 19:27
A regression, yes, but I'm not sure exactly where it happened. Seemed to be having this issue in 3.1.24 as well.

**Comment by khalwat** [comment] 2018-11-05 19:29
Just to make sure... did you re-save your General/Twitter/Facebook settings for Global SEO, and Content SEO first? I just want to make sure this is not a stale data issue of some kind.

**Comment by robmcfadden** [comment] 2018-11-05 19:31
Re-saved all of those for both Global and Content. Cleared all caches and re-saved the entry. No go.

**Comment by khalwat** [comment] 2018-11-05 23:15
So.... I'm unable to reproduce this, at least how I understand your settings to be.

I have an SEO Settings field with _only_ the General tab visible. I'm seeing all of the previews as expected. Can you post some screenshots of the Content SEO settings and Field Settings that you have?

Also it's possible that it'd be quickest to work this out if we did a video conference so I could see what's going on. Doable?

**Comment by robmcfadden** [comment] 2018-11-06 14:47
I am also using ImageOptimize and I think that might be part of the issue that I'm seeing.

If I disable ImageOptimize, everything works as it should! With ImageOptimize, I need to have the Facebook and Twitter image fields enabled and set to "Same as SEO Image" on their respective tabs on the SEOmatic field, but that only gets the source code to look correct, not the previews. Disabling ImageOptimize fixes the preview and source code, while not requiring me to have the Facebook and Twitter tabs on the field at all, just like your test.

Let me know if that changes what info you need from me. If you'd still like a call, I may have @timkelty help out with that as he's a bit better at explaining/debugging this stuff.

**Comment by timkelty** [comment] 2018-11-06 18:20
Did some testing with @robmcfadden, here's the recap:

The issues with the previews is fixed here: https://github.com/nystudio107/craft-seomatic/pull/263

The issue that remains is this:

If your field _has_ the Facebook/Twitter tabs AND they do not have the image field, the tags do not fall back as expected (no og:image tag is rendered).

**Comment by khalwat** [comment] 2018-11-06 19:50
Ahhh, thank you for the clarification, that makes sense. I was testing the opposite setup!

**Comment by khalwat** [comment] 2018-11-07 19:58
Yeah this was a regression. Fixed in https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.28

**Closed as completed by khalwat** 2018-11-07 19:58 UTC
Labels: bug

**Comment by robmcfadden** [comment] 2018-11-07 20:02
Thanks!
