### ISSUE TITLE
Products json-ld data outputting as webpage not product when IndividualProduct is used.

### ISSUE THREAD

**Issue by bossanova808** [nystudio107/craft-seomatic#355] opened 2019-03-23 00:44 UTC
As per our Discord chat...

If I set my MainEntityOfPage of products to `IndividualProduct`, then the json-ld output is set to type `webpage` although there is actually offer data in there:

```
{
    "@context": "http://schema.org",
    "@type": "WebPage",
    "author": {
        "@id": "https://imagescience.com.au/#identity"
    },
    "copyrightHolder": {
        "@id": "https://imagescience.com.au/#identity"
    },
    "copyrightYear": "2015-06-23T16:56:00+10:00",
    "creator": {
        "@id": "https://imagescience.com.au/#creator"
    },
    "dateModified": "2019-03-21T12:20:26+11:00",
    "datePublished": "2015-06-23T16:56:00+10:00",
    "description": "The benchmark A2 fine art printer today, and our default recommendation for anyone wanting to make big, beautiful, archival prints in-house.",
    "headline": "Epson SureColor P800 A2 Inkjet Printer",
    "image": {
        "@type": "ImageObject",
        "url": "https://c3-dev.imagescience.net.au/_201809_imager-transforms/s3images/Products/Epson-Printers/P800/1628/Epson-SureColor-P800-A2-Inkjet-Printer_21c7204107c0fbddd8d98f5d8b926964.jpg"
    },
    "inLanguage": "en-au",
    "mainEntityOfPage": "https://c3-dev.imagescience.net.au/products/epson-printers/epson-surecolor-p800-a2-inkjet-printer",
    "name": "Epson SureColor P800 A2 Inkjet Printer",
    "offers": {
        "@type": "Offer",
        "availability": "http://schema.org/InStock",
        "offeredBy": {
            "@id": "https://imagescience.com.au/#identity"
        },
        "price": "1,695.00",
        "priceCurrency": "AUD",
        "seller": {
            "@id": "https://imagescience.com.au/#identity"
        },
        "url": "https://c3-dev.imagescience.net.au/products/epson-printers/epson-surecolor-p800-a2-inkjet-printer"
    },
    "publisher": {
        "@id": "https://imagescience.com.au/#creator"
    },
    "url": "https://c3-dev.imagescience.net.au/products/epson-printers/epson-surecolor-p800-a2-inkjet-printer"
}
```

If I change it to just `Product` then the json-ld is correct:

```
{
    "@context": "http://schema.org",
    "@type": "Product",
    "description": "The benchmark A2 fine art printer today, and our default recommendation for anyone wanting to make big, beautiful, archival prints in-house.",
    "image": {
        "@type": "ImageObject",
        "url": "https://c3-dev.imagescience.net.au/_201809_imager-transforms/s3images/Products/Epson-Printers/P800/1628/Epson-SureColor-P800-A2-Inkjet-Printer_21c7204107c0fbddd8d98f5d8b926964.jpg"
    },
    "mainEntityOfPage": "https://c3-dev.imagescience.net.au/products/epson-printers/epson-surecolor-p800-a2-inkjet-printer",
    "name": "Epson SureColor P800 A2 Inkjet Printer",
    "offers": {
        "@type": "Offer",
        "availability": "http://schema.org/InStock",
        "offeredBy": {
            "@id": "https://imagescience.com.au/#identity"
        },
        "price": "1,695.00",
        "priceCurrency": "AUD",
        "seller": {
            "@id": "https://imagescience.com.au/#identity"
        },
        "url": "https://c3-dev.imagescience.net.au/products/epson-printers/epson-surecolor-p800-a2-inkjet-printer"
    },
    "sku": "HEP_SCP800",
    "url": "https://c3-dev.imagescience.net.au/products/epson-printers/epson-surecolor-p800-a2-inkjet-printer"
}
```

Given I use have a lot of both `IndividualProduct` pages and pages that list variants, where I use `SomeProducts` .. I feel I really need both options & obviously the `SomeProducts` pages should output a list of products somehow, but I have not yet been able to test that as all my products have been coming up as `webpage`

Much thanks, as ever, for your help & attention Andrew (and overall I think the new SEOmatic approach is great!).

**Comment by khalwat** [comment] 2019-03-25 13:49
This does work when the type is `Product`, interestingly.

**Comment by bossanova808** [comment] 2019-03-25 23:51
Yep I should have noted that, sorry!

I should note I think the issue is a general one -> if I set e.g. CreativeWork -> Blog - it produces `Webpage` in the json-ld again.   If I leave it set only to `CreativeWork` - the I get json-ld with `CreativeWork` as expected.

So put simply the bug seems to kick in with ANY use of those second or third levels in the Main Entity of Page bit.

**Comment by khalwat** [comment] 2019-03-26 20:15
So I'm unable to reproduce that here @bossanova808 -- I have several live production sites that use sub-types for the JSON-LD and they are working as expected. Something very odd is going on here...

**Comment by bossanova808** [comment] 2019-03-26 20:18
Hmm, ok then.  Can you maybe point me at the area of code where it determines what jsonld to build, and I'll do some tracing to see if I can figure it out?

Sent on the go...

________________________________

**Comment by bossanova808** [comment] 2019-03-26 22:56
Yeah ok, so looking at it - in the db, despite the page setting being what I want:

![image](https://user-images.githubusercontent.com/731309/55038982-a0769600-5076-11e9-80b0-216822979763.png)

..in the actual DB there is:

![image](https://user-images.githubusercontent.com/731309/55038559-5640e500-5075-11e9-9ebe-dc903db2d64f.png)

It's like the settings have not saved properly....or when I load those content settings, it is not actually getting them from the DB (given it has the right values?).

So if I manually go through,visit each content settings page, and explicitly re-save these again (without changing any settings), then they seem to update in the DB...

![image](https://user-images.githubusercontent.com/731309/55038935-7a50f600-5076-11e9-958f-5b35b0c09715.png)

So definitely a bit odd, that those settings pages load up and don't reflect what is actually in the DB.

But I'm happy to put it down to Gremlins for now....assuming they don't keep resetting for as-yet-unknown reasons!

**Comment by bossanova808** [comment] 2019-03-26 23:13
(just to be sure I have checked these settings survive a full migration from scratch (where I dump the metabundles db, then re-import it post migration) - and they definitely do survive (and have been since I did this).

Definitely going with Gremlins for now, and will close this...thanks for your help in getting me to the heart of the issue in any case!

**Comment by bossanova808** [comment] 2019-03-27 02:01
So, we have determined this occurs specifically if you save Content SEO settings from a 'tab' other than general.

According to my logging, it's falling back to the default of 'WebPage' when save on those other tabs is set.

Here's a save from the general tab:
```
INFO: 2019-03-27 11:57:47 globalsSettings['mainEntityOfPage'] not set.
INFO: 2019-03-27 11:57:47 self::SCHEMA_TYPES is:
INFO: 2019-03-27 11:57:47
Array
(
    [0] => siteSpecificType
    [1] => siteSubType
    [2] => siteType
)
INFO: 2019-03-27 11:57:47 In loop with schemaType siteSpecificType
INFO: 2019-03-27 11:57:47 settings[siteSpecificType] is none
INFO: 2019-03-27 11:57:47 In loop with schemaType siteSubType
INFO: 2019-03-27 11:57:47 settings[siteSubType] is Blog
INFO: 2019-03-27 11:57:47 Returning settings[siteSubType] which is Blog=
INFO: 2019-03-27 11:57:47 globalsSettings['mainEntityOfPage'] finishes as Blog
```

And from the Twitter tab:

```
NFO: 2019-03-27 11:57:53 globalsSettings['mainEntityOfPage'] not set.
INFO: 2019-03-27 11:57:53 self::SCHEMA_TYPES is:
INFO: 2019-03-27 11:57:53
Array
(
    [0] => siteSpecificType
    [1] => siteSubType
    [2] => siteType
)
INFO: 2019-03-27 11:57:53 In loop with schemaType siteSpecificType
INFO: 2019-03-27 11:57:53 settings[siteSpecificType] is not set
INFO: 2019-03-27 11:57:53 In loop with schemaType siteSubType
INFO: 2019-03-27 11:57:53 settings[siteSubType] is not set
INFO: 2019-03-27 11:57:53 In loop with schemaType siteType
INFO: 2019-03-27 11:57:53 settings[siteType] is not set
INFO: 2019-03-27 11:57:53 Fallen through - returning default Webpage
INFO: 2019-03-27 11:57:53 globalsSettings['mainEntityOfPage'] finishes as WebPage
```

The issue appears to be the content of $bundleSettings:
Saving from General:
```
Array
(
    [siteType] => CreativeWork
    [siteSubType] => Blog
    [siteSpecificType] => none
    [seoTitleSource] => fromField
    [seoTitleField] => title
    [siteNamePositionSource] => sameAsGlobal
    [seoDescriptionSource] => summaryFromField
    [seoDescriptionField] => oneLineDescription
    [seoKeywordsSource] => keywordsFromField
    [seoKeywordsField] => blocks
    [seoImageSource] => fromField
    [seoImageField] => masterImage
    [seoImageIds] => Array
        (
            [0] => 46586
        )

    [seoImageTransform] => 1
    [seoImageTransformMode] => fit
    [ogImageSource] => fromField
    [ogImageField] => masterImage
    [ogImageIds] => 
    [ogImageTransform] => 1
    [ogImageTransformMode] => fit
    [twitterImageSource] => fromField
    [twitterImageField] => masterImage
    [twitterImageIds] => 
    [twitterImageTransform] => 1
    [twitterImageTransformMode] => fit
    [seoImageDescriptionSource] => fromCustom
    [seoImageDescriptionField] => title
)
```
Saving from Twitter:
```
Array
(
    [twitterCreatorSource] => sameAsSiteTwitter
    [twitterCreatorField] => bio
    [twitterTitleSource] => sameAsSeo
    [twitterTitleField] => title
    [twitterSiteNamePositionSource] => sameAsGlobal
    [twitterDescriptionSource] => fromField
    [twitterDescriptionField] => oneLineDescription
    [seoImageSource] => fromField
    [seoImageField] => masterImage
    [seoImageIds] => Array
        (
            [0] => 46586
        )

    [seoImageTransform] => 1
    [seoImageTransformMode] => fit
    [twitterImageSource] => fromField
    [twitterImageField] => masterImage
    [twitterImageIds] => 
    [twitterImageTransform] => 1
    [twitterImageTransformMode] => fit
    [twitterImageDescriptionSource] => sameAsSeo
    [twitterImageDescriptionField] => title
)
```

...just putting this all here for the sake of a record.

Let me know if you still can't reproduce and I can dig further.

**Comment by khalwat** [comment] 2019-04-01 22:21
Yeah it should be checking this field for emptiness:
```
    [siteType]
```

...and not attempting to set the `mainEntityOfPage` if it's empty.

**Comment by khalwat** [comment] 2019-04-01 22:27
Fixed in https://github.com/nystudio107/craft-seomatic/commit/04eeb5b2ed55e1f794ad9fb06173e1f20fc9916c

**Closed as completed by khalwat** 2019-04-01 22:27 UTC
Labels: bug, need info
