### ISSUE TITLE
Incorrect URLs generated when siteUrl is overridden using an alias

### ISSUE THREAD

**Issue by howells** [nystudio107/craft-seomatic#593] opened 2020-03-27 02:11 UTC
Hi - I've specified an alias called @client as my siteUrl param, and its value is `http://example.test:8888/`. However, when entries' urls are generated using SEOmatic, the URLs look something like `example.test:8888/example.test:8888/recipes/recipe-slug`.

Also, even with a siteUrl specified, the Twitter and Facebook previews don't show the correct URL: it shows Craft's own siteUrl.

Finally - it would be awesome if the sitemap could point to where Craft is, but have all URLs point to whatever is specified in siteUrl.

**Comment by khalwat** [comment] 2020-03-27 22:23
When you say `siteUrl` param, what do you mean exactly? Are you talking about the Site URL Override feature?

If yes, what happens if you set it to a constant as opposed to an alias?

@howells the latter part of what you're asking for is invalid; sitemaps need to exist in the same top level domain as the URLs and sitemap indexes they contain:

https://www.sitemaps.org/protocol.html

**Comment by howells** [comment] 2020-03-27 22:32
Sorry I wasn't clear at all: it's when I set `http://example.test:8888/` as the site url override feature. I just tried changing this to an environment variable, and the same issue occurs. Let me know if you need any more info.

**Comment by khalwat** [comment] 2020-03-27 22:34
Can you please try it as a _constant_ -- e.g. put http://example.test:8888/ into the field and see what happens? Also try without the port?

**Comment by howells** [comment] 2020-03-27 23:05
Doh, sorry - yes even entered with a constant the same thing happens, and removing the port makes no difference:

<img width="337" alt="Screenshot 2020-03-27 at 23 01 36" src="https://user-images.githubusercontent.com/145849/77807273-40e30a00-707f-11ea-994c-724feca28988.png">

<img width="502" alt="Screenshot 2020-03-27 at 23-1 01 08" src="https://user-images.githubusercontent.com/145849/77807313-5e17d880-707f-11ea-89db-7e36b59d99f7.png">

<img width="425" alt="Screenshot 2020-03-27 at 23-1 01 30" src="https://user-images.githubusercontent.com/145849/77807315-5eb06f00-707f-11ea-8e29-6cd3f5a429d4.png">

**Comment by khalwat** [comment] 2020-03-28 13:53
Can you tell me what version of Craft you're using, and what version of SEOmatic you're using?

I tried to replicate this issue with SEOmatic 3.2.49 (the latest) and was unable to:

<img width="563" alt="Screen Shot 2020-03-28 at 9 53 07 AM" src="https://user-images.githubusercontent.com/7570798/77824558-f8a50580-70d9-11ea-893a-6e6c718739cd.png">
<img width="389" alt="Screen Shot 2020-03-28 at 9 52 36 AM" src="https://user-images.githubusercontent.com/7570798/77824559-f93d9c00-70d9-11ea-9b04-1a9362dd7eee.png">
<img width="447" alt="Screen Shot 2020-03-28 at 9 52 24 AM" src="https://user-images.githubusercontent.com/7570798/77824560-f93d9c00-70d9-11ea-914d-2d523deebe9c.png">

**Comment by howells** [comment] 2020-03-29 00:36
Craft 3.4.11 and SEOmatic 3.2.49. Not sure how else I might have configured it unusually. It's in headless mode if that makes a difference.

**Comment by khalwat** [comment] 2020-03-29 16:18
What is your actual `siteUrl` set to?

What happens if you turn headless mode off?

**Comment by khalwat** [comment] 2020-03-29 16:19
I'm betting your actual `siteUrl` is set to:

`example.test:8888`

ie, with no protocol.

**Comment by howells** [comment] 2020-03-30 10:27
My siteUrl was set using a ENV variable, http://example.test:8888 - I tried setting this to a constant in general.php for both * and dev, but the same issue occurred. Also tried removing the protocol, and port number, and tried turning headless off, changing the site base URL, but no difference. I can't think of what other variables I could tweak to have an effect.

**Comment by andrewfairlie** [comment] 2020-04-01 12:06
I'm having a similar bug when using `Site URL Override` for a Gatsby site. The canonical URL (and it only ever seems to happen on Canonical URL, all others are fine) is set to (domain replaced to google.com for client privacy)

`https://google.com/google.com/page-name`

Craft 3.4.12 and SEOMatic 3.2.49

**Comment by khalwat** [comment] 2020-04-01 12:07
@andrewfairlie are you seeing this when you view the source of the frontend of the page? or only in the preview inside of the Craft CP?

**Comment by andrewfairlie** [comment] 2020-04-01 12:10
This is a site without a Twig frontend, but I'm seeing it on the GraphQL explorer and if I use the social media preview function it shows this (changed for client privacy)

![image](https://user-images.githubusercontent.com/1772888/78135681-32e40f00-741a-11ea-9fcc-7a7770b5a29c.png)

If I turn the headless mode off it makes no difference.

**Comment by khalwat** [comment] 2020-04-01 12:12
I would absolutely love to fix this issue, but if I can't reproduce it, it makes diagnosing and fixing it difficult.

Any clues either of you can provide me with would be wonderful.

In lieu of a break there, I think it might be best if we did a screen share to try to diagnose what is going wrong here. You can hit me on up the Craft Discord to arrange that at your convenience, my name on there is `andrew.welch`

**Comment by andrewfairlie** [comment] 2020-04-01 12:13
@khalwat I'm going to put an hour aside here and see if I can fix it and will put a pull request in if I crack it 👍

**Comment by khalwat** [comment] 2020-04-01 12:14
@andrewfairlie awesome -- my starting point would be setting a breakpoint here:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/UrlHelper.php#L40

...and seeing what the values coming in and out are.

**Comment by andrewfairlie** [comment] 2020-04-01 12:21
@khalwat I think I've found the culprit but am unsure if this will cause any side effects

If I change https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/DynamicMeta.php#L97 from

```php
        return UrlHelper::absoluteUrlWithProtocol($url);
```

to 

```php
        return $url;
```

It works. So I suspect the fault is related to that. I'll keep digging.

**Comment by andrewfairlie** [comment] 2020-04-01 12:27
I'm not much of a PHP guy, but I wonder if `UrlHelper::absoluteUrlWithProtocol` is doubling up some how?

**Comment by andrewfairlie** [comment] 2020-04-01 12:37
If I remove the protocol from the `Site URL Override` it seems to triple up.

![image](https://user-images.githubusercontent.com/1772888/78137859-e4d10a80-741d-11ea-8bfd-ea1518b63b84.png)

**Comment by khalwat** [comment] 2020-04-01 13:16
@andrewfairlie can you confirm that you also are using an environment variable or alias for the **Site URL Override** setting? If not, can you provide exactly what you're using?

**Comment by andrewfairlie** [comment] 2020-04-01 13:40
I am using an environment variable, but the same applies when the URL is written directly into the field as well.

**Comment by khalwat** [comment] 2020-04-01 13:42
Yeah that's the part that doesn't make any sense to me. 

Can you set a breakpoint in the `absoluteUrlWithProtocol()` method to see what's being passed in and out?

**Comment by khalwat** [comment] 2020-04-02 16:11
Thanks to @andrewfairlie I think we should have this nailed down -- fix is in https://github.com/nystudio107/craft-seomatic/commit/7c6a5551296ad938b3c59863150fa5c4dc725b98

Can you set your semVer to `dev-develop` and do a `composer update` to test whether this works for you?

**Comment by andrewfairlie** [comment] 2020-04-02 16:35
Seems to have done the job for me @khalwat

**Comment by howells** [comment] 2020-04-02 16:53
Yeah seems to be working, thanks @andrewfairlie. I've noticed that the overridden URL doesn't seem to be reflected in the Facebook or Slack previews in the SEO Preview when editing an entry.

**Comment by khalwat** [comment] 2020-04-02 17:38
@howells previews fixed in https://github.com/nystudio107/craft-seomatic/commit/c42b302681a9bacdc19f8cee4c309b3c821ba420

**Closed as completed by khalwat** 2020-04-02 17:38 UTC
Labels: need info
