### ISSUE TITLE
Entry Type SEO Improvement

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#631] opened 2020-05-11 15:04 UTC
I started creating entry type SEO and when I do that I see that the section is duplicated in the SEOmatic control panel - see screenshot
![image](https://user-images.githubusercontent.com/6899490/81577197-26d36180-9377-11ea-9705-54a067edb288.png)

What I'd like to see is that next to the section title add the entry type handle/label so that it is clear what each of these sections with duplicate titles is for.

**Comment by khalwat** [comment] 2020-05-11 15:44
Duplicate of https://github.com/nystudio107/craft-seomatic/issues/618

**Closed as completed by khalwat** 2020-05-11 15:44 UTC
