### ISSUE TITLE
Main Entity of Page changing on save

### ISSUE THREAD

**Issue by jreb** [nystudio107/craft-seomatic#762] opened 2020-10-01 19:13 UTC
### Describe the bug
When saving in content SEO, the Main Entity of Page field changes, from a child to the parent

### To reproduce
In content SEO select a sub-Main Entity of Page, for example 'Comedy Event' (under Event) and save. This works and shows in the code on the front end. Now save the page (with or without other changes) and the Main Entity of Page changes to 'Event', this also changes in the front end.

For now, I have manually cleared all Main Entity of Page fields, though interestingly this doesn't appear to fallback to what is set in global... but that may be another issue, or me misunderstanding how it works.

### Expected behaviour
That the Main Entity of Page doesn't change unless you tell it too.

### Versions
PHP - 7.4.8
SEOMatic - 3.3.21

**Comment by engram-design** [comment] 2020-10-08 04:40
I'm seeing that as well with site settings Organization and Local Business. It's pretty inconsistent and sometimes need to save a few times: https://d.pr/v/04hYn9

**Comment by khalwat** [comment] 2020-10-20 15:36
I'd love to be able to reproduce this, but thus far have been unable to. Do either of you have anything to narrow this down?

**Comment by outline4** [comment] 2020-10-23 14:36
I am having the same problem.  
It changes from "HomeAndConstructionBusiness" to "Organisation".  

It's hard to tell when this happens, because sometimes it stays, even when cleaning cache, but sometimes it deletes it... 

I've noticed that with slow connections it tends to clear this value more often? could that even be?

**Comment by khalwat** [comment] 2020-10-23 14:45
Very odd. Welp, I'll try to reproduce it. If it's inconsistent like this, it's almost certainly something timing related, and very likely in the JavaScript.

**Comment by khalwat** [comment] 2020-10-23 14:48
@engram-design in that video, are you reloading the page? Or are you clicking on Save? Hoping for some context to try to reproduce this.

**Comment by outline4** [comment] 2020-10-23 15:04
Ok, one way to reproduce it on my environment is: 
In Content SEO General -> Copy Settings from another site: After hitting save, the Main Entity of Page is set to a value that is hierarchal below the initial value. 
E.g. „Organisation -> LocalBusiness -> HomeAndConstructionBusiness" to "Organisation"

**Comment by outline4** [comment] 2020-10-23 16:48
When it loads it adds (unknown) at the end of the name: 
`Organisation.LocalBusiness.HomeAndConstructionBusiness (unknown)`

When you save it again, it will loose the value and drop to 
`Organization (unknown)`

After that, it'll stay on that value, even if the (unknown) is present. 

Hope you can fix that soon...

**Comment by sunscreem** [comment] 2020-11-01 19:20
Hey @khalwat sorry to "bug" (ahem) you on this - will you get chance to have a look at this any time soon?

**Comment by khalwat** [comment] 2020-11-01 19:22
I've looked at it, but I haven't figured out a proper fix yet.

**Comment by khalwat** [comment] 2020-11-18 16:48
So that ended up taking far more time than it should have, but I have it sorted. It was a silly error. 

Fixed in https://github.com/nystudio107/craft-seomatic/commit/3e2cad26193654999d6ece747bee7e8d5e0358f6

**Closed as completed by khalwat** 2020-11-18 16:48 UTC
Labels: need info

**Comment by sunscreem** [comment] 2020-11-18 17:55
@khalwat Thank you sir!
