### ISSUE TITLE
Layout Issue on general settings

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-seomatic#721] opened 2020-08-14 14:41 UTC
### Describe the bug

Visit the SEOmatic settings > general page and the main entity layout is borked. See screenshot

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Screenshots
[
![borked](https://user-images.githubusercontent.com/6899490/90261212-a8c1a380-de1a-11ea-8574-2c7c1da9f380.jpg)
](url)

### Versions
- Plugin version:3.3.14
- Craft version:3.5.4

**Comment by khalwat** [comment] 2020-08-14 15:37
I can't reproduce this issue -- can you provide more information @CreateSean ?

<img width="1639" alt="Screen Shot 2020-08-14 at 11 37 31 AM" src="https://user-images.githubusercontent.com/7570798/90266795-8f245a00-de22-11ea-8e54-8d23b3ecffe2.png">

**Comment by CreateSean** [comment] 2020-08-14 17:10
I checked Chrome, Edge, and FF - all look the same to me. Also there are no errors in the console so not sure how to provide more information.

I also nuked the vendor folder and ran `composer install` again issue still exists

**Comment by khalwat** [comment] 2020-08-14 18:51
Can you try looking at another site? Maybe there is some other plugin/CSS/devops setup or something involved here?

**Comment by CreateSean** [comment] 2020-08-15 14:39
I only have one other site updated to latest craft and seomatic and that site is having the same issue.

**Comment by khalwat** [comment] 2020-08-15 14:40
Any way I can get a login on one of the sites to have a look?

**Comment by CreateSean** [comment] 2020-08-15 14:41
@khalwat Sure I'lll create a user account for you - they only exist on staging ATM. could you DM the email to use on discord?

**Comment by CreateSean** [comment] 2020-08-15 15:05
@khalwat I updated my company site to craft **3.5.4** and SEOmatic **3.3..15** and the issue appeared after updating.

**Comment by khalwat** [comment] 2020-08-15 15:29
Fixed in https://github.com/nystudio107/craft-seomatic/commit/b75b20a6009df3262412a2d48a07db2ecff0aeca

**Closed as completed by khalwat** 2020-08-15 15:29 UTC
Labels: need info
