### ISSUE TITLE
Can I get seomatic settings by section handle or URI in a template?

### ISSUE THREAD

**Issue by RosanaRufer** [nystudio107/craft-seomatic#107] opened 2018-05-14 07:58 UTC
As long as I have understood, when I do `seomatic.meta` in a template, I am accessing the meta settings object that SEOmatic assigned to the template, based on the section that the template was assigned to. 

I have a scenario where multiple URLs map to the same template (using `routes.php`) and I set the template's entry, from the template, based on the URI but SEOmatic doesn't know about this and the `seomatic` object contains the `gobal` configuration instead of the section's.

I'm using `{% do seomatic.helper.loadMetadataForUri(URI) %}` but it's not working.

Thank you

**Comment by Totemika** [comment] 2018-05-14 08:35
Sorry

**Comment by RosanaRufer** [comment] 2018-05-14 11:08
How does this helper work? 
I'm using it, as a test, in my base template like:
`{% do seomatic.helper.loadMetadataForUri('blog') %}`

For `mysite.com/blog` it renders the **content SEO** I configured for the **'blog' entry** but for `mysite.com/ca/blog` it's rendering the **global SEO**.

I also tried disabling automatic render in the plugin settings and doing `<title>{{ seomatic.meta.seoTitle }}  </title>` after 'loading metadata for blog' but the result is the same...

**Note:** 'ca' is just a named parameter; not the url a different site.

**Comment by khalwat** [comment] 2018-05-14 20:56
Yes, you can do this...

So what you can do is just use `seomatic.helper.loadMetadataForUri(URI, SITE_ID)`

https://github.com/nystudio107/craft-seomatic#helper-functions-seomatichelper

**Comment by RosanaRufer** [comment] 2018-05-15 21:11
@khalwat I could reproduce this “issue” (I hope the issue is in how I understood it works) on a blank site:

https://github.com/Totemika/testing-site

The `routes.php` has:
```
return [
	'/<country_code:[a-z]{2}(-[a-z]{2})?>' => ['template' => 'index'],
	'<country_code:[a-z]{2}(-[a-z]{2})?>/<section_handler:pricing>' => ['template' => 'pricing'],
];
```

And the base template :

```
{% if entry is not defined %}
	{# Entry is not defined because we have a country_code in the URL. See routes.php #}
	{% set entry = craft.entries.section(section_handler|default('homePage')).one() %}
	{% do seomatic.helper.loadMetadataForUri(entry.uri) %}
{% endif %}
```


![seomatic-country-codes](https://user-images.githubusercontent.com/4906291/40083637-bafb73ca-588c-11e8-9e11-bf895d116f4a.gif)

**Comment by khalwat** [comment] 2018-05-15 22:01
Yeah that should work, it should load whatever meta information is associated with that section. I believe you said you set breakpoints, and it was indeed loading it?

Did you get any further into seeing why it wasn't being included?

**Comment by khalwat** [comment] 2018-05-16 03:45
Turns out it actually wasn't working as intended in some circumstances.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/98fe949bae8ab89483b30bd9b7086a46b2502710

**Closed as completed by khalwat** 2018-05-16 03:45 UTC

**Comment by RosanaRufer** [comment] 2018-05-16 07:36
Thank you, it works now, you're awesome 👍 

![relieved](https://user-images.githubusercontent.com/4906291/40103018-06dfcfe6-58e4-11e8-902c-957c42d9fbc5.gif)
