### ISSUE TITLE
Schema.org entity field is missing options

### ISSUE THREAD

**Issue by chrismlusk** [nystudio107/craft-seomatic#1303] opened 2023-03-26 18:30 UTC
### Describe the bug
I noticed the entity type field is showing `(unknown)` with all of my previously fine selections. This is happening with entities as basic as "Local Business" or "Blog Posting."

And, when I clear the selection to reset the field and start again, I only see a "No options available" message.

### Versions
- Plugin version: 4.0.22
- Craft version: 4.4.5

**Comment by khalwat** [comment] 2023-03-26 19:06
Looks like there is an issue with the caching layer, investigating.

**Comment by khalwat** [comment] 2023-03-26 19:57
Interestingly, I can reproduce this on one of my dev machines, but not the other... strange.

**Comment by khalwat** [comment] 2023-03-26 23:23
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/6582531907098c6eb72d40cae2d69414d7960758 & https://github.com/nystudio107/craft-seomatic/commit/0cfdc3c402231f1e3ac0080f6b4a7413fc9d2c7e

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.52”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.23”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2023-03-26 23:23 UTC
Labels: bug

**Comment by khalwat** [comment] 2023-03-27 17:46
@chrismlusk can you confirm that this addresses the issue for you? I plan to cut a release so others don't run into it.

**Comment by chrismlusk** [comment] 2023-03-27 17:59
@khalwat yep, that update worked. Thanks!
