### ISSUE TITLE
JSON-LD data not automatically rendering

### ISSUE THREAD

**Issue by richardcalahan** [nystudio107/craft-seomatic#101] opened 2018-05-03 17:58 UTC
I may be misunderstanding the plugin setting "Automatic Render Enabled", but if enabled, should all JSON-LD data be rendering automatically? Mine seems incomplete. 

For example, under site settings, I've configured the following for location data under Identity:
<img width="1063" alt="screen shot 2018-05-03 at 10 55 24 am" src="https://user-images.githubusercontent.com/753757/39594087-87f41af2-4ec0-11e8-88aa-8335bce27268.png">

But on the frontend, I see:
<img width="444" alt="screen shot 2018-05-03 at 10 56 45 am" src="https://user-images.githubusercontent.com/753757/39594158-b6e93720-4ec0-11e8-9f19-42e7a061fee0.png">

I'm running:
Craft 3.0.5
SEOMatic 3.0.10

**Comment by khalwat** [comment] 2018-05-03 22:43
So it's automatically rendering the JSON-LD -- are you seeing any additional `ld+json` on the page? (you should)

**Comment by khalwat** [comment] 2018-05-04 00:37
I take it back; this is a regression.

**Comment by khalwat** [comment] 2018-05-04 00:59
So I think this might actually be due to something they changed in Craft 3.0.5: https://github.com/craftcms/cms/issues/2831

**Comment by khalwat** [comment] 2018-05-04 01:34
Fixed in https://github.com/nystudio107/craft-seomatic/commit/362efcc5bbed84310fcf1ef96fa89d02833b2415

**Closed as completed by khalwat** 2018-05-04 01:34 UTC
Labels: need info

**Comment by richardcalahan** [comment] 2018-05-04 13:00
Ah, sorry I missed your questions. I thought I'd get pinged by Github. Thanks for the fix, all good now.
