### ISSUE TITLE
Canonical URL vs siteUrl

### ISSUE THREAD

**Issue by svondervoort** [nystudio107/craft-seomatic#1547] opened 2024-12-13 15:34 UTC
### Question
An Online Marketing agency noticed something similar to other issues around here like #1507.
But in our case we would like the canonical of specific pages to include a trailing slash but not for other pages.

For example:
URL: https://www.bezorgdekrant.nl/en/ 
Site Base URL (according to Craft): http://bezorgdekrant-website.test/en/
Canonical Link: https://www.bezorgdekrant.nl/en

For any other sub-URL no trailing slash is required, only for the base URLs.

I tried:
- `addTrailingSlashesToUrls => true` option.
- Setting the Canonical URL in the SEO field on the Entry.
- Pragmatically overwriting the canonical using `{% do seomatic.meta.canonicalUrl(...) %}`

Does the plugin remove the trailing slash by default or is there a way to force it?

**Comment by khalwat** [comment] 2024-12-13 15:53
What is at `/en/`? Is it a Single or is an Entry, or is it just an `index.twig` template with no Craft element associated with it?

**Comment by svondervoort** [comment] 2024-12-13 15:55
Sorry. In this case it is a Single (HomePage section).

**Comment by khalwat** [comment] 2024-12-14 14:05
So I just tested this, and according to my test, SEOmatic _is_ respecting the `addTrailingSlashesToUrls` General config setting.

With `addTrailingSlashesToUrls` off (which is the default), I get:

```html
<link href="http://plugindev.local:8005/es" rel="canonical">
```

with `addTrailingSlashesToUrls` set to `true`, I get: 
```html
<link href="http://plugindev.local:8005/es/" rel="canonical">
```

So I'm going to guess that either somehow `addTrailingSlashesToUrls` isn't properly set, or maybe you're using an older version of SEOmatic? Are you updated to the latest version?

**Comment by svondervoort** [comment] 2024-12-16 10:51
Thanks for testing. I tried the `addTrailingSlashesToUrls` and it does work, maybe before it was SEOmatic cache that I didn't clear properly.

Now the only issue is that (for some reason) they only want the trailing slash for the homepage and not any sub-pages.
The reason being that in Google Search Console bezorgdekrant.nl/en/ will be seen as a folder instead of a file/page.

Setting `addTrailingSlashesToUrls` will force all links to also include a `/` which is not preferred. 
Is there a way to only set the trailing slash to the metadata for a specific page?

**Comment by khalwat** [comment] 2024-12-17 02:33
Yeah honestly that recommendation doesn't make sense in, but let me see if I can work something up for you.

**Comment by khalwat** [comment] 2024-12-17 17:08
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.5.9”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.1.8”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.1.8”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2024-12-17 17:08 UTC
Labels: question

**Comment by svondervoort** [comment] 2024-12-18 07:09
Great, I'll give it a go this friday. I got some time planned for this issue.

**Comment by svondervoort** [comment] 2024-12-20 12:04
I just did some testing and it works like a charm! Thanks!
When is a new release of SEOmatic planned with this change?

**Comment by khalwat** [comment] 2024-12-21 19:34
Should be out next week.

**Comment by rw-ninety** [comment] 2025-01-08 11:40
@khalwat This broke our integration, please check-out my bug-report: #1559 1559

**Comment by Stan-S-99** [comment] 2025-07-01 14:17
Hi,

Could it be that the issue has resurfaced? It seems the canonical URL is once again missing the trailing slash.

**Comment by khalwat** [comment] 2025-07-01 14:21
@Stan-S-99 not that I'm aware of -- please post a detailed report with your settings so I can attempt to reproduce the issue locally.

**Comment by Stan-S-99** [comment] 2025-07-03 10:01
Hi @khalwat ,

Thank you for your message.
It is on the same pages as mentioned by @svondervoort  

URL: https://www.bezorgdekrant.nl/en/
Site Base URL (according to Craft): http://bezorgdekrant-website.test/en/
Canonical Link: https://www.bezorgdekrant.nl/en

We haven’t made any changes in the meantime, but suddenly our partner discovered that the canonical link no longer matched what was shown in Search Console.

**Comment by khalwat** [comment] 2025-07-04 18:11
...and what is the setting of in Craft for `addTrailingSlashesToUrls ` ref: https://craftcms.com/docs/5.x/reference/config/general.html#addtrailingslashestourls

**Comment by Stan-S-99** [comment] 2025-07-07 10:04
Hi @khalwat , 

The issue is that the / should only be on the homepage not on all pages. So addTrailingSlashesToUrls forces this to be enabled on all pages. (This is something the customer wants). As I can see in this issue, something was done to make it page specific but for some reason it looks like this is not working anymore. I have tried overriding the canonical URL but with no succes.         
` if (!$generalConfig->addTrailingSlashesToUrls && (!$preserveTrailingSlash || self::urlIsSiteIndex($url))) `

urllsSiteIndex is true so the / gets trimmed. I think this is why it is not working anymore because in the previous commits this was not there yet. It seems this is done because of something craft implemented, maybe this is more a craft Issue? Is there anything you can do to solve this?

**Comment by khalwat** [comment] 2025-07-11 01:11
This is probably related: https://github.com/craftcms/cms/issues/5675

While I do think this is entirely a non-issue in terms of it affecting SEO, I'll endeavor to fix it for you!

**Comment by khalwat** [comment] 2025-07-11 08:43
Okay so this is being done _intentionally_ due to: https://github.com/nystudio107/craft-seomatic/issues/717
