### ISSUE TITLE
JSON-LD not getting HTML content added unless escaped

### ISSUE THREAD

**Issue by robmcfadden** [nystudio107/craft-seomatic#441] opened 2019-07-12 19:35 UTC
Since the `jsonLD` object is being JSON encoded, seems like I shouldn't have to escape the contents of this Redactor field that I'm adding to the articleBody field of the Article schema type. It doesn't get added to the object unless I do.

Not sure if this is really a bug, but just something I noticed. Thanks for taking a look!

```
{% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}

{% for row in entry.contentMatrix.type('richText').limit(1).all() %}
  {% do mainEntity.articleBody(row.richText|e('html_attr')) %}
{% endfor %}

**Comment by khalwat** [comment] 2019-07-13 03:15
I did a test where I pulled from a Rich Text field:

```twig
    {% set mainEntity = seomatic.jsonLd.get('mainEntityOfPage') %}
    {% do mainEntity.articleBody(entry.someRichText) %}
```

...and it worked as expected. Could there be some additional complication here?

**Comment by khalwat** [comment] 2019-07-13 03:16
BTW if you do this in a loop:

```twig
{% for row in entry.contentMatrix.type('richText').limit(1).all() %}
  {% do mainEntity.articleBody(row.richText|e('html_attr')) %}
{% endfor %}
```
...then only the last block of rich text will be in there.

**Comment by khalwat** [comment] 2019-07-13 20:25
So I was wrong in my original assessment; it's actually a pretty interesting problem.

So the issue isn't actually encoding; SEOmatic does indeed encode everything that's in the JSON-LD blob.

If you do `entry.someRichText` what is actually returned is an object, specifically a `craft\redactor\FieldData` object. Technically, you should be doing either  `entry.someRichText.getRawContent()` or  `entry.someRichText.getParsedContent()` depending on what you want

 The reason it works when you do `|e('html_attr')` is because this forces the `craft\redactor\FieldData` object to be converted to a string. If you don't do this, the object gets assigned to the `articleBody` property.

The problem is that to render the JSON-LD array, we recursively convert an object to an array of values; but the FieldData object can't be converted to an array, so it ends up evaluating to an empty string, which then gets filtered out.

But I agree that the _expectation_ is that this would work... so now at assignment time, it will check if it's an object that's an instance of `Twig\Markup` and if so, convert it to a string

Addressed in https://github.com/nystudio107/craft-seomatic/commit/0f19964526a0af8449d262e44774293dc45fdf8b

**Closed as completed by khalwat** 2019-07-13 20:25 UTC
Labels: need info

**Comment by robmcfadden** [comment] 2019-07-14 02:24
Thanks for taking a look!
