### ISSUE TITLE
'Social' title source 'Same as SEO Title' but not the same

### ISSUE THREAD

**Issue by stenvdb** [nystudio107/craft-seomatic#123] opened 2018-05-25 09:09 UTC
Maybe there is something overriding this but I can't figure it out, it looks like a small bug?
In content SEO, the preview of a certain channel clearly sets the SEO title as '_site name_ | _entry title_'. But in the Facebook or Twitter settings in content SEO, the title is set to 'Same as SEO Title', however this only displays '_entry title_' (so without my site name). 

It also definitely is not getting overridden by the SEO Settings field attached to the entry itself. Is there something I have missed? Shouldn't the site name be there as well in the Facebook OG Title?

**Comment by khalwat** [comment] 2018-05-30 16:36
I will have a look at it; I think it may just be a matter of the defaults not being set correctly.

You can test this theory by going to one of the Content SEO sections and setting it the way you want it, and then clicking on Save.

**Comment by khalwat** [comment] 2018-05-31 16:12
I tested this, and am unable to reproduce it. What do you have the **Facebook OpenGraph Site Name Position Source** setting set to? By default, it uses "none" but if you change it to **Same as Site Name Position** it should do what you want.

**Comment by ockam** [comment] 2018-06-11 15:41
I’m experiencing the same issue (preview is good but not code). 
I have tried changing global config without success.

Could this be related to multi-site setup? I run a 2 sites setup (french / english).

**Comment by ockam** [comment] 2018-06-11 18:00
Done some test in Seomatic code and can confirm that when the code goes through `OgTitleTag.php`, `siteNamePosition = 'none'`, even though General Site Name Position is set to "After" and Facebook Site Name Position is set to "Same as Site Name Position".

Manually setting Facebook Site Name Position on the entry do work. So it looks like the global settings are not applied in this case.

I would like the dig deeper in the code but I’m a bit lost. If you want me test something specific, I’ll be glad to help.

**Comment by khalwat** [comment] 2018-06-12 20:21
Due to an error on my part, the default values for Content SEO are not set for the title position. If you go to the section in Content SEO, and just click on Save it'll properly save it.

Fixed in https://github.com/nystudio107/craft-seomatic/commit/62737f3229cff90387e42650b2c96cddf71f1393

**Closed as completed by khalwat** 2018-06-12 20:21 UTC
Labels: need info
