### ISSUE TITLE
500 - Undefined index: category

### ISSUE THREAD

**Issue by lenvanessen** [nystudio107/craft-seomatic#974] opened 2021-09-09 07:53 UTC
### Describe the bug
Since Craft 3.7.12 this bug was introduced when editing any category page in the CMS.

2021-09-09 09:48:00 [-][14078][15qeb1quo6eehjaplf1addqpj0][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: category in /Users/lenvanessen/Projects/leenders-shop/vendor/nystudio107/craft-seomatic/src/seoelements/SeoCategory.php:164
Stack trace:
#0 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/lenvanes...', 164)
#1 /Users/lenvanessen/Projects/leenders-shop/vendor/nystudio107/craft-seomatic/src/seoelements/SeoCategory.php(164): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/lenvanes...', 164, Array)
#2 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/View.php(1659): nystudio107\seomatic\seoelements\SeoCategory::nystudio107\seomatic\seoelements\{closure}('<span class="st...', false)
#3 /Users/lenvanessen/Projects/leenders-shop/storage/runtime/compiled_templates/5f/5f4d68e13d6c18535e96742e1784974a5e22f319e01155f6eff3a5e0b583c3d5.php(156): craft\web\View->invokeHook('cp.categories.e...', '<span class="st...')
#4 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(182): __TwigTemplate_ef03edbcec0e086b05550b9cd1e5abf3c82bdf1733f7f1471fc8ecf4f799b355->block_details('<span class="st...', Array)
#5 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(254): Twig\Template->displayBlock('details', Array, Array, true)
#6 /Users/lenvanessen/Projects/leenders-shop/storage/runtime/compiled_templates/52/526de0e1f9c40c9de6c260f5dc853907dcfaae0eae14bd89fc70a6e973215a74.php(101): Twig\Template->renderBlock('details', Array, Array)
#7 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3bee16274281c6257049cbb65bc8e6c5dca6754067b96c99b13a9cea4bfc9a40->doDisplay(Array, Array)
#8 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /Users/lenvanessen/Projects/leenders-shop/storage/runtime/compiled_templates/68/68829eb42291aa99509b784b2c856e3379f88571d3c58232ce11f24262d90c5b.php(342): Twig\Template->display(Array, Array)
#10 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_479cd34f6d6f9f539659c3fee5c2890edd3784bb7c0cb29be1f187a6198c3723->doDisplay('[<span class="s...', Array)
#11 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /Users/lenvanessen/Projects/leenders-shop/storage/runtime/compiled_templates/5f/5f4d68e13d6c18535e96742e1784974a5e22f319e01155f6eff3a5e0b583c3d5.php(77): Twig\Template->display(Array, Array)
#13 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ef03edbcec0e086b05550b9cd1e5abf3c82bdf1733f7f1471fc8ecf4f799b355->doDisplay('[<span class="s...', Array)
#14 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#16 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#17 /Users/lenvanessen/Projects/leenders-shop/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#18 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('categories/_edi...', Array)
#19 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('categories/_edi...', '[<span class="s...')
#20 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('categories/_edi...', '[<span class="s...', '<span class="st...')
#21 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/controllers/CategoriesController.php(401): craft\web\Controller->renderTemplate('categories/_edi...', Array)
#22 [internal function]: craft\controllers\CategoriesController->actionEditCategory('dstCategories', 20557, Object(craft\elements\Category), NULL)
#23 /Users/lenvanessen/Projects/leenders-shop/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /Users/lenvanessen/Projects/leenders-shop/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#25 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-category', Array)
#26 /Users/lenvanessen/Projects/leenders-shop/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-category', Array)
#27 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction('categories/edit...', Array)
#28 /Users/lenvanessen/Projects/leenders-shop/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('categories/edit...', Array)
#29 /Users/lenvanessen/Projects/leenders-shop/vendor/craftcms/cms/src/web/Application.php(261): yii\web\Application->handleRequest(Object(craft\web\Request))
#30 /Users/lenvanessen/Projects/leenders-shop/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#31 /Users/lenvanessen/Projects/leenders-shop/web/index.php(24): yii\base\Application->run()
#32 /Users/lenvanessen/.composer/vendor/laravel/valet/server.php(235): require('/Users/lenvanes...')
#33 {main}

### Versions
- Plugin version:3.7.12
- Craft version: 3.4.2

**Comment by joelstrom** [comment] 2021-09-09 11:01
We just stumbled upon this issue too, same Craft version 3.7.12 but newer SEOmatic version 3.4.7
Edit: this seems to be a duplicate of https://github.com/nystudio107/craft-seomatic/issues/973, will try the proposed solution!

**Comment by brandonkelly** [comment] 2021-09-09 12:51
Just fixed this on Craft’s end: https://github.com/craftcms/cms/issues/9811#issuecomment-916061730

**Comment by brandonkelly** [comment] 2021-09-09 12:51
Just fixed this on Craft’s end: https://github.com/craftcms/cms/issues/9811#issuecomment-916061730

**Comment by khalwat** [comment] 2021-09-09 16:11
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/d693f1988a75222313ee62e98d995f2c51cb51fc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.8”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2021-09-09 16:11 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2021-09-14 22:09
Craft 3.7.13 is out now with the Craft fix.
