### ISSUE TITLE
Overwritting rel=alternate in templates reverts back to default after some time

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#189] opened 2018-08-02 17:01 UTC
So this is a weird issue :/

We are using Craft Pro v3.0.18 with craft-seomatic v3.1.6.

In our templates we do this:

```twig
{% hook 'seo' %}
{% do seomatic.tag.get('referrer').include(false) %}
{% do seomatic.link.get('alternate').hreflang('en-US') %}
```

This works fine for like ~ a day. After that, the link alternate reverts back to `x-default`. If I clear Craft's caches, then it goes back to `en-US`.

I notice this issue on our production app but not in our staging app.

We override seomatic's config like this (not sure if it's 100% right)

```php
return [
    // The server environment, either `live`, `staging`, or `local`
    'environment' => getenv('ENVIRONMENT') === 'production' ? 'live' : getenv('ENVIRONMENT')
];
```

I know the info might not be sufficient but I'm not sure what else info I can provide (at least publicly).

**Comment by khalwat** [comment] 2018-08-02 20:04
errr... there's no `{% hook 'seo' %}` in SEOmatic -- I think you may be thinking about Ether's SEO plugin?

Make sure you don't have both installed...

**Comment by XhmikosR** [comment] 2018-08-02 20:41
I definitely don't have that installed but I'll double check the template
initialization and remove it. But the issue indeed happens.

**Comment by khalwat** [comment] 2018-08-02 23:09
Well, you state that you do this in your templates:

```
{% hook 'seo' %}
{% do seomatic.tag.get('referrer').include(false) %}
{% do seomatic.link.get('alternate').hreflang('en-US') %}

```

Unless that's just a copy/paste error, either the SEO plugin is installed, or that template should be throwing an error.

As for your issue, make sure that the SEOmatic commands are not inside of a `{% cache %}` tag?

**Comment by XhmikosR** [comment] 2018-08-03 11:07
Errors are not thrown in all environments as you already know. But anyway I removed that leftover.

Regarding `cache` tags, no I don't have that either.

Let me observe this a little more and come back to you next week.

**Comment by XhmikosR** [comment] 2018-08-03 11:08
Regarding `cache` tags, no I don't have that either.

Let me observe this a little more and come back to you next week.

**Comment by khalwat** [comment] 2018-08-03 16:15
Very strange. Do let me know what you find out. Because it's something that works, but then seems to "not work" over time, my guess is there's some kind of a caching issue involved here.

**Comment by XhmikosR** [comment] 2018-08-05 13:05
Ok, so this started happening on my staging environment too with 3.1.9.

I have already removed the seo leftover and just do

```twig
{% do seomatic.tag.get('referrer').include(false) %}
{% do seomatic.link.get('alternate').hreflang("#{craft.app.language}") %}
```

I think the issue might be with the order I'm using in the `head`. Like where I'm calling `{{ head() }}`.

**Comment by XhmikosR** [comment] 2018-08-05 13:12
In fact, with v3.1.9 it's always `x-default`, while with 3.1.8 it worked on my staging and dev environments properly, but reverted back to `x-default` after some time on production.

So, I think whatever you changed after v3.1.8 definitely triggers my issue :)

**Comment by XhmikosR** [comment] 2018-08-05 13:17
So, I think whatever you changed after v3.1.8 definitely triggers my issue :)

**Comment by khalwat** [comment] 2018-08-05 20:33
Is there a reason why you're explicitly calling `{{ head() }}`?

**Comment by khalwat** [comment] 2018-08-05 20:36
I just tested the code you're using here, and I'm seeing it work as expected when I add in:

```
{% do seomatic.tag.get('referrer').include(false) %}
```

I'd get away from explicitly calling `{{ head() }}` unless this is something you absolutely need to be doing.

**Comment by XhmikosR** [comment] 2018-08-06 02:46
Thanks for the suggestion.

I'm gonna try without explicitly calling `head` and see how it goes for a couple of days. I'll let you know.

**Comment by XhmikosR** [comment] 2018-08-06 03:05
Ah, I remember why I resorted to calling `head`. I wanted some of the stuff I output in `head` to be at the end of it, because the seomatic stuff are currently output there. Is there any way I can overwrite it?

**Comment by khalwat** [comment] 2018-08-06 15:12
You can use `{% js at POS_HEAD %}` to add things to the head, but it probably won't be at the exact end. Does it matter?

**Comment by XhmikosR** [comment] 2018-08-06 15:19
Not to me a lot, but marketing... :P

Currently, I worked around it by not using `view.registerCssFile`/`registerJsFile` so that the CSS files are to the top and GTM to the end.

But, if I had an option to load the GTM script even on staging (maybe a dropdown to override the default setting), I could get rid of my custom GTM script. And, yeah, we need GTM in staging too because we load a bunch of other stuff via GTM like cookiebot etc.

PS. I'm gonna deploy today/tomorrow tops, so I should have news in 1-2 days if the `x-default` issue still persists with 3.1.11.

**Comment by khalwat** [comment] 2018-08-06 15:20
I don't understand why marketing cares where in the `<head>` something goes?

**Comment by khalwat** [comment] 2018-08-06 15:22
You do have the option to load GTM even on the staging site. In Twig, just do something like this:

```
{% do seomatic.script.get('googleTagManager').include(true) %}
```

This will force it to include the script regardless of the environment. You can also adjust the dataLayer:

```
{% do seomatic.script.get('googleTagManager').dataLayer({
    'woof': 'bark'
}) %}
```

So you can pass in different things depending on the environment. Documented here: https://github.com/nystudio107/craft-seomatic#google-tag-manager

**Comment by khalwat** [comment] 2018-08-08 01:48
I'm going to assume the above answers this issue.

**Comment by XhmikosR** [comment] 2018-08-08 05:51
Please don't hurry. I'm still waiting to see if the issue happens.

**Comment by khalwat** [comment] 2018-08-08 05:52
Did you see my comment above about how you can have GTM working on staging? And then should be able to avoid having to use `{{ head() }}`?

**Comment by XhmikosR** [comment] 2018-08-08 05:53
Yes, I did, and I have already made a few changes. But it still seemed to happen even without `head()`, so I need to verify.

**Comment by XhmikosR** [comment] 2018-08-09 08:04
@khalwat: this definitely happens in my case. I have to log into the production app and clear Craft's caches.

**Comment by khalwat** [comment] 2018-08-09 08:06
Clearing which cache specifically changes the result?

Next time you see it happen, clear them one at a time until it "fixes" itself, it'll be helpful in tracking down what is doing on.

**Comment by XhmikosR** [comment] 2018-08-09 08:18
I will, but we definitely need this fixed ASAP, because it affects our SEO (and I got marketing all over me :P)

**Comment by khalwat** [comment] 2018-08-09 08:20
I'm not convinced it's an outright bug; it's more likely to be something specific to your setup and/or templates.

I use code very much like this on a number of live sites, without the issues you've mentioned here.

**Comment by XhmikosR** [comment] 2018-08-09 08:22
Yeah, but regardless, it happens with SEOmatic ;)

**Comment by XhmikosR** [comment] 2018-08-09 17:25
@khalwat: please reopen this since it's an ongoing issue. The fact that you can't reproduce (yet) doesn't mean it's not an issue.

I had the chance to pinpoint this to the `SEOmatic frontend template caches` clear cache option. After that, it respects my changes.

My current SEOmatic related template changes are these:

```twig
{% do seomatic.link.get('alternate').hreflang("#{craft.app.language}") %}
{% do seomatic.script.get('googleTagManager').include(true) %}
{% do seomatic.tag.get('referrer').include(false) %}
```

**Comment by XhmikosR** [comment] 2018-08-09 17:27
Oh, also, my current version is SEOmatic 3.1.13.1 and Craft 3.0.19

**Comment by khalwat** [comment] 2018-08-10 02:00
Right, so then the question is... why would it work (the cache being correct) and then suddenly stop working?

**Comment by XhmikosR** [comment] 2018-08-10 06:18
@khalwat: that is something I can't figure out. I know it works after I clear the cache, and then breaks like ~24 hours after that without us making any changes to the production site. The staging app does not have this issue ever. I've also made sure there are no template errors on my side, which when I opened this issue, that wasn't the case.

I'm not sure what more info I can give you. My SEOmatic template changes are above.

**Comment by khalwat** [comment] 2018-08-10 13:43
So if the staging server never has this issue, I'd start to look for differences in Craft & server config between the staging and production servers.

**Comment by XhmikosR** [comment] 2018-08-10 13:45
Already did and there is none, apart from the environment variable set to production for the production.

**Comment by khalwat** [comment] 2018-08-11 20:44
Have you changed things so that you're no longer calling `{{ head() }}` and instead included GTM as per the above code?

If this is working fine on the staging server, there has to be _some_ difference with the production server that's bring it out.

**Comment by khalwat** [comment] 2018-08-12 02:20
Added a config option so you can just disable it there: https://github.com/nystudio107/craft-seomatic/commit/f75350cc8f00b0c5d76dce342bcfe8afad9fa8d5

**Comment by XhmikosR** [comment] 2018-08-12 14:56
Thanks, but this is not the solution to my issue. Because the problem is that `rel alternate` along with other frontend entries are reverted to random value. It's like every ~24 hours SEOmatic believes we are not in production or something, because it drops any custom template overrides, including rel alternate, meta robots is set to none even though the env is `production`.

**Comment by khalwat** [comment] 2018-08-12 16:56
If you believe the issue is environmental, it should be pretty easy to test. Create some kind of a tag in SEOmatic (it can be whatever you want), something like:

```
{% do seomatic.tag.create({
    'content': seomatic.config.environment,
    'name': 'seomaticEnvironment',
}) %}

{% do seomatic.tag.create({
    'content': getenv('ENVIRONMENT'),
    'name': 'craftEnvironment',
}) %}
```

And then you will actually have meta tags (which will be ignored by browsers/bots) that will tell you explicitly what environment is running.

Although I'm open to the idea that this is an SEOmatic bug, from everything that you've stated—and from using SEOmatic extensively in the field—I'm leaning towards some kind of environmental/server setup issue.

So questions that need answering are:

1. Are the staging and production servers running on the same shared VPS/instance?

2. What caching method is being used for Yii2 on this server?

3. I'd also consider a slightly more straightforward `seomatic.php`, such as:

```
return [

    // All environments
    '*' => [
        // The public-facing name of the plugin
        'pluginName' => 'SEOmatic',

        // Should SEOmatic render metadata?
        'renderEnabled' => true,

        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live',

        // Should SEOmatic display the SEO Preview sidebar?
        'displayPreviewSidebar' => true,

        // Should SEOmatic display the SEO Analysis sidebar?
        'displayAnalysisSidebar' => true,

        // If `devMode` is on, prefix the <title> with this string
        'devModeTitlePrefix' => '🚧 ',

        // The separator character to use for the `<title>` tag
        'separatorChar' => '|',

        // The max number of characters in the `<title>` tag
        'maxTitleLength' => 70,

        // The max number of characters in the `<meta name="description">` tag
        'maxDescriptionLength' => 320,
    ],

    // Live (production) environment
    'production'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live',
    ],

    // Staging (pre-production) environment
    'staging'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'staging',
    ],

    // Local (development) environment
    'local'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'local',
    ],
];
```

...as shown in the documention: https://github.com/nystudio107/craft-seomatic#plugin-settings

**Comment by XhmikosR** [comment] 2018-08-13 13:34
Thanks for the reply, @khalwat. Please keep the issue open for a few days until I try your suggestions and have more info.

EDIT:

This doesn't seem to work @khalwat 

```twig
    {% do seomatic.tag.create({
        "content" => seomatic.config.environment,
        "name" => "seomaticEnvironment"
    }) %}

    {% do seomatic.tag.create({
        "content" => getenv("ENVIRONMENT"),
        "name" => "craftEnvironment"
    }) %}
```

A hash key must be followed by a colon (:). Unexpected token "operator" of value "=" ("punctuation" expected with value ":").

EDIT2:

Nvm, I changed `=>` to `:`.

**Comment by XhmikosR** [comment] 2018-08-13 13:40
This doesn't seem to work @khalwat 

```twig
    {% do seomatic.tag.create({
        "content" => seomatic.config.environment,
        "name" => "seomaticEnvironment"
    }) %}

    {% do seomatic.tag.create({
        "content" => getenv("ENVIRONMENT"),
        "name" => "craftEnvironment"
    }) %}
```

A hash key must be followed by a colon (:). Unexpected token "operator" of value "=" ("punctuation" expected with value ":").

**Comment by XhmikosR** [comment] 2018-08-13 13:50
About my server setup.

It's 2 fortrabbit apps, with the only difference in the `ENVIRONMENT` variable I set. Everything else is the same.

**Comment by XhmikosR** [comment] 2018-08-13 16:41
@khalwat: so I just pushed this on my production app, using this config for SEOmatic + the meta tags

```php
return [
    // Live (production) environment
    'production'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live'
    ],

    // Staging (pre-production) environment
    'staging'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'staging'
    ],

    // Local (development) environment
    'dev'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'local'
    ]
];
```

```html
<meta name="seomaticEnvironment" content="staging">
<meta name="craftEnvironment" content="production">
```

**Comment by XhmikosR** [comment] 2018-08-13 16:41
On my staging app, both vars are `staging` so something seems wrong somewhere. Any ideas?

**Comment by khalwat** [comment] 2018-08-13 16:45
Please also put a default in there as per my example:

```
    '*' => [
        // The public-facing name of the plugin
        'pluginName' => 'SEOmatic',

        // Should SEOmatic render metadata?
        'renderEnabled' => true,

        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live',

        // Should SEOmatic display the SEO Preview sidebar?
        'displayPreviewSidebar' => true,

        // Should SEOmatic display the SEO Analysis sidebar?
        'displayAnalysisSidebar' => true,

        // If `devMode` is on, prefix the <title> with this string
        'devModeTitlePrefix' => '🚧 ',

        // The separator character to use for the `<title>` tag
        'separatorChar' => '|',

        // The max number of characters in the `<title>` tag
        'maxTitleLength' => 70,

        // The max number of characters in the `<meta name="description">` tag
        'maxDescriptionLength' => 320,
    ],
```

We want to provide sane defaults in case for whatever reason it doesn't match any environment.

**Comment by XhmikosR** [comment] 2018-08-13 16:53
Well, with those in place it's correct

```
<meta name="seomaticEnvironment" content="live">
<meta name="craftEnvironment" content="production">
```

**Comment by XhmikosR** [comment] 2018-08-13 17:10
But it's random, and I don't think it has to do with the all environment settings being there.

I tried commenting out one by one the all env settings, but I can't conclude which one triggers this. It does get triggered randomly after I clear Craft's cache (all) regardless of the setting I comment out.

**Comment by khalwat** [comment] 2018-08-13 17:20
Well now that's interesting. What that means is you're having requests come in without the `ENVIRONMENT` set properly for some reason. 

This likely means that for other things, this is set improperly as well. How are you setting `ENVIRONMENT`?

**Comment by XhmikosR** [comment] 2018-08-13 17:21
Via fortrabbit's environment variables. This is the same as the staging app.

**Comment by khalwat** [comment] 2018-08-13 17:26
Here's the relevant code from `vendor/craftcms/cms/src/bootstrap/bootstrap.php`:

```
// Set the environment
$environment = $findConfig('CRAFT_ENVIRONMENT', 'env') ?: ($_SERVER['SERVER_NAME'] ?? null);
```

...and then here is what (should) be in your `web/index.php`:

```
// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
```

So what I think is happening is that for whatever reason, on some requests, `ENVIRONMENT` is not set or is not set to what you're expecting it to be, so `CRAFT_ENVIRONMENT` then defaults to `production` which is what is causing this to "just work" now that you've added a wildcard.

**Comment by khalwat** [comment] 2018-08-13 18:30
FYI, this is where Craft merges in the plugin's settings with the contents of the config file: 

https://github.com/craftcms/cms/blob/develop/src/services/Plugins.php#L776

...which ends up calling this:

https://github.com/craftcms/cms/blob/develop/src/services/Config.php#L203

**Comment by XhmikosR** [comment] 2018-08-13 18:50
Thanks for the replies,I really appreciate it. Now i will double check web
index file tomorrow but iirc its correct.

The craft meta though always sticks to production. Do you have any idea how
we can debug this further?

**Comment by khalwat** [comment] 2018-08-13 18:52
SEOmatic isn't doing anything special here; it's just leveraging the built-in multi-environment config file support.

You might want to ask support at FortRabbit as well, maybe @o_stark will have some insight.

**Comment by XhmikosR** [comment] 2018-08-14 07:24
My web/index.php is fine too.

The environment meta tag is always fine; the SEOmatic meta tag reverts back randomly. I will ask fortrabbit support too, but this is a pretty difficult issue to debug for sure.

**Comment by XhmikosR** [comment] 2018-08-14 09:11
After looking at the source code, I still think this is a bug in SEOmatic somewhere around here https://github.com/nystudio107/craft-seomatic/blob/9a0af099e84271b94424c17f87f17b3987b3018a/src/helpers/Config.php#L58-L74

**Comment by XhmikosR** [comment] 2018-08-14 12:46
After discussing a lot with @ostark, here is what I know for sure: unless I explicitly set the `'*'` environment options, SEOmatic wrongfully sets its environment to staging.

So this triggers the bug for sure:

```php
return [
    // Live (production) environment
    'production'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live'
    ],

    // Staging (pre-production) environment
    'staging'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'staging'
    ],

    // Local (development) environment
    'dev'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'local'
    ]
];
```

![2production](https://user-images.githubusercontent.com/349621/44092319-cb582eb4-9fd8-11e8-961c-6786bc3257a9.jpg)

If I use your suggestion and include the all environment settings, then the issue seems gone. Seems, because I need to confirm after 24 hours. So this seems to work:

```php
return [

    // All environments
    '*' => [
        // The public-facing name of the plugin
        'pluginName' => 'SEOmatic',

        // Should SEOmatic render metadata?
        'renderEnabled' => true,

        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live',

        // Should SEOmatic display the SEO Preview sidebar?
        'displayPreviewSidebar' => true,

        // Should SEOmatic display the SEO Analysis sidebar?
        'displayAnalysisSidebar' => true,

        // If `devMode` is on, prefix the <title> with this string
        'devModeTitlePrefix' => '&#x1f6a7; ',

        // The separator character to use for the `<title>` tag
        'separatorChar' => '|',

        // The max number of characters in the `<title>` tag
        'maxTitleLength' => 70,

        // The max number of characters in the `<meta name="description">` tag
        'maxDescriptionLength' => 320
    ],

    // Live (production) environment
    'production'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'live'
    ],

    // Staging (pre-production) environment
    'staging'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'staging'
    ],

    // Local (development) environment
    'dev'  => [
        // The server environment, either `live`, `staging`, or `local`
        'environment' => 'local'
    ]
];
```

![1staging](https://user-images.githubusercontent.com/349621/44092298-b89033f8-9fd8-11e8-9198-cfa9825112d9.jpg)


So, this does still seem like a bug to my eyes.

**Comment by khalwat** [comment] 2018-08-14 18:54
So @XhmikosR I discussed this with @o_stark as well -- that code that you site actually isn't coming into play here. That is for reading in the multi-environment `seomatic-config` which is used when constructing the meta containers: https://github.com/nystudio107/craft-seomatic#meta-bundle--container-settings

It doesn't come into play when reading in the `config/seomatic.php` -- that's something that Craft does as part of `services/Plugins.php`

**Comment by XhmikosR** [comment] 2018-08-14 18:57
Could be yeah. I was still in the middle of trying to pinpoint the root cause when I made that comment.

**Comment by khalwat** [comment] 2018-08-14 18:58
The code you referenced above is only hit when _new_ metabundles are being created (it uses those `seomatic-config` files as a template).

The actual code you're hitting is here, I think: https://github.com/craftcms/cms/blob/develop/src/services/Config.php#L220

...because that's what `services/Plugins.php` calls to read in any multi-environment configs (including the `config/seomatic.php` file)

**Comment by khalwat** [comment] 2018-08-14 19:00
What you could do is apply a hot fix to the deployed server to do something like this in `services/Config.php`:

```
        // If no environment was specified, just look in the '*' array
        if ($this->env === null) {
            Craft::error('env is null'.print_r($this, true), '__METHOD__');
            return $config['*'];
        }
```

So that it will log some error information for you if as we're suspecting, that codepath gets hit.

**Comment by khalwat** [comment] 2018-08-14 19:01
^ make sure you clear any caches, and restart `php-fpm` to clear the `opcache` if you do the above. Otherwise the code will never be run.

**Comment by XhmikosR** [comment] 2018-08-14 19:04
Not sure if I can clear opcache, it should be taken care of on fortrabbit. I will try the above code rn.

**Comment by khalwat** [comment] 2018-08-14 19:06
You can put in a sanity check log outside of the conditional, if you want to make sure your code is actually running. Like:

```
Craft::warning('Debug code is in place', '__METHOD__');
// If no environment was specified, just look in the '*' array
if ($this->env === null) {
        Craft::error('env is null'.print_r($this, true), '__METHOD__');
        return $config['*'];
}
```

**Comment by XhmikosR** [comment] 2018-08-14 19:09
So, wait, you mean this should be in craft code?

**Comment by khalwat** [comment] 2018-08-14 19:13
Yes, because I believe that's where it's happening.

**Comment by XhmikosR** [comment] 2018-08-14 19:15
Doesn't seem to work for me, results in blank page.

**Comment by XhmikosR** [comment] 2018-08-14 19:21
The first snippet works, but I don't see anything in any log. In which log file should I look?

**Comment by khalwat** [comment] 2018-08-14 19:23
It will be in `web.log` but only when that condition is met. Which is why I suggested sanity checking logging code to ensure that it's actually running.

**Comment by XhmikosR** [comment] 2018-08-14 19:24
I don't have any craft.log in storage/logs.

**Comment by khalwat** [comment] 2018-08-14 19:24
Sorry, I meant `web.log`

**Comment by XhmikosR** [comment] 2018-08-14 19:27
Unfortunately your second snippet results in the usual blank page of horror :P

**Comment by khalwat** [comment] 2018-08-14 19:31
I tested it here locally; it passes syntax checks in PhpStorm:

![phpstormscreensnapz082](https://user-images.githubusercontent.com/7570798/44113711-efc68dec-9fd6-11e8-8985-035398202412.png)

...and I'm using it here in my local dev environment without issue:

```
        Craft::warning('Debug code is in place', '__METHOD__');
        // If no environment was specified, just look in the '*' array
        if ($this->env === null) {
            Craft::error('env is null'.print_r($this, true), '__METHOD__');
            return $config['*'];
        }
```

You should check your `web.log` for errors if it's not working for some reason; looks pretty straightforward to me, though. It just adds logging.

**Comment by XhmikosR** [comment] 2018-08-14 19:32
idk, maybe because this is a prod environment.

**Comment by khalwat** [comment] 2018-08-14 19:33
Unlikely. Probably there is some kind of error integrating it into the PHP file.

**Comment by XhmikosR** [comment] 2018-08-14 19:34
No idea, but the second snippet works fine, but I don't see anything in web.log. Also since this is using composer maybe all this is useless if the dump isn't regenerated?

**Comment by XhmikosR** [comment] 2018-08-14 19:35
Let's try to be a little clearer. In which file and line exactly you want me to add this?

**Comment by khalwat** [comment] 2018-08-14 19:36
No, nothing new has been added that involves Composer at all.

The file and line is the one I linked to earlier: https://github.com/craftcms/cms/blob/develop/src/services/Config.php#L220

**Comment by XhmikosR** [comment] 2018-08-14 19:37
Well that throws for me even locally.

```

Fatal error: Uncaught Error: Class 'Craft' not found in C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\src\services\Config.php:220 Stack trace: #0 C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\bootstrap\bootstrap.php(169): craft\services\Config->getConfigFromFile('general') #1 C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\bootstrap\web.php(42): require('C:\\Users\\xmr\\De...') #2 C:\Users\xmr\Desktop\stackpath\web\index.php(20): require('C:\\Users\\xmr\\De...') #3 {main} thrown in C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\src\services\Config.php on line 220
```

Hence the blank page of death.

**Comment by XhmikosR** [comment] 2018-08-14 19:37
Hence the blank page of death.

**Comment by khalwat** [comment] 2018-08-14 19:38
Perhaps you're using an old version of Craft? Anyway, just put this at the top of the `services/Config.php` file:

```
use Craft;
```

Right with the other `use` statements, and it'll work.

**Comment by khalwat** [comment] 2018-08-14 19:40
That line is definitely there in recent versions of Craft CMS 3 -> https://github.com/craftcms/cms/blob/develop/src/services/Config.php#L10

**Comment by khalwat** [comment] 2018-08-14 19:40
...but hey, at least we know the code is executing! 👍

**Comment by XhmikosR** [comment] 2018-08-14 19:40
It's the same version I use in all environments. 3.0.19.

`use Craft;` is already at the top.

**Comment by XhmikosR** [comment] 2018-08-14 19:41
`use Craft;` is already at the top.

**Comment by khalwat** [comment] 2018-08-14 19:42
...but your error is saying it is not:

```
Fatal error: Uncaught Error: Class 'Craft' not found in C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\src\services\Config.php:220 Stack trace: #0 C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\bootstrap\bootstrap.php(169): craft\services\Config->getConfigFromFile('general') #1 C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\bootstrap\web.php(42): require('C:\\Users\\xmr\\De...') #2 C:\Users\xmr\Desktop\stackpath\web\index.php(20): require('C:\\Users\\xmr\\De...') #3 {main} thrown in C:\Users\xmr\Desktop\stackpath\vendor\craftcms\cms\src\services\Config.php on line 220
```

**Comment by XhmikosR** [comment] 2018-08-14 19:44
Well, that's what I'm getting...

https://gist.github.com/XhmikosR/f44ce9526b8851f512e0b41c3757280e/revisions

So as you can see the config.php file is identical apart from the two lines.

**Comment by XhmikosR** [comment] 2018-08-14 19:44
So as you can see the config.php file is identical apart from the two lines.

**Comment by XhmikosR** [comment] 2018-08-14 20:07
Ok, so I tried this with plain old `echo` locally. The if null path is not being executed ever. If you want me to try something else let me know.

**Comment by khalwat** [comment] 2018-08-14 20:10
...but the problem has never happened locally, yes?

**Comment by XhmikosR** [comment] 2018-08-14 20:12
Yes, because locally I never use production. But I can't echo stuff on a live server, you understand.

**Comment by XhmikosR** [comment] 2018-08-14 20:18
But I was able to reproduce locally too, by setting my env to production and using the first config from here https://github.com/nystudio107/craft-seomatic/issues/189#issuecomment-412859248

meta robots was set wrongfully to none.

**Comment by XhmikosR** [comment] 2018-08-14 20:18
meta robots was set wrongfully to none.

**Comment by khalwat** [comment] 2018-08-14 20:32
So I think the issue is actually this:

```
        // If it's not a multi-environment config, return the whole thing
        if (!array_key_exists('*', $config)) {
            return $config;
        }
```

If you have no default `'*'` key, it doesn't consider the file to be a valid multi-environment config, and it just returns the whole array... which then isn't going to have valid keys, so it probably falls back on whatever the db is set to.

This isn't a bug in SEOmatic, this is a multi-environment config file not implemented properly. You'll have the same exact issue with the Craft CMS multi-environment config files, for the same reason:

https://github.com/craftcms/cms/blob/develop/src/services/Config.php#L215

For it to be considered a valid multi-environment config, the `'*'` array as it appears in the documentation must exist: https://github.com/nystudio107/craft-seomatic#plugin-settings

Official Craft documentation on multi-environment configs: https://docs.craftcms.com/v2/multi-environment-configs.html

Note the **TIP**:

> The '*' array is required to enable Craft’s multi-environment config support, even if you don’t need it. Craft specifically checks for it when deciding whether to enable multi-environment config support or not.

**Closed as completed by khalwat** 2018-08-14 20:32 UTC
Labels: need info

**Comment by XhmikosR** [comment] 2018-08-14 20:34
OK, so in theory I should have no issue with the `'*'` config present. Can that be empty, though?

**Comment by khalwat** [comment] 2018-08-14 20:36
Yes, it can be empty. As per the code above, it only checks for the key's existence to know whether it's a multi-environment config or not.

**Comment by XhmikosR** [comment] 2018-08-14 20:37
All right. Huge thanks for your time, I really appreciate it.

It's just that I only hit this with your plugin since no other plugin is using this setup.

**Comment by XhmikosR** [comment] 2018-08-14 20:43
@brandonkelly: this should be made clearer on v3 docs too. Perhaps a warning or something.

**Comment by brandonkelly** [comment] 2018-08-14 20:45
Uh not going to read this :) Feel free to post an issue with the TL;DR on https://github.com/craftcms/docs/issues

**Comment by XhmikosR** [comment] 2018-08-14 20:50
Done :)

**Comment by XhmikosR** [comment] 2018-08-18 09:00
@khalwat So, this happened again on our production app's homepage. The other pages seem to be fine.
