### ISSUE TITLE
Dashboard graphs out of sync with Content SEO

### ISSUE THREAD

**Issue by rogerdawkins** [nystudio107/craft-seomatic#254] opened 2018-10-31 13:24 UTC
Attached images will show the issue best.
![image](https://user-images.githubusercontent.com/42376821/47790561-6c898580-dd0f-11e8-8183-7b0a770d79ee.png)
As you can see 16.7% showing as D.
![image](https://user-images.githubusercontent.com/42376821/47790598-84f9a000-dd0f-11e8-90e0-a7abfe11933c.png)
But the Content SEO page shows no D, should be 66.7% as A and 33.3% as B.

I suspect this issue was caused by the fact that I had a section which had both an Entry URI Format and Template selected which were showing as D. But I realised that the section should not have an Entry or Template as they were just used within another page. So I removed the settings but the Dashboard graphs appear to still be taking them into account when doing the calcs.

I've made lots of settings changes but can't seem to get the graphs to recalculate.

**Comment by khalwat** [comment] 2018-11-01 15:04
Yep, you're correct in your assessment. The issue is that the old metabundles are still there. I'll put something in to clean this up for the graph display.

**Comment by rogerdawkins** [comment] 2018-11-01 17:23
Perfect, thanks Andrew, no rush, it just makes me look bad with a 'D' on my graph :)

**Comment by khalwat** [comment] 2018-11-01 20:46
Fixed in https://github.com/nystudio107/craft-seomatic/commit/4b6329cb0c39a5e41827c88aa8788ca106ec4862

**Closed as completed by khalwat** 2018-11-01 20:46 UTC
Labels: bug
