### ISSUE TITLE
Multi-site: SEO Preview URLs only render with the Primary Site domain

### ISSUE THREAD

**Issue by danvolkens** [nystudio107/craft-seomatic#607] opened 2020-04-16 15:58 UTC
When editing an entry in Site B, the SEO preview renders urls from the primary site domain, Site A. I tested switching Site B to be the primary site and then only Site B domain was rendered. So it appears that no matter which site I'm working in, the SEO Preview always renders links with the primary site's domain.

**Comment by khalwat** [comment] 2020-04-16 20:20
I will have a look at this. This is a regression if it's an actual bug, because this definitely did work properly at one point.

**Comment by khalwat** [comment] 2020-04-16 20:27
So I did a quick test locally, and this seems to be working correctly?

English:

<img width="1436" alt="Screen Shot 2020-04-16 at 4 25 08 PM" src="https://user-images.githubusercontent.com/7570798/79503346-0249cb00-7fff-11ea-8ff8-9513132c9ef2.png">

French:

<img width="1436" alt="Screen Shot 2020-04-16 at 4 25 44 PM" src="https://user-images.githubusercontent.com/7570798/79503368-0b3a9c80-7fff-11ea-9257-201f440feab4.png">

Note that the SEO Title preview is different, and reflects the title of each localized site.

What version of SEOmatic are you using, and what version of Craft are you using? Can you add any more detail to this for me?

**Comment by danvolkens** [comment] 2020-04-16 21:56
Thanks! I will drop you some screenshots of it in my environment and versions tomorrow morning. Appreciate it. 

Note that it’s the wrong domain that is displayed and linked to for the previews, not just the title in my case. Say I have my primary site domain as something.com and I’m editing the entry on another site with domain somethingelse.com. The preview always displays and links to the primary site’s domain.

**Comment by danvolkens** [comment] 2020-04-17 13:30
Example of editing an entry in a second site, but the SEO preview sets the domain to the Primary Site domain: 
![image](https://user-images.githubusercontent.com/438082/79574174-c6aa1200-808d-11ea-9a67-ebea7aaab0a3.png)

Primary site set as builtbyhlt.com:
![image](https://user-images.githubusercontent.com/438082/79574283-ec371b80-808d-11ea-9b28-2665805fb873.png)

If I change the Primary site to mynursingmastery.com, then the Preview changes the domain accordingly:
![image](https://user-images.githubusercontent.com/438082/79574320-f9540a80-808d-11ea-9fef-aa217162f5af.png)
![image](https://user-images.githubusercontent.com/438082/79574329-fb1dce00-808d-11ea-976d-d5cca28a0e94.png)

**Comment by khalwat** [comment] 2020-04-17 16:05
I see okay, so the title/description is correct, but what your'e saying is the URLs alone are incorrect, yes?

**Comment by danvolkens** [comment] 2020-04-17 16:06
Correct! All metadata in the previews is correct except for the domain. This is for what is displayed as well as the link out.

**Comment by khalwat** [comment] 2020-04-18 01:21
Fixed in https://github.com/nystudio107/craft-seomatic/commit/6c3bb8ce8a689a2b3d3cda1a6f02f3cdbf52855d

**Closed as completed by khalwat** 2020-04-18 01:21 UTC
Labels: need info
