### ISSUE TITLE
Manually setting a "canonical" with query strings within a Sprig component

### ISSUE THREAD

**Issue by aaronbushnell** [nystudio107/craft-seomatic#1362] opened 2023-10-02 14:52 UTC
I have a Sprig-powered blog listing where a user can paginate and filter posts by category. When they do that, they end up with URLs such as...

```
/blog?category=foo&page=2
```

I'd like to set the canonical meta tag to this for indexing purposes:
```html
<link href="https://mysite.com/blog?category=foo&page=2" rel="canonical">
```

However, it seems using the following creates an odd output in the HTML:
```twig
{# Used in my blog listing partial #}
{% do seomatic.link.get("canonical").href("https://mysite.com/blog?category=foo&page=2") %}

{# SEOmatic output #}
<link href="https://mysite.test/blog?category=foo&amp;page=2%2F" rel="canonical">
```

Am I doing something wrong here or misunderstanding the use of query strings within the canonical meta tag? It seems like it makes sense to use them because they do resolve to unique changes within my Sprig components, but perhaps I'm missing something.

**Comment by khalwat** [comment] 2023-10-05 12:57
Are you using `seomatic.helper.paginate(PAGEINFO)`? 

ref: https://nystudio107.com/docs/seomatic/using.html#helper-functions-seomatic-helper

If not, you probably should be... it should take care of all of this automatically for you.

I'm not sure how/why Sprig should be a factor here, because dynamically loaded Sprig components likely will not be altering meta tags (they've already rendered in the DOM), and bots are going to load the direct URL (thus no Sprig will be involved).

Anyway if you truly need to set the canonical directly (which you probably should not be doing in this case), the issue you've having is likely just do to encoding. Maybe something like this:

```twig
{% do seomatic.link.get("canonical").href("https://mysite.com/blog?category=foo&page=2" | raw) %}
```

**Comment by aaronbushnell** [comment] 2023-10-06 13:21
Sprig is paginating through results, but we're also using the [`sprig.pushUrl(url)`](https://putyourlightson.com/plugins/sprig#sprig-pushurlurl) variable to create unique URLs.
```twig
{% do sprig.pushUrl("?category=#{category|url_encode}&page=#{page|url_encode}") %}
```

While `seomatic.helper.paginate()` would probably work if we were using Craft's native pagination it doesn't seem to infer the more customized approach we're taking. Which is totally understandable.

And, unfortunately, it seems the `| raw` filter isn't helping with the character encoding we're seeing in the canonical meta tag:
```twig
<!-- <head> -->
<link href="https://mysite.com/blog?category=foo&amp;page=2%2F" rel="canonical">

<!-- page.twig -->
{% do seomatic.link.get("canonical").href("https://mysite.com/blog?category=foo&page=2" | raw) %}
```

**Comment by khalwat** [comment] 2023-10-06 14:24
Just so I understand... if someone puts this in their browser:

```
https://mysite.com/blog?category=foo&page=2
```

...how is Sprig involved in the paginated results here when the page is directly loaded using page 2?

**Comment by aaronbushnell** [comment] 2023-10-06 18:24
Here's a _very_ stripped down setup of what I'm doing. I've removed the `category` part because it's not necessary to demonstrate how this is setup and just adds clutter to a more simplified example.

```twig
{% set page = page ?? 1 %}

{% do sprig.pushUrl("?page=#{page|url_encode}") %}
{% set pageQuery = craft.entries.section('blog').limit(6) %}
{% set pageInfo = sprig.paginate(pageQuery, page) %}
{% set pageEntries = pageInfo.pageResults %}

<div s-swap="innerHTML show:top">
  {% for post in pageEntries %}
    <p>{{ post.title }}</p>
  {% endfor %}

  {# Previous #}
  {% if page > 1 %}
    <button sprig s-val:page="{{ page - 1 }}" s-push-url="?page={{ page - 1 }}">Previous</button>
  {% endif %}

  {# Next #}
  {% if page < pageInfo.totalPages %}
    <button sprig s-val:page="{{ page + 1 }}" s-push-url="?page={{ page + 1 }}">Next</button>
  {% endif %}
</div>

```

**Comment by khalwat** [comment] 2023-10-07 21:19
So I had a look into this, and SEOmatic is actually calling Yii2's `Html::tag()` in the end, which is what is doing the encoding... and it's actually correct to be doing so:

https://www.webmasterworld.com/html/4547916.htm

So essentially this is not a bug; the `&amp;` is supposed to be encoded in an HTML tag context, and it will work just fine either encoded or decoded.

**Closed as completed by khalwat** 2023-10-07 21:19 UTC
Labels: question

**Comment by aaronbushnell** [comment] 2023-10-09 13:57
Got it! The `%2F` is the trailing `/` in the URL so this appears to check out. Thanks!
