### ISSUE TITLE
Entry details view CSS not loading on Craft 3.1.30

### ISSUE THREAD

**Issue by TheFunkyMonk** [nystudio107/craft-seomatic#423] opened 2019-06-12 20:09 UTC
# Description

I noticed some odd styling issues editing an entry on a site I'm developing after upgrading from Craft 3.1.21 to 3.1.30 (matrix fields overlapping, site name displaying in a smaller font). To narrow things down, I spun up a fresh Craft install to try to replicate.

After setting up a test section and entry on the fresh install, I could not reproduce the issue, until I installed SEOmatic. The most obvious element to compare is the site name on the top left (`Craft Test` in the below screenshots) - in the entry listing view, it displays larger than on the entry details view. The style for that element is coming from `/cpresources/bbd1c323/css/_main.scss`, which doesn't appear to load on the entry view after installing SEOmatic.

# Steps to reproduce

1. Install Craft CMS latest version (3.1.30)
2. Create a section and entry within (I used a Structure type)
3. Navigate to entry details (notice site title stays the same size)
4. Install SEOmatic
5. Navigate back to entry details (notice site title now becomes smaller)

# Screenshots

Entries listing view:
![01-entries](https://user-images.githubusercontent.com/1728770/59382219-07b8f380-8d12-11e9-8bcc-78e9b1f09fef.png)

Entries details view:
![02-entry-details](https://user-images.githubusercontent.com/1728770/59382247-11daf200-8d12-11e9-9ad4-c070ba8a46a6.png)

Example of matrix field display issue:
![03-matrix-fields](https://user-images.githubusercontent.com/1728770/59382254-199a9680-8d12-11e9-9c1e-b8eecbe4ef1e.png)

## Note
I tested this with a site that was running Craft version 3.1.21 with SEOmatic 3.1.47 - was not able to reproduce on that version of Craft/SEOmatic, but after updating Craft to 3.1.30 and SEOmatic 3.2.7, the issue cropped up. Potentially something causing a conflict in a very recent version of Craft?

**Comment by TheFunkyMonk** [comment] 2019-06-13 00:48
Update - Can actually narrow this down to v3.2.7 of SEOmatic. Downgrading to v3.2.6 resolves the issue, and updating to v3.2.7 brings it back.

**Comment by khalwat** [comment] 2019-06-13 01:57
The issue is that in converting it over to Tailwind CSS `^1.0.0`, I made a mistake and included the CSS-reset. Fixed in https://github.com/nystudio107/craft-seomatic/commit/7f256f328658e8db821767b293a8a2816ea2321f

**Closed as completed by khalwat** 2019-06-13 01:57 UTC
