### ISSUE TITLE
Cannot update another plugin because of version constraints in SEOMatic

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#1157] opened 2022-06-16 02:21 UTC
### Describe the bug
I am unable to update Top Shelf Craft's plugin "Wordsmith", and it seems to be because of a version constraint in SEOMatic … and I know, maybe I should take the opportunity to switch to your own Typogrify plugin ;-)

### To reproduce
Steps to reproduce the behaviour:
1. I have Wordsmith 4.0.0.1 installed
3. Run composer update (should update to 4.0.1)
4. Plugin remains at 4.0.0.1
5. See below for composer reports

### Expected behaviour
Plugin should update if possible

### Screenshots
Composer lists the following package restraints:
```
$ composer why-not topshelfcraft/wordsmith 4.0.1
topshelfcraft/wordsmith  4.0.1 requires davechild/textstatistics (^1.0.3)
andrewmac/spm-commercial dev-develop does not require davechild/textstatistics (but 1.0.2 is installed)
$ composer why davechild/textstatistics
nystudio107/craft-seomatic 4.0.1 requires davechild/textstatistics (1.0.2)
topshelfcraft/wordsmith 4.0.0.1 requires davechild/textstatistics (^1.0)
```
So I wonder if SEOMatic definitely needs davechild/textstatistics locked to 1.0.2?

### Versions
- Plugin version: SEOMatic 4.0.1, Wordsmith 4.0.0.1
- Craft version: Craft Pro 4.0.4

**Comment by khalwat** [comment] 2022-06-16 02:49
Duplicate of https://github.com/nystudio107/craft-seomatic/issues/1153

**Closed as completed by khalwat** 2022-06-16 02:49 UTC
Labels: bug

**Comment by ghost** [comment] 2022-06-16 03:02
Thanks so much, and apologies that I didn't notice that other issue!

**Comment by khalwat** [comment] 2022-06-16 19:04
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/2a9aaaf7ea06c4678fd4ae8fd4ae023bc05692cc

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`
