### ISSUE TITLE
{seomatic.helper...} tags in output

### ISSUE THREAD

**Issue by croxton** [nystudio107/craft-seomatic#990] opened 2021-09-28 09:46 UTC
### Describe the bug
After upgrading to 3.4.14 from 3.3.13 I'm seeing numerous instances of `{seomatic.helper....}` tags for image paths, widths and heights.

Example metadata - appears to be trying to output an empty `teaserImage` field but it should default to the selected SEO Image Source which is overridden in the SEO field for the entry:

```
<meta name="twitter:image:width" content="{{ seomatic.helper.socialTransformWidth(entry.teaserImage[0], seomatic.helper.twitterTransform(), 1, &quot;crop&quot;) }}">
<meta name="twitter:image:height" content="{{ seomatic.helper.socialTransformHeight(entry.teaserImage[0], seomatic.helper.twitterTransform(), 1, &quot;crop&quot;) }}">
```

And JSON-LD (when no creator set):
```
{
"@id": "#creator",
"@type": "Organization",
"logo": {
"@type": "ImageObject",
"height": "{seomatic.helper.socialTransformHeight(seomatic.site.creator.genericImageIds[0], \"schema-logo\")}",
"url": "https://[redacted]/(seomatic.helper.socialTransform(seomatic.site.creator.genericImageIds[0], \"schema-logo\"))",
"width": "{seomatic.helper.socialTransformWidth(seomatic.site.creator.genericImageIds[0], \"schema-logo\")}"
 }
},
```

### Expected behaviour
Output should be same as 3.3.x branch of SEOmatic

### Versions
- Plugin version: 3.4.14
- Craft version: 3.7.13

**Comment by croxton** [comment] 2021-09-28 09:54
Downgraded to `3.4.11` and all working properly as far as I can tell (phew!).

**Comment by khalwat** [comment] 2021-09-28 11:50
> Example metadata - appears to be trying to output an empty teaserImage field but it should default to the selected SEO Image Source which is overridden in the SEO field for the entry:

Can you expand on this? You're saying that the SEO Settings field is no longer overriding as expected *and* Twig is being output instead of the rendered image?

Is the Override switch on the SEO Settings field enabled?

**Comment by khalwat** [comment] 2021-09-28 12:06
Can you search through your `web.log` to see if you have any MetaValue-related rendering `[error]`s listed?

**Comment by croxton** [comment] 2021-09-28 12:07
> Can you expand on this? You're saying that the SEO Settings field is no longer overriding as expected and Twig is being output instead of the rendered image?

The `{seomatic.helper..}` output referenced the teaserImage field, but the override switch was enabled and a different field had been selected. This happened for Twitter images - the main SEO image was output correctly (the selected heroImage).

> Is the Override switch on the SEO Settings field enabled?

Yes.

I'll try to explain:
* Section is set to use `From Asset field` > `teaserImage` by default for the SEO image source. 
* Twitter, Facebook are set to use `Same As SEO image`.
* SEOmatic field is set to display SEO title, SEO Description and SEO Image.
* On the entry in question, the Override switch is enabled and the content editor had selected the `heroImage` field (which was populated with an image). The `teaserImage` field was empty.
* I tried clearing the SEOmatic caches, didn't help.

**Comment by khalwat** [comment] 2021-09-28 12:07
> Downgraded to 3.4.11 and all working properly as far as I can tell (phew!).

At what version does the regression manifest itself?

**Comment by croxton** [comment] 2021-09-28 12:09
I only tried 3.4.11 as I looked through the other issues and saw that there were problems with previous versions too that would impact this site. I'm on a very tight deadline and I need to get this into production asap, so tried 3.4.11 and it worked. Will check the logs now.

**Comment by croxton** [comment] 2021-09-28 12:23
I've found some warnings/errors like this in the log (not exactly in this order, I've collected them together):
```
2021-09-28 11:41:28 [-][1][-][info][nystudio107\seomatic\base\MetaItem::debugMetaItem] ERROR - JSON-LD property: image -> Must be one of these types: ImageObject, URL -> Must be one of these types: ImageObject, URL
2021-09-28 11:41:28 [-][1][-][info][nystudio107\seomatic\base\MetaItem::debugMetaItem] JSON-LD property: image -> An image of the item. This can be a URL or a fully described ImageObject.
2021-09-28 11:41:28 [-][1][-][info][nystudio107\seomatic\base\MetaItem::debugMetaItem] ERROR - Tag attribute: content -> Content is not a valid URL.
2021-09-28 11:41:28 [-][1][-][info][nystudio107\seomatic\base\MetaItem::debugMetaItem] WARNING - Tag attribute: content -> Content is not a valid URL.
2021-09-28 11:41:28 [-][1][-][info][nystudio107\seomatic\base\MetaItem::debugMetaItem] WARNING - Tag attribute: content -> Content should contain at least 40 characters.
```

**Comment by khalwat** [comment] 2021-09-28 13:05
Yeah those are just side-effects of it not rendering unfortunately, and not the type of errors I was hoping to see to help pinpoint the issue.

**Comment by khalwat** [comment] 2021-09-28 13:13
Unable to reproduce thus far on a few different test sites. I wonder what could be the cause here.

**Comment by khalwat** [comment] 2021-09-28 13:25
I also just updated two of my public sites to 3.4.14, and am not seeing an issue when viewing the source:

https://devmode.fm/

https://nystudio107.com/

**Comment by magnessjo** [comment] 2021-09-28 14:35
@khalwat, not sure if it's related to this issue, but I see some log errors after upgrading to 3.4.14.  They stem from the helpers class so I added a screenshot to this ticket/context.  Please let me know if you would prefer a separate ticket for it.  

<img width="1572" alt="Screen Shot 2021-09-28 at 10 33 08 AM" src="https://user-images.githubusercontent.com/856595/135108225-7aa7edca-3d61-4680-b51c-d7c30b385aaa.png">

**Comment by khalwat** [comment] 2021-09-28 15:07
@magnessjo I've fixed that in an unreleased branch, it's unrelated to the issue above, unfortunately.

**Comment by croxton** [comment] 2021-09-28 15:09
I tried that fix for `{prime}` and it doesn't help. I get the error if a section is set to use a particular Asset field for the SEO image, and the field is empty. I'm using Google Cloud Storage for Assets, which may (or may not) be relevant.

Output on one entry with SEO Image set to a field `logo`. The field has no image:
```
<meta content="[redacted - just the site url]" property="og:image">
<meta content="{{ seomatic.helper.socialTransformWidth(entry.logo[0], &quot;facebook&quot;, 1, &quot;crop&quot;) }}" property="og:image:width">
<meta content="{{ seomatic.helper.socialTransformHeight(entry.logo[0], &quot;facebook&quot;, 1, &quot;crop&quot;) }}" property="og:image:height">

<meta name="twitter:image" content="[redacted - just the site url]">
<meta name="twitter:image:width" content="{{ seomatic.helper.socialTransformWidth(entry.logo[0], seomatic.helper.twitterTransform(), 1, &quot;fit&quot;) }}">
<meta name="twitter:image:height" content="{{ seomatic.helper.socialTransformHeight(entry.logo[0], seomatic.helper.twitterTransform(), 1, &quot;fit&quot;) }}">
```

Error:
```
Error rendering `{{ seomatic.helper.socialTransform(entry.logo[0], "base", 1, "crop") }}` -> Key "0" in object with ArrayAccess of class "craft\elements\db\AssetQuery" does not exist in "__string_template__49793f93d148b5574eb541bb6c900133517848d1417586bd0cf4a7d6dd1b6777" at line 1. - {{ seomatic.helper.socialTransform(entry.logo[0], "base", 1, "crop") }}
```

Stack trace:
```
Twig\Error\RuntimeError: Key "0" in object with ArrayAccess of class "craft\elements\db\AssetQuery" does not exist in "__string_template__49793f93d148b5574eb541bb6c900133517848d1417586bd0cf4a7d6dd1b6777" at line 1. in [redacted]/vendor/twig/twig/src/Extension/CoreExtension.php:1392
Stack trace:
#0 [redacted]/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\AssetQuery), 0, Array, 'array', false, false)
#1 [redacted]/storage/runtime/compiled_templates/fb/fb615e72fcc1dc0b1fd16f46ffd6c6e83f6d7be004e57bddaf6b836ff1b1294b.php(38): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\AssetQuery), 0, Array, 'array')
#2 [redacted]/vendor/twig/twig/src/Template.php(405): __TwigTemplate_9fb33dd83a64ae336a8f47e35d09068e6c0cf8ee9357e58c1360813175953600->doDisplay(Array, Array)
#3 [redacted]/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#4 [redacted]/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#5 [redacted]/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#6 [redacted]/vendor/craftcms/cms/src/web/View.php(536): Twig\TemplateWrapper->render(Array)
#7 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(340): craft\web\View->renderString('{{ seomatic.hel...', Array)
#8 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(279): nystudio107\seomatic\helpers\MetaValue::internalRenderObjectTemplate('{{ seomatic.hel...', Array)
#9 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(101): nystudio107\seomatic\helpers\MetaValue::parseMetaString('{{ seomatic.hel...', true, true)
#10 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(144): nystudio107\seomatic\helpers\MetaValue::parseString('{{ seomatic.hel...', true, true, 3)
#11 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(120): nystudio107\seomatic\helpers\MetaValue::parseArray(Array)
#12 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(87): nystudio107\seomatic\helpers\JsonLd::normalizeJsonLdArray(Array, 3)
#13 [redacted]/vendor/yiisoft/yii2/helpers/BaseJson.php(198): nystudio107\seomatic\helpers\JsonLd::processData(Array, Array, '61532beb78f509....')
#14 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(85): yii\helpers\BaseJson::processData(Array, Array, '61532beb78f509....')
#15 [redacted]/vendor/yiisoft/yii2/helpers/BaseJson.php(198): nystudio107\seomatic\helpers\JsonLd::processData(Array, Array, '61532beb78f509....')
#16 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(85): yii\helpers\BaseJson::processData(Array, Array, '61532beb78f509....')
#17 [redacted]/vendor/yiisoft/yii2/helpers/BaseJson.php(198): nystudio107\seomatic\helpers\JsonLd::processData(Array, Array, '61532beb78f509....')
#18 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(85): yii\helpers\BaseJson::processData(Array, Array, '61532beb78f509....')
#19 [redacted]/vendor/yiisoft/yii2/helpers/BaseJson.php(68): nystudio107\seomatic\helpers\JsonLd::processData(Object(nystudio107\seomatic\models\MetaJsonLd), Array, '61532beb78f509....')
#20 [redacted]/vendor/nystudio107/craft-seomatic/src/helpers/JsonLd.php(73): yii\helpers\BaseJson::encode(Object(nystudio107\seomatic\models\MetaJsonLd), 449)
#21 [redacted]/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLd.php(282): nystudio107\seomatic\helpers\JsonLd::encode(Object(nystudio107\seomatic\models\MetaJsonLd))
#22 [redacted]/vendor/nystudio107/craft-seomatic/src/models/MetaJsonLdContainer.php(122): nystudio107\seomatic\models\MetaJsonLd->render(Array)
#23 [redacted]/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(335): nystudio107\seomatic\models\MetaJsonLdContainer->includeMetaData(Object(yii\caching\TagDependency))
#24 [redacted]/vendor/nystudio107/craft-seomatic/src/Seomatic.php(879): nystudio107\seomatic\services\MetaContainers->includeMetaContainers()
#25 [internal function]: nystudio107\seomatic\Seomatic->nystudio107\seomatic\{closure}(Object(yii\base\Event))
#26 [redacted]/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#27 [redacted]/vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#28 [redacted]/vendor/yiisoft/yii2/web/View.php(175): yii\base\Component->trigger('endPage')
#29 [redacted]/vendor/craftcms/cms/src/web/View.php(1701): yii\web\View->endPage(false)
#30 [redacted]/vendor/craftcms/cms/src/web/View.php(462): craft\web\View->endPage()
#31 [redacted]/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('members/_entry', Array, 'site')
#32 [redacted]/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('members/_entry', Array)
#33 [internal function]: craft\controllers\TemplatesController->actionRender('members/_entry', Array)
#34 [redacted]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#35 [redacted]/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#36 [redacted]/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#37 [redacted]/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#38 [redacted]/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('templates/rende...', Array)
#39 [redacted]/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#40 [redacted]/vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#41 [redacted]/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#42 [redacted]/web/index.php(26): yii\base\Application->run()
#43 {main}
```

**Comment by khalwat** [comment] 2021-09-28 15:11
@croxton perfect, that gives me the clue I need to fix it, thx!

**Comment by croxton** [comment] 2021-09-28 15:12
No worries. I'm going to step back in releases and see when if I can find when it broke.

**Comment by khalwat** [comment] 2021-09-28 15:13
It'll be in the 3.4.14 update

**Comment by croxton** [comment] 2021-09-28 15:15
Confirmed: working in 3.4.13

**Comment by khalwat** [comment] 2021-09-28 15:18
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/c8c70c648c0448bca1f8bb0f03ebd62feeaa04fb

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.15”,
```
Then do a `composer clear-cache && composer update`

**Comment by croxton** [comment] 2021-09-28 15:27
That hasn't fixed it (sorry!)

**Comment by khalwat** [comment] 2021-09-28 15:35
The strange part @croxton is that if an error is encountered rendering a meta value template string, it logs the error you noted above:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/MetaValue.php#L287

...but then does:

```
return null;
```

which should result in an empty value for the rendered field, which would cause it to fall back on previous values.

**Comment by croxton** [comment] 2021-09-28 15:42
Hmm yeah, that bit's not working, but I think the main problem is maybe the regex here?

https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/MetaValue.php#L331

**Comment by khalwat** [comment] 2021-09-28 15:43
Shouldn't be, that's the exact regex that Craft uses:

https://github.com/craftcms/cms/blob/develop/src/web/View.php#L686

**Comment by khalwat** [comment] 2021-09-28 15:55
I set things up to mirror the setup you described, and it's working properly here:

Content SEO setting:
<img width="759" alt="Screen Shot 2021-09-28 at 11 52 41 AM" src="https://user-images.githubusercontent.com/7570798/135122246-6c6dc276-4d7b-4b81-9c14-49e6aed2d412.png">

SEO Settings field:

<img width="759" alt="Screen Shot 2021-09-28 at 11 52 25 AM" src="https://user-images.githubusercontent.com/7570798/135122250-80dbd370-07a0-43ce-86b4-f04ea3396674.png">

Asset field:

<img width="759" alt="Screen Shot 2021-09-28 at 11 52 12 AM" src="https://user-images.githubusercontent.com/7570798/135122251-52dcfe18-66ef-4ffd-a394-c69880f68641.png">

Result:

<img width="342" alt="Screen Shot 2021-09-28 at 11 54 49 AM" src="https://user-images.githubusercontent.com/7570798/135122471-416fce6d-86bc-4f66-a012-1f35611e4324.png">

```html
<meta content="http://localhost:8000/assets/site/_1200x630_crop_center-center_82_none/its-time-to-stop.jpg?mtime=1632844217" property="og:image">
```

**Comment by khalwat** [comment] 2021-09-28 15:57
Can you confirm that in your local `vendor/` you're seeing this code:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/MetaValue.php#L334

**Comment by croxton** [comment] 2021-09-28 16:07
Yes it's there!

It seems to be working now using dev-develop! But, and I'm sure of this, it wasn't. Opcache was disabled, all caches cleared, storage emptied. Wasn't working 20 minutes ago but now I can confirm it is. 

I'm honestly perplexed by this!!

**Comment by khalwat** [comment] 2021-09-28 16:08
Magic? :D

**Comment by croxton** [comment] 2021-09-28 16:08
Mate, I'll take that. What a day.

**Closed as completed by khalwat** 2021-09-28 16:08 UTC
Labels: bug

**Comment by m9dfukc** [comment] 2021-11-29 20:41
Hey, unfortunately I am running into the same issue.

`  <img id="test" src="{{ seomatic.meta.seoImage }}" /> `

leads to:

`<img id="test" src="{seomatic.helper.socialTransform(2381, "base", 0, "crop")}">`

My assets are all stored locally on the server. 

**Versions**
Plugin version: 3.4.20 (also tested 3.4.11, same issue)
Craft version: 3.7.23

**Comment by khalwat** [comment] 2021-11-30 00:15
@m9dfukc That's expected behavior.

If you want the actual parsed result, you need to use: 

```twig
<img id="test" src="{{ seomatic.meta.parsedValue('seoImage') }}" />
```

ref: https://nystudio107.com/docs/seomatic/using.html#seomatic-variables

This isn't typical usage, generally you aren't using SEOmatic's internal variables to output to HTML tags (it does this for you in the various meta tags)
