### ISSUE TITLE
Slow response for Metadata Containers

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-seomatic#736] opened 2020-08-27 15:26 UTC
### Question
As raised in https://github.com/nystudio107/craft-seomatic/issues/728, we are seeing slow response times for metadata containers in the Craft profiler. Our production environment is load balancer across 2 EC2s in AWS without any additional caching. 

If this is an issue with items being uncached then it is strange that the SEO containers are the only ones affected, we do not get the issue with templates etc. We rarely clear our caches manually (only after deployment) so it appears that the containers are just not being cached correctly?

![image](https://user-images.githubusercontent.com/3185073/91462380-0544aa00-e882-11ea-843c-14acdb85f93a.png)

**Comment by baileydoestech** [comment] 2020-08-27 15:28
Identical deployment to our staging site is much more reasonable, only difference is that it is not load balanced:

![image](https://user-images.githubusercontent.com/3185073/91462645-50f75380-e882-11ea-8bca-5d5c7503bca2.png)

**Comment by khalwat** [comment] 2020-08-28 03:05
What caching method are you using?

**Comment by khalwat** [comment] 2020-08-28 03:07
Also your staging server certainly seems more in line with what I'd expect to see from a cache hit. I'd start looking for differences between staging and production.

Even simple things like is `devMode` on by accident on production or the like... which would also explain what's going on, because SEOmatic's caches last only 30 seconds if your environment is local dev and if `devMode` is on, it forces it to act like it's in local dev.

Also check your `ENVIRONMENT` variable in your `.env` file on production to make sure it's not set to `dev` or what have you.

**Comment by baileydoestech** [comment] 2020-08-28 12:20
Caching just to the file system, aware that this duplicates the cache across our LB environment but would expect the metadata containers to be cached after the first hit to each instance (which they don't appear to be doing after Craft 3.5).

`devMode` definately off on all environments, the only difference is the load balancing so it seems like the cache is either not getting written to or somewhere clear after each visit.

Redis is certainly the planned resolution to this and something we have wanted to explore for a while but just perplexed why this has suddenly started to happen...

**Comment by khalwat** [comment] 2020-08-28 14:06
@lukebailey yeah I don't know, but if it's working as expected in your staging environment, I'd look for differences between the two environments.

There aren't any changes to SEOmatic in recent memory that could affect this that I'm aware of.

The only other thing I can think if is that SEOmatic will not cache things if it thinks it's a Preview or Live Preview request, or if the status code in the response is >= 400

There have been some major changes in Craft CMS in version 3.5, but again... if it's working as expected in staging, but not in production, it's almost always going to be an environmental difference.

**Comment by khalwat** [comment] 2020-08-28 14:07
And yes, especially in a load balanced environment, I would highly recommend using Redis, or having your file system where the cache files reside be shared.

Otherwise you have no cache coherency.

**Comment by khalwat** [comment] 2020-09-10 15:18
I will re-open this if additional information is presented.

**Comment by leehaskings** [comment] 2020-09-14 03:02
We're seeing a slow down related to metaContainers in our live install as well.

Switching off all images/transforms did seem to resolve it and does indicate an issue in that area (we're using the Amazon S3 plugin with asset indexing/caching on).

However, turning all meta images back on and turning off just the jsonLd container with the below has made a massive difference (see attached screenshots)

`{% do seomatic.jsonLd.container().include(false) %}`

Couldn't resist tracing it further and found the slowdown happening somewhere deep into the JSON encode functions of Yii where it loops through the object and once it hits the 'image' key something seems to slow it down.

![metacontainers-disabled](https://user-images.githubusercontent.com/18319962/93039036-d6a03f00-f689-11ea-8fef-e949414c9c3e.PNG)
![metacontainer-enabled](https://user-images.githubusercontent.com/18319962/93039040-d7d16c00-f689-11ea-8c63-7e191d3454de.PNG)

**Comment by khalwat** [comment] 2020-09-14 03:54
@leehaskings Please make sure that caching is working as expected. For that to happen, `devMode` needs to be off, and your `ENVIRONMENT` needs to be set to production or staging

I think it's very likely that you're seeing uncached hits there.

**Comment by leehaskings** [comment] 2020-09-14 04:19
@khalwat I agree it feels like a caching issue - but it seems to not be caching at all if that's the case.

Have just double checked the environment and devMode is definitely false - verified in the admin panel with the dev icon hiding/showing in the page title when switching between modes.

Interestingly, when we switch .env to our 'staging' environment the speed issues are gone - opposite to what we were expecting.

**Comment by 3dgroup** [comment] 2020-10-06 19:00
We are experiencing the same issues! 

This solves issue for now
{% do seomatic.jsonLd.container().include(false) %}

Tried disabling the transformations but didn't seem to change anything (unless I missed a setting somewhere).

Why has this been closed? Seems like its not been resolved.

**Comment by khalwat** [comment] 2020-10-07 00:33
@3dgroup this was closed because originally I was waiting on additional information. But after hearing from @leehaskings and the fact that changing their `.env` results in the speed issues being gone, this is very likely something environmental or devops related, and not SEOmatic related.

I'd need more information to go on here, as I'm unable to reproduce the issue.

**Comment by 3dgroup** [comment] 2020-10-07 07:40
What more info do you need.

- We use AWS for our images just like @leehaskings
- I experience this on two different servers. 
- Cache seems to be working for everything else.
- Happens on staging and production

**Comment by baileydoestech** [comment] 2020-10-07 08:52
Very similar setup on our side too (AWS, load balanced, happens in multiple envronments but not single server setups). Deploying Redis this week to determine if that resolves the issue.

**Comment by 3dgroup** [comment] 2020-10-07 09:08
We don't have a load balancer. We do have Cloudflare setup on the domain (although I am not sure that should be an issue).

**Comment by khalwat** [comment] 2020-10-07 12:47
What is the SEO Image set to? Where is that stored? S3 bucket? Someone else saw issues where they had their bucket or some setting to their bucket set to the wrong zone, which caused slowdowns/errors in the image transforms.

Can I have a live URL where I can look at the site?

What caching method are you using?

To go further, we are almost certainly going to have to do some kind of pairing to look at what's going on, which includes access to the server, and working with the devops engineers in charge of this (if that's not you).

**Comment by khalwat** [comment] 2020-10-07 12:50
What this all _sounds to me_ like is that the rendering of the JSON-LD container is not being cached. An uncached render can be a little slow, only because there are so many properties that need to be parsed.

However, some of the times here sound excessive even for that, which makes me wonder if the issue isn't also something related to the SEO images and transforms that are going on.

The more profiling and narrowing down you can do the better.

**Comment by khalwat** [comment] 2020-10-07 19:29
@lukebailey @3dgroup @leehaskings if any of you want to try screen sharing, hit me up on Discord at **andrew.welch** and we can work out a day and time to look into this a little deeper.

Ideal would be if you can reproduce it on local dev (maybe by changing the `ENVIRONMENT` variable or such), but staging works too.

**Comment by baileydoestech** [comment] 2020-10-09 09:48
Thanks @khalwat I will be available the week of 19th if nobody else is free before then to help diagnose

**Comment by khalwat** [comment] 2020-10-20 16:47
I'm available all week @lukebailey -- just hit me up!

**Comment by jhealey5** [comment] 2020-10-29 13:56
Just a bump on this, we've just noticed this same problem on one of our clients production sites, since then we've checked multiple other client sites, on multiple environments/versions and the issue is consistent. The only one of our sites that didn't have this issue was a much older site on Craft 3.43 and SeoMatic 3.2.13. All of our sites use s3, some use template caching,  some use blitz and some don't have any.

Incrementally updating the versions shows the problem begins with 3.3.15.

3.3.15: ![image](https://user-images.githubusercontent.com/1771431/97582301-7b35d080-19ed-11eb-98f0-727ea3668ba0.png)

3.3.14: 
![image](https://user-images.githubusercontent.com/1771431/97582375-943e8180-19ed-11eb-9f66-1aa456e80156.png)

**Comment by khalwat** [comment] 2020-10-29 14:11
So that's pretty interesting, and to me point to this commit @jhealey5 https://github.com/nystudio107/craft-seomatic/commit/f58e42167d326c875d8e06366bb4620dd87a97d3

**Comment by khalwat** [comment] 2020-10-29 15:34
So I've reverted the above commit: https://github.com/nystudio107/craft-seomatic/commit/54556f2b9f3694f55732fe10d0d585b2bb2b5432

To use it, change your semver to this:
```
    "nystudio107/craft-seomatic": "dev-develop as 3.2.23",
```

This very well may fix the issue, but it doesn't make sense to me because we're asking the Assets Service for the transformed image, but if the transform has already been done, it should immediately return it.

So even if the first transform is a little slow because it's happening for a remote volume, and the image needs to be downloaded and cached locally, subsequent requests for this transformed image should be quick.

???

**Comment by khalwat** [comment] 2020-10-29 16:04
@andris-sevcenko

**Comment by baileydoestech** [comment] 2020-11-02 13:06
Deployed to our production site with the following results so this looks to have resolved the issue (maybe others can confirm)

**SEOMatic 3.3.22**
![image](https://user-images.githubusercontent.com/3185073/97870784-556d3c00-1d0b-11eb-934b-9f7f67411686.png)

**SEOMatic dev-develop**
![image](https://user-images.githubusercontent.com/3185073/97871399-5b175180-1d0c-11eb-911e-2159d6486214.png)

**Comment by baileydoestech** [comment] 2020-11-09 17:16
If nobody else has comment can the fix make it into a 'proper' release? (conscious of having dev-develop running on production)

**Comment by khalwat** [comment] 2020-11-09 17:29
I know that this is what the problem was; but it doesn't make sense to me _why_ -- but that's from me no understanding what is going on under the hood.

@andris-sevcenko might know better, the code is here: https://github.com/nystudio107/craft-seomatic/blob/develop/src/helpers/ImageTransform.php#L122

It's either being slowed down by:

`$volume->fileExists($asset->getPath())`

or by:

`$url = $assets->getAssetUrl($asset, $transform, $generateNow)`

The latter makes the most sense to me, but if the transform has already been made, I would assume the operation would be very inexpensive.

**Comment by qrazi** [comment] 2020-11-12 15:21
It very much looks like we have this issue too. I'll try using the dev branch to see if it resolves for us as well

**Comment by khalwat** [comment] 2020-11-12 15:50
I will cut a release today.

**Comment by qrazi** [comment] 2020-11-16 17:02
OK, trying to dive deep into SEOMatic profiling on my local dev running a rickity Docker setup was not the smartest... 😬 

On our staging environment I can confirm that the fix scheduled for 3.3.23 brings down the processing times, from:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/7550540/99283567-7b2f3080-2835-11eb-9594-ae7558a91700.png"> 

to:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/7550540/99283605-86825c00-2835-11eb-8474-b7c1d14d37fb.png"> (yup, some heavy queries are next to be removed).

Some extra info; running Craft CMS 3.5.15.1, SEOMatic 3.3.22, S3 bucket for all Volumes, CloudFront CDN, Imager for image transforms (but SEOMatic uses native transforms and Imager is not configured to handle native transforms as, so I don't expect this to matter).

**Comment by khalwat** [comment] 2020-11-18 16:56
Released in https://github.com/nystudio107/craft-seomatic/releases/tag/3.3.23

**Closed as completed by khalwat** 2020-11-18 16:56 UTC
Labels: question
