### ISSUE TITLE
Page can't be excluded from sitemap

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#184] opened 2018-07-27 17:11 UTC
I don't know if this is the same as #172, but I'm facing a similar issue.

I have a Page of a "Search" Entry type. In the entry's sitemap tab I have all options unchecked, yet the page is still included in my sitemap.

**Comment by khalwat** [comment] 2018-07-28 01:22
Right this is a duplicate of #172

**Closed as completed by khalwat** 2018-07-28 01:22 UTC
