### ISSUE TITLE
Can't retrieve (GQL) or save (control panel) humans template

### ISSUE THREAD

**Issue by tremby** [nystudio107/craft-seomatic#1109] opened 2022-04-13 21:43 UTC
([Originally posted in the wrong repo](https://github.com/nystudio107/seomatic/issues/400))

### Describe the bug

I get an error when trying to retrieve or save the humans template.

### To reproduce
Steps to reproduce the behaviour:
1. Query via GQL for `seomatic { frontendTemplates { contents filename } }` or `seomatic { frontendTemplateContainer }`
2. See response, which has `Error rendering template string -> The "defined" test only works with simple variables in "__string_template__9d8842c587f4804bb2efb8391bf2419a" at line 4. ` where I expect the humans.txt content to be
3. Go to control panel -> SEOmatic -> global SEO -> humans
4. See default humans.txt template (which does not contain the string `defined` at all)
5. Without editing click to save
6. See error. It was partially obscured under the bottom of the text field when I took the screenshot below but when I try again now it is fully visible. `Error rendering template string -> The "defined" test only works with simple variables in "__string_template__9d8842c587f4804bb2efb8391bf2419a" at line 4. `

### Expected behaviour
When retrieving and an error takes place, I expect not to get a response at all, or for graphql errors to be produced, or to get an empty result. In fact, the string I expect to contain the humans.txt content has a string error message in it. This is bad since I might inadvertently serve this error message as the file.

When saving the humans.txt template I expect it to save properly with no error.

# Screenshots
![graphql query and response showing error message](https://user-images.githubusercontent.com/199635/163072275-ebbebe80-d928-467e-9644-361458d9216a.png)
![seomatic control panel showing error message hiding at bottom of text field](https://user-images.githubusercontent.com/199635/163072300-cf2ecd52-ec7b-4e5d-9ea3-a74080fa064d.png)

### Versions
- Plugin version: 4.x dev at a6aa50e
- Craft version: 4.0.x at 792e226

**Comment by khalwat** [comment] 2022-04-13 22:00
I'm unable to reproduce this. As you note, nowhere in the `Humans.txt` template does `defined` appear.

I'd suggest:

1. Updating to the latest version in `develop-v4` as that fixes the CSS overlap issue you noted
2. Clear all of your logs, and then make the issue happen, and then either look through the logs for anything more conclusive or post the logs here so I can do so

See video:


https://user-images.githubusercontent.com/7570798/163277499-2d072e1f-4da3-4507-867a-cf1ef006643d.mov

**Comment by tremby** [comment] 2022-04-13 23:43
Your template is different, and does not have `parseEnv` wrapped around `seomatic.site.creator.genericUrl`. I found that it is indeed the `parseEnv` line which causes the error.

I see it's still in the default template: https://github.com/nystudio107/craft-seomatic/blob/develop/src/templates/_frontend/pages/humans.twig -- maybe it's not meant to be?

**Comment by khalwat** [comment] 2022-04-13 23:52
oooooooh, good call!

Addressed in: https://github.com/nystudio107/craft-seomatic/commit/57088f5be33dda5ad8282a4c3e590b046b438e46 & https://github.com/nystudio107/craft-seomatic/commit/7d557fe485327404638071d46626ffe7deef8b70

It should be this, FWIW:

```twig
URL: {{ parseEnv(seomatic.site.creator.genericUrl ?? "n/a") }}
```

...with the null coalescing operator inside of the `parseEnv()` parameter list

**Closed as completed by khalwat** 2022-04-13 23:52 UTC
Labels: bug

**Comment by tremby** [comment] 2022-04-14 00:03
That doesn't look right to me -- say `...genericUrl` is null, what would `parseEnv("n/a")` do?

**Comment by khalwat** [comment] 2022-04-14 01:40
it would do nothing, and the text would be output as `n/a`

**Comment by tremby** [comment] 2022-04-14 01:54
Huh, weird. OK. Unexpected enough to me to dig, and that's documented in the source code but not in https://craftcms.com/docs/4.x/dev/functions.html#parseenv

Anyway, thanks very much for the fix.
