### ISSUE TITLE
og:image/twitter:image not being set in pages

### ISSUE THREAD

**Issue by XhmikosR** [nystudio107/craft-seomatic#178] opened 2018-07-23 19:05 UTC
So, if I have the setting Global -> Facebook/Twitter -> Facebook OpenGraph/Twitter Image Source set to "Same as SEO image", none of my pages have the image I have specified in Global -> General -> SEO Image Source.

I thought this setting was being inherited?

If I specify the same image in Global -> Facebook/Twitter then it's added.

Using v3.1.3.

**Comment by XhmikosR** [comment] 2018-07-23 19:14
BTW, this is another page a trailing slash is being added, but didn't notice before since my default image wasn't being added :)

**Comment by khalwat** [comment] 2018-07-23 22:46
Is it the same as this issue: https://github.com/nystudio107/craft-seomatic/issues/168

...where you have multiple entry types?

**Comment by khalwat** [comment] 2018-07-23 22:48
I'm unable to reproduce this. I have a custom SEO Image set in Global SEO:

![google chromescreensnapz1265](https://user-images.githubusercontent.com/7570798/43106917-ca1e77b0-8ea8-11e8-8af2-e8e1aff31c2a.png)

I see this reflected in both the Twitter image:

![google chromescreensnapz1266](https://user-images.githubusercontent.com/7570798/43106958-e3fc86fe-8ea8-11e8-9658-c4a8808d38d8.png)

...and the Facebook image:

![google chromescreensnapz1267](https://user-images.githubusercontent.com/7570798/43106974-f1a27a52-8ea8-11e8-895c-64f3c6724894.png)

Where exactly are you not seeing this image propagate to? Screenshots would help...

**Comment by khalwat** [comment] 2018-07-23 23:23
So this _was_ a bug in older versions of SEOmatic that were fixed in an update -- but to propagate the fix to the already installed version, you need to go to the Twitter and Facebook pages, and click on Save.

Can you try this and confirm things are still not working as expected?

**Comment by XhmikosR** [comment] 2018-07-24 11:46
Yup, that seems to be the cause. After I go to Facebook/Twitter options and set again to use the SEO image, and click Save, then it works with just the General image.

**Comment by XhmikosR** [comment] 2018-07-24 11:47
On the other hand, I don't see any preview but the image is being generated and added in the HTML.

**Comment by khalwat** [comment] 2018-07-24 12:50
What preview is missing? Screenshot?

**Comment by XhmikosR** [comment] 2018-07-24 12:56
Yup, the image shown int the Facebook/Twitter preview box. Could it be because I use an SVG image and have Transform enabled?

**Comment by khalwat** [comment] 2018-07-24 15:03
Ahhhhh yes sorry, you can't use SVGs for this unfortunately. That's exactly the problem.

**Closed as completed by khalwat** 2018-07-24 15:03 UTC
Labels: need info

**Comment by XhmikosR** [comment] 2018-07-24 17:18
You mean for the preview, right? Because with Transform enabled the SVG is correctly converted.

**Comment by khalwat** [comment] 2018-07-24 17:19
Hrm welp, I'll test it and see what happens. Somewhat surprised it worked at all :)

**Comment by khalwat** [comment] 2018-07-24 17:30
So this actually seemed to work fine in my test? I did have to click on Save for the Twitter settings for it to show up, but... my guess is that this is also broken for you because of the trailing slashes setting.

**Comment by XhmikosR** [comment] 2018-07-25 06:02
Yup :) I will try again after I update to the latest Craft which has the slash fix.

**Comment by XhmikosR** [comment] 2018-07-25 07:31
So, all good with the new Craft version: preview includes the image :D
