### ISSUE TITLE
use `baseCpUrl` instead of `siteUrl` when generating Social Media Preview

### ISSUE THREAD

**Issue by webrgp** [nystudio107/craft-seomatic#950] opened 2021-08-18 15:47 UTC
Hi Andrew!

I am working on that Craft / Gatsby project that has Craft running on `cms.example.com` and the Gatsby (Netlify) on `example.com`.

I have in the `config/general.php`:

```php
return [
    ...
    'baseCpUrl' => "cms.example.com",
    ...
];
```

And the $PRIMARY_SITE_URL set to `example.com`

Everything is working fine until I try to view **Social Media Preview** which returns:

`http://example.com/seomatic/preview-social-media?elementId=5&siteId=1` 

instead of 

`http://cms.example.com/seomatic/preview-social-media?elementId=5&siteId=1` 

If I manually add the `cms.` to the generated url, I get the preview.

I did some poking around the code and I tried change the bellow from `UrlHelper::siteUrl` to `UrlHelper::baseCpUrl` per [Craft's API Docs](https://docs.craftcms.com/api/v3/craft-helpers-urlhelper.html#method-basecpurl), but it didn't seem to work.

https://github.com/nystudio107/craft-seomatic/blob/cc764149969d99ef396e07d868ec56de9cf38316/src/Seomatic.php#L652-L660

Can you help?

**Comment by khalwat** [comment] 2021-08-25 03:56
Well, the problem is that the CP URL is for CP requests... but the social media preview is a frontend request.

Have you tried using the Site URL Override feature in SEOmatic? 

https://nystudio107.com/docs/seomatic/configuring.html#advanced-plugin-settings

**Comment by webrgp** [comment] 2021-08-26 14:33
I've tried to use your solution, adding `siteUrl` to the `seomatic.php` config file:

```php
<?php

use craft\helpers\App;
use nystudio107\seomatic\base\SeoElementInterface;

return [
    // The public-facing name of the plugin
    'siteUrl' => App::env('ADMIN_SITE_URL'),
];
```

But it still loading Craft's `siteUrl` instead. Did you mean to update the `siteUrl` in Craft?

**Comment by khalwat** [comment] 2021-08-26 15:26
No, I mean this setting:

https://github.com/nystudio107/craft-seomatic/blob/develop/src/config.php#L133

Which you can also set in the CP via SEOmatic -> Plugin Settings -> Advanced

**Comment by webrgp** [comment] 2021-08-26 16:11
Still not working. 

After fixing the config prop name, I can see it on SEOmatic -> Plugin Settings -> Advanced:

<img width="652" alt="Screen Shot 2021-08-26 at 12 07 29 PM" src="https://user-images.githubusercontent.com/994788/130997867-3431b79c-39cc-4270-832d-2f1ece174597.png">

But when I try using the preview, still goes to the Craft's `siteUrl`

**Comment by d--j** [comment] 2022-07-11 21:52
@webrgp when You are still have this problem, #1165 has a workaround for your problem.

**Comment by webrgp** [comment] 2022-07-12 14:00
Thanks for the tip! I've end up removing the hyphen from the calendar name.

**Comment by goraxan** [comment] 2023-11-28 14:25
@webrgp the reason why setting the "Site URL Override" has no effect on the social media URL is because the Seomatic.php file is importing the wrong UrlHelper (it's using the native `craft\helpers\UrlHelper` instead of `nystudio107\seomatic\helpers\UrlHelper`). Changing the import fixes it.

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/Seomatic.php#L38

cc @khalwat

**Comment by khalwat** [comment] 2023-11-28 14:40
@goraxan nice catch! Addressed in: https://github.com/nystudio107/craft-seomatic/commit/61f941efb3ffc81afc0c940e663b1ec63fc625f7 & https://github.com/nystudio107/craft-seomatic/commit/3ec9a31184b4d0abf65ca6d5d57717318e60a9e7

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.67”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.36”,
```
Then do a `composer clear-cache && composer update`

**Comment by goraxan** [comment] 2023-11-28 15:15
@khalwat I've reviewed it and it looks like the `elementId` and `siteId` query parameters are lost due to the https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/helpers/UrlHelper.php#L54 implementation, which ignores the `$params` variable if the `siteUrlOverride` is set.

**Comment by khalwat** [comment] 2023-11-28 20:15
If the `siteUrlOverride` is set, it's just going to use that, and that alone as the URL.

**Comment by goraxan** [comment] 2023-11-29 09:01
I don't understand how can we know what to preview if we don't receive the `elementId` nor the `siteId` params. I'll use the https://github.com/nystudio107/craft-seomatic/issues/1165 workaround then.

**Comment by khalwat** [comment] 2023-12-05 01:34
hmmmm... okay let me re-open this and look into it further. @goraxan you think passing along the params would do the trick for you?

**Comment by khalwat** [comment] 2023-12-05 03:15
@goraxan Addressed via: https://github.com/nystudio107/craft-seomatic/commit/6b317fcdc8490139b08fc6af241dd9d2055d0677 & https://github.com/nystudio107/craft-seomatic/commit/377badc26a67b9db54eb3f2998756b6f98182351

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.68”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.37”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2023-12-05 03:15 UTC
