### ISSUE TITLE
Sitemap priority in content SEO settings stuck at 0.5 for every entry.

### ISSUE THREAD

**Issue by jonlongnecker** [nystudio107/craft-seomatic#871] opened 2021-04-21 17:52 UTC
### Describe the bug
After  upgrading a site from Craft 2 to Craft 3 (and Seomatic as well), I'm noticing that setting a sitemap priority in Content SEO for each section isn't "sticking" when editing or creating an entry tied to that Content SEO.

For example, I've set main content pages to a 0.9 sitemap priority, and recreated new seomatic fields for overrides to match the existing content already created. But after setting that up, while the other content is inherited properly, all the entires inherited a 0.5, and even creating new entries has the 0.5 priority chosen by default instead of 0.9.

The sitemap itself is also setting the 0.5 priority in the xml file.

This is happening on all entries with Content SEO set and corresponding SEO Custom Field attached to that section's entries.

I've resaved the Content SEO settings, the section settings, cleared SEOmatic caches, and set the environment to live to make sure all SEO content is being rendered.

Feels like something is stuck somewhere from the previous version of SEOmatic, and I'd rather not go through hundreds of entries and manually update the sitemap priority. Or have to explain to the client that each new entry has to be manually changed to a higher sitemap priority.

How can I get the sitemap priority to apply to these entries properly?

### Expected behaviour
When setting the sitemap priority on an SEO Content section and matching it with a SEOmatic custom field, the global settings should reflect what was set, and not default to a different number.

### Screenshots
![Screen Shot 2021-04-21 at 10 50 12 AM](https://user-images.githubusercontent.com/2390/115598651-7dd3fd00-a28f-11eb-83e9-0515d3de4b9a.png)
![Screen Shot 2021-04-21 at 10 49 52 AM](https://user-images.githubusercontent.com/2390/115598656-7f052a00-a28f-11eb-9a79-eab1c5ed7dce.png)

### Versions
- Plugin version: 3.3.40
- Craft version: 3.6.12

**Comment by khalwat** [comment] 2021-04-21 18:04
If I had to guess, it's likely because you had an old SEOmatic Meta field on Craft 2.x that had the `0.5` sitemap priority in it, that is being set in the Craft 3 SEO Settings field.

Content SEO settings are respected as defaults, but if the SEO Settings field has a higher priority in it, it wins. That's how the override cascade works.

Your options are:

1) Delete any old SEOmatic Meta fields that contain sitemap priority information before the migration

2) Manually change each entry

**Comment by jonlongnecker** [comment] 2021-04-21 18:42
I just followed the instructions for migrating to keep the old SEOmatic fields to help with copying content over. And I'm way too deep in to fixing all the things that didn't actually copy over to re-start the migration at this point. 

Even after deleting the old SEOmatic fields all new entries still default to the 0.5 sitemap priority. Surely there's a way get this old value "unstuck?" I don't see a global sitemap priority setting in the CP anywhere that would be overriding Content SEO settings.

FYI, have cleared caches, resaved sections hoping it would help. No luck so far.

**Comment by jonlongnecker** [comment] 2021-04-21 18:52
Also, the Craft 2 site is still live and I've gone back to see if there's even a way to set the sitemap priority in the Craft 2.x version. SEOmatic didn't even do sitemaps then? I can't find anywhere in either the Add-on settings or custom field settings that would let me dictate a sitemap priority number...

**Comment by khalwat** [comment] 2021-04-21 21:20
hmmmmm. We might need to have a look together via screenshare

**Comment by khalwat** [comment] 2021-04-24 04:29
Confirmed the issue here, no need to screenshare.

**Comment by khalwat** [comment] 2021-04-28 15:54
Addressed in https://github.com/nystudio107/craft-seomatic/commit/8d18598c9d4caaebc1015df5265d2532a66c709f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.3.41”,
```
Then do a `composer clear-cache && composer update`

N.B.: this will not change the setting for exiting entries that have saved SEO Settings values in them. But it will change it for any new entries that are created.

**Closed as completed by khalwat** 2021-04-28 15:54 UTC
Labels: bug
