### ISSUE TITLE
after installing the plugin get an error in Global SEO config for Twitter

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-seomatic#272] opened 2018-11-19 21:27 UTC
[
<img width="1356" alt="screen shot 2018-11-19 at 16 24 08" src="https://user-images.githubusercontent.com/25344867/48735928-bdf2a980-ec17-11e8-8127-bad29f64c525.png">
](url)

**Comment by khalwat** [comment] 2018-11-19 22:38
So this is after first installing the plugin fresh into an existing Craft install?

**Comment by ghost** [comment] 2018-11-19 23:40
yep, actually not a big deal because for some reasons this only happens in local/ homestead environment. It's fine in staging and prod. I didn't even get a chance to input twitter handle. Anyway, purchased the plugin, it's fantastic, super pro, like everything you do. Thanks

**Comment by khalwat** [comment] 2018-11-19 23:42
Perfect, I'll try reproducing that here!

**Comment by ghost** [comment] 2018-11-19 23:45
I wouldn't worry too much. In my homestead vagrant setup I get weird fatal errors in the cP, like if I install plugins or upgrade craft. Sent logs to Brad. Got the latest homestead vagrant versions. So i stick to installs and upgrades in composer. This might not have anything in common, but homestead has these weird quirks in Craft CP...

**Comment by ghost** [comment] 2018-11-19 23:46
works all great on my VPS

**Comment by khalwat** [comment] 2018-11-20 01:58
@neachtan109 is there any chance that you didn't run `composer update` in your local dev environment? 

I've looked at the code, and I'm not seeing anything else that would explain what you're seeing?

**Comment by ghost** [comment] 2018-11-20 12:40
I installed the plugin via composer require, I run update now and again for specific reasons.

**Comment by aarmitage** [comment] 2018-11-21 09:21
We've seen this too, also in a dev environment on a staging Digital Ocean/ServerPilot box.

The issue for us seems to be the presence of an SEO image. Steps to reproduce were:

1. Go to Content SEO
2. Choose a section
3. Choose SEO image source (transform mode set to crop)
4. Save
5. See exactly the same error as above
6. Return to Content SEO - that section now shows as having an image, but clicking into it shows the error in 5

We've run `composer update` but this hasn't resolved the issue.

**Comment by khalwat** [comment] 2018-11-21 11:22
Thanks @aarmitage that's helpful, I'll try to reproduce it.

**Comment by khalwat** [comment] 2018-11-21 11:27
I tried those STR @aarmitage but I'm not seeing the error -- do you have any relevant logs you can give me?

**Comment by aarmitage** [comment] 2018-11-21 13:10
Can't see anything to be honest. No php errors - sorry.

**Comment by sjadema** [comment] 2018-11-21 20:18
I have the same problem with the steps followed by https://github.com/nystudio107/craft-seomatic/issues/272#issuecomment-440593282 with the exception that I didn't alter the image crop settings, i just changed the JsonLd type and saved the page.

I tried setting the `$transformName` parameter of `\nystudio107\seomatic\services\Helper::socialTransform()` to an empty string when it's `null`. After that i get the same error but on a different method `\nystudio107\seomatic\services\Helper::socialTransformWidth()`, here the `$transformName` parameter is `null` as well.

The data structure in the records is quite complex so it's difficult to do more research.

**Comment by khalwat** [comment] 2018-11-21 22:51
My kingdom for a reproducible case! :)

**Comment by khalwat** [comment] 2018-11-22 02:51
Those of you who are able... change the version to `dev-develop` and see if what I pushed to `develop` fixes the issue for you.

I still don't fully understand what is happening, but this should at least cause it fall back on a sane default, rather than throwing an exception.

**Comment by nettum** [comment] 2018-11-22 10:03
Hi Andrew!  
I got the same exception after changing the twitter and facebook image settings for a section.  
I previously had it to "Same as SEO image":  
![image](https://user-images.githubusercontent.com/798156/48895233-e4e1f300-ee44-11e8-8390-eb6e1f563742.png)

After changing it to "From Asset Field" and choosing a required asset field like this:  
![image](https://user-images.githubusercontent.com/798156/48895352-27a3cb00-ee45-11e8-8371-6b909810de36.png)  
I get the same error:  
![image](https://user-images.githubusercontent.com/798156/48895584-b9133d00-ee45-11e8-9769-30e07cfeff7d.png)

This only happens if the section I'm enabling it for has any content (and yes, all entries on that section has an required image attached - in my case from aws s3).

I will try switch to `dev-develop` to see if that helps.

**Comment by nettum** [comment] 2018-11-22 10:13
Error slighty changed after update to develop branch (3e07b08), now for `socialTransformWidth` method:
![image](https://user-images.githubusercontent.com/798156/48895932-a1888400-ee46-11e8-8c50-3939d7b03900.png)

Same case for `socialTransformHeight`.

**Comment by nettum** [comment] 2018-11-22 10:18
If I remove the type hinting and do the same if check in `socialTransformWidth` and `socialTransformHeight` it seems to work (at least I'm not getting the exception anymore).

**Comment by khalwat** [comment] 2018-11-22 14:37
Thanks @nettum -- I'll check that out!

**Comment by khalwat** [comment] 2018-11-22 18:21
@nettum I just pushed another change to `dev-develop` if you're able to try? Sorry to do the go-around like this with you, but I am unable to reproduce this locally.

**Comment by nettum** [comment] 2018-11-22 18:42
No worries :)   
Did the same change before checking out dev-develop and then still got the `Argument 2 passed to nystudio107\seomatic\services\Helper::socialTransform() ` error.   
Upgraded to `dev-develop 673632f`, did a refresh and now it's working.
:+1: 

Maybe not related and I may misunderstand something, but checking just in case:  

Shouldn't the change I just did in "SEOmatic" -> Section -> "Content SEO" -> "Faceook" like this:
![image](https://user-images.githubusercontent.com/798156/48918523-75dcbc80-ee8d-11e8-8555-4c9df0144476.png)

be reflected on the article (where I have an SEO Settings field where I can override the fields). It still says "Same as SEO image": 
![image](https://user-images.githubusercontent.com/798156/48918632-2ba80b00-ee8e-11e8-84c1-f280db579a8c.png)

Anyway, the fix for the error seems to work!
Would appreciate if someone else also would do a quick check as I had to do this in a hurry (have more time tomorrow)

**Comment by khalwat** [comment] 2018-11-22 18:45
Glad that's fixed for you... still doesn't make sense to me, I can't see where the `null` value could be coming from.

As for the other question, this is a UX/UI issue with with the SEO Settings field, not a bug. The SEO Settings field _overrides_ whatever the Global/Content SEO settings are. So it has its own unique value; if it's empty, it falls back on the Global/Content SEO settings.

c.f.: https://github.com/nystudio107/craft-seomatic/issues/248

**Comment by khalwat** [comment] 2018-11-22 18:50
Fixed in 3.1.33 https://github.com/nystudio107/craft-seomatic/releases/tag/3.1.33

**Closed as completed by khalwat** 2018-11-22 18:50 UTC
Labels: bug

**Comment by aarmitage** [comment] 2018-11-22 18:53
Updated and working here too - thanks Andrew.
