### ISSUE TITLE
Inconsistent Tracking Script Includes Caused by Caching Issues.

### ISSUE THREAD

**Issue by curtismorte** [nystudio107/craft-seomatic#1214] opened 2022-09-26 19:56 UTC
### Describe the bug
When using SEOMatic and Blitz cache on a Craft site, tracking include scripts (HubSpot & GTM) are "Inconsistently" added to the page. We use the built in tracking script includes to add scripts to the `<head>` based on configuration within the control panel.

What I mean by "Inconsistent", is that if I clear all cache within Craft using the utilities, and visit any entry URL, I am able to have my tracking scripts included on the page for HubSpot and GTM. It's sometime after this that the problem ensues.

In particular, I tend to notice the issue right away when I go to run Blitz Cache for static site generation. This is because none of the HTML files that are produced by Blitz contain tracking code for either HubSpot or GTM. If I go to visit any page after I run Blitz, while being logged into the control panel so I don't access a cached page, the page which is returned by Craft no longer contains tracking scripts (yes, I've verified that I am not getting a cached page).

**I've tracked this issue down to the following place:**
https://github.com/nystudio107/craft-seomatic/blob/66e372d0ddcbb162529872cc28c0e6cf95577f3c/src/models/MetaScriptContainer.php#L64-L103

> When my entries have their includes added, the value for `$tagData` is defined. When I am missing script includes for entires, the value for `$tagData` is an empty array.

**Please note that is issue is an all of nothing issue meaning that either the script includes are added for all entries, or the script includes are not added for all entries.**

I've tested this with simple file caching with Craft, and the Redis Caching with Craft. Both caching mechanisms have the same problem. I've also been able to produce this same problem across multiple different environments of the same site, so I know it's not environment specific. We've been experiencing this issue for our production sites for about 2 weeks now. Prior to then it was not a problem.

I feel like this could be contributed potentially to core Craft, as `getOrSet` should always return cache values, however the callable function for setting values is defined by the codebase here, so that's why I am submitting a bug request to you.

### To reproduce
1. Setup local environment to use redis cache
2. Enable GTM tracking script include for SEOMatic
3. Go to utilities clear all SEOMatic cache.
4. Load any entry page and verify that the tracking script is included
5. Generate Blitz cache
> Notice Blitz cache HTML files don't have the tracking script included.

### Expected behaviour
Tracking scripts should be able to be included for dynamically generated content (user requests a page that is returned by Craft) and by Blitz.

### Versions
- Plugin version: 4.0.8
- Craft version: 4.2.5.1

**Comment by khalwat** [comment] 2022-09-26 20:13
Are you able to reproduce this issue at all with Blitz completely out of the picture (ie, uninstalled)?

**Comment by khalwat** [comment] 2022-09-26 20:43
It sounds to me like the metadata is getting cached when it's in a state where SEOmatic thinks it should not render the script tags

So whenever the metadata is being rendered, the state of the environment or devMode is wrong, so it never renders the tracking scripts, and it caches that data. Then the next time it requests that data, it pulls it from the cache.

Thus clearing the cache causes it to "work" again, because now the environment and/or devMode is what it should be for production, and it works

How or why this is happening, I have no idea... but it's going to have something to do with your environment and/or deployment process most likely

**Comment by bencroker** [comment] 2022-09-26 21:05
> 5. Generate Blitz cache

How exactly are you generating the cache and is the HTTP Generator being used?

**Comment by curtismorte** [comment] 2022-09-27 00:44
I am working on getting you both the details. I will update shortly.

**Comment by curtismorte** [comment] 2022-09-27 01:20
@khalwat, disabling Blitz solves the problem. So it's likely safe to say that the local generator from Blitz is the culprit. To be clear, I see now that this is technically an issue that happens from Blitz, which affects SEOMatic. Let me know if we need to move this over to the Blitz repository, or if we can work here?

@bencroker, what @khalwat mentions here https://github.com/nystudio107/craft-seomatic/issues/1214#issuecomment-1258611315 is also what I think is the case. When Blitz is enabled, I can get Blitz to properly cache a page (which includes the script includes) by visiting any URL for the site. However, if I use the local generator, the pages are generated, but they don't have the script includes that are normally placed there by SEOMatic. I feel like something is missing from the local generator which is causing Craft to think that it's not running in a production environment while you're generating all of the static files. Thus, tricking SEOMatic into thinking "hey I shouldn't be adding tracking scripts to sites that don't require it".

**My environment settings are:**
- The environment variable `ENVIRONMENT` set to "production" 

**The Relevant parts of SEOMatic:**
```php
return [
   '*' => [

       // Should SEOmatic render metadata?
       'renderEnabled' => true,

       // Should SEOmatic add to the http response headers?
       'headersEnabled' => true,

       // Whether the environment should be manually set, or automatically determined
       'manuallySetEnvironment' => true,

       // The server environment, either `live`, `staging`, or `local`
       'environment' => 'local',

       // Should the meta generator tag and X-Powered-By header be included?
       'generatorEnabled' => true,

       // SEOmatic uses the Craft `siteUrl` to generate the external URLs.  If you
       // are using it in a non-standard environment, such as a headless GraphQL or
       // ElementAPI server, you can override what it uses for the `siteUrl` below.
       'siteUrlOverride' => '',

       // The duration of the SEOmatic meta cache in seconds. Null means always cached until explicitly broken
       // If devMode is on, caches last 30 seconds.
       'metaCacheDuration' => null,

       // Determines whether the meta container endpoint should be enabled for anonymous frontend access
       'enableMetaContainerEndpoint' => false
   ],
   'dev' => [
   ],
   'staging' => [
       'environment' => 'staging',
   ],
   'production' => [
        'environment' => 'live'
    ],
];

```

**The Relevant parts of Blitz:**
```php
return [
    '*' => [
        'debug' => false,
        'cachingEnabled' => true,
        'queueJobTtr' => 600,
        'refreshMode' => 2,
    ],
    'dev' => [
        'debug' => true,
        'cachingEnabled' => false,
    ],
    'staging' => [
    ],
    'production' => [
    ],
];
```
> We store other parts of Blitz settings in project yaml files. The main thing is that use the local generator and file storage.

**Comment by bencroker** [comment] 2022-09-27 07:15
You didn't answer my question above, but from what you're reported, this is likely caused by an issue with the Local Generator. Switching to the HTTP Generator should solve this for you, while I look into the issue and work on a fix.

**Comment by bencroker** [comment] 2022-09-27 07:34
I just ran a local test using the Local Generator with `ENVIRONMENT=production` and it worked fine, the tracking script appears where I'd expect it to. Are you running the latest version 4.2.2 of Blitz?

![Screenshot 2022-09-27 at 09 35 33](https://user-images.githubusercontent.com/57572400/192463246-05ce9c1e-ba41-4d8f-935d-4f3fe8626762.png)

**Comment by curtismorte** [comment] 2022-09-27 14:17
@bencroker were running the latest version (4.2.2).

I'll look into this again today with some different ways of testing that I thought of so I can provide more feedback to you.

**Comment by khalwat** [comment] 2022-09-27 17:38
Will close this then -- happy to help out in any way I can.

**Closed as completed by khalwat** 2022-09-27 17:38 UTC
Labels: bug
