### ISSUE TITLE
Environment variable not parsed in some areas of ld+json

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-seomatic#811] opened 2021-01-15 11:45 UTC
I noticed that in the ld+json output for a commerce product some parts do not parse environment variables and instead insert the literal variable.

An example of this issue can be seen at https://www.fluffycarpets.com/carpets/london-silk-stone

### Versions
- Plugin version: 3.3.29
- Craft version: Pro 3.5.17.1
- Commerce version: 3.2.14

**Comment by karensg** [comment] 2021-01-16 10:51
I noticed the same thing. The autosuggest in the Admin Panel looks broken too. The problem seems to be there for all environment variables. I noticed it when I try to use $GTM_ID.

**Comment by khalwat** [comment] 2021-01-20 22:36
That's really odd, this was addressed in: https://github.com/nystudio107/craft-seomatic/blob/v3/CHANGELOG.md#3328---20201222

**Comment by khalwat** [comment] 2021-01-20 22:36
@karensg screenshot of this broken Admin Panel UI?

**Comment by karensg** [comment] 2021-01-21 10:42
Actually, the variable seems to work. Just the auto-suggestion seems broken. This is what I see in the relevant source code:
```
var data = {
  query: '',
  selected: '',
  filteredOptions: [],
  suggestions: [
    {
      label: 'Environment Variables',
      data: [
        { name: '$CONTENT_LENGTH', hint: '' },
        {
          name: '$CONTENT_TYPE',
          hint: ''
        },
        { name: '$DOCUMENT_ROOT', hint: '/home/forge/<removed>/app/web' },
        {
          name: '$DOCUMENT_URI',
          hint: '/index.php'
        },
        { name: '$FCGI_ROLE', hint: 'RESPONDER' },
        {
          name: '$GATEWAY_INTERFACE',
          hint: 'CGI/1.1'
        },
        { name: '$HOME', hint: '/home/forge' },
        { name: '$HTTPS', hint: 'on' },
        {
          name: '$HTTP_ACCEPT',
          hint:
            'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
        },
        { name: '$HTTP_ACCEPT_ENCODING', hint: 'gzip, deflate, br' },
        {
          name: '$HTTP_ACCEPT_LANGUAGE',
          hint: 'en-US,en;q=0.9,nl-NL;q=0.8,nl;q=0.7,ru-RU;q=0.6,ru;q=0.5,es-ES;q=0.4,es;q=0.3,fr;q=0.2'
        },
        {
          name: '$HTTP_COOKIE',
          hint: '<removed>'
        },
        { name: '$HTTP_HOST', hint: '<removed>' },
        {
          name: '$HTTP_SEC_CH_UA',
          hint: '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"'
        },
        { name: '$HTTP_SEC_CH_UA_MOBILE', hint: '?0' },
        {
          name: '$HTTP_SEC_FETCH_DEST',
          hint: 'document'
        },
        { name: '$HTTP_SEC_FETCH_MODE', hint: 'navigate' },
        {
          name: '$HTTP_SEC_FETCH_SITE',
          hint: 'none'
        },
        { name: '$HTTP_SEC_FETCH_USER', hint: '?1' },
        {
          name: '$HTTP_UPGRADE_INSECURE_REQUESTS',
          hint: '1'
        },
        {
          name: '$HTTP_USER_AGENT',
          hint:
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36'
        },
        { name: '$PHP_SELF', hint: '/index.php' },
        {
          name: '$QUERY_STRING',
          hint: ''
        },
        { name: '$REDIRECT_STATUS', hint: '200' },
        {
          name: '$REMOTE_ADDR',
          hint: '<removed>'
        },
        { name: '$REMOTE_PORT', hint: '58530' },
        {
          name: '$REQUEST_METHOD',
          hint: 'GET'
        },
        {
          name: '$REQUEST_URI',
          hint: '/administrator/seomatic/tracking/googleTagManager/en'
        },
        {
          name: '$SCRIPT_FILENAME',
          hint: '/home/forge/<removed>/app/web/index.php'
        },
        { name: '$SCRIPT_NAME', hint: '/index.php' },
        {
          name: '$SERVER_ADDR',
          hint: '<removed>'
        },
        { name: '$SERVER_NAME', hint: '<removed>' },
        {
          name: '$SERVER_PORT',
          hint: '443'
        },
        { name: '$SERVER_PROTOCOL', hint: 'HTTP/2.0' },
        {
          name: '$SERVER_SOFTWARE',
          hint: 'nginx/1.18.0'
        },
        { name: '$USER', hint: 'forge' }
      ]
    }
  ],
  id: 'vars-googleTagManagerId-autosuggest',
  inputProps: {
    class: 'text fullwidth',
    initialValue: '$GTM_ID',
    style: '',
    id: 'scripts-googleTagManager-vars-googleTagManagerId',
    name: 'scripts[googleTagManager][vars][googleTagManagerId]',
    size: '',
    maxlength: '',
    autofocus: false,
    disabled: false,
    title: '',
    placeholder: ''
  },
  limit: 5
};
```

**Comment by khalwat** [comment] 2021-01-21 13:25
@karensg can you give me a screenshot of what the UI looks like when it is broken in this manner?

**Comment by karensg** [comment] 2021-01-21 13:56
Looks like this:
![image](https://user-images.githubusercontent.com/359682/105360195-a1d46380-5bf8-11eb-9530-ff4ef145fbb0.png)
![image](https://user-images.githubusercontent.com/359682/105360344-c6304000-5bf8-11eb-8f7e-ff0dba258b36.png)

**Comment by khalwat** [comment] 2021-01-21 15:01
@karensg are you 100% sure that you actually have a `GTM_ID` environment variable set in your `.env` file? Because from the dump you showed, it doesn't look like you do.

That would cause it to then not show up in the auto-complete list.

**Comment by khalwat** [comment] 2021-01-21 15:01
@fantasticmachine can you verify for me? I'm unable to reproduce the issue you're mentioning on the latest version of SEOmatic.

**Comment by peteeveleigh** [comment] 2021-01-21 15:46
@khalwat Yep can verify it's still there and everything is updated to the latest versions.
I don't know if you saw the other issue I raised around the same time about items showing as Out Of Stock. That one seemed to be resolved by me simply visiting the settings pages. However I can't seem to sort this one the same way. Have also tried clearing all caches to no avail.
 
Here's the "offers" section of the LD+JSON from one of the site's product detail pages. It seems to be parsing the $SITE_URL environment variable OK elsewhere in the JSON.

`"offers":{"@type":"Offer","availability":"http://schema.org/InStock","offeredBy":{"@id":"$SITE_URL#identity"},"price":"79.00","priceCurrency":"GBP","seller":{"@id":"$SITE_URL#identity"},"url":"https://www.fluffycarpets.com/carpets/london-silk-stone"},"`

The full LD+JSON (that the above is taken from) can be seen at https://www.fluffycarpets.com/carpets/london-silk-stone

This site was an update from Craft 2 to 3 and consequent SEOMatic updates so perhaps is something to do with that?

EDIT: Also seems to fail parsing $SITE_URL in the "Organisation" section. Both nodes are labelled "@id" (if that has any bearing). Elsewhere the URL seems to be injected correctly (the site url is shown as one would expect)

**Comment by khalwat** [comment] 2021-01-21 15:50
Yeah so that's actually fine @fantasticmachine -- I know it looks weird, but it's just an identifier. You're right that in this specific place it's not expanding the environment variable, but that's due to a limitation on how environment variables work.

SEOmatic adds a hash to whatever your `SITE_URL` is to identify it. The problem is, environment variables can't have any additional text in them if you want them to be parsed.

But it doesn't matter, because the `@id` is just an internally used ID to identify a blob of JSON-LD, it isn't used by Google for anything. I know it looks weird, but it's totally fine.

**Closed as completed by khalwat** 2021-01-21 15:50 UTC
Labels: bug

**Comment by karensg** [comment] 2021-01-21 16:12
Yes, very sure. The variable even works. It is not important or something, just wanted to flag it. It is okay to close the issue.

**Comment by khalwat** [comment] 2021-01-21 16:30
@karensg you can open a separate issue if you like -- yours is going to be a very different problem.

Craft CMS is what presents the UI for the `.env` variable auto-complete, so if it's not showing a particular variable, it's going to very likely be a Craft CMS issue.

**Comment by khalwat** [comment] 2021-01-21 16:32
How are you setting the `GTM_ID` variable @karensg ? If you're setting it in some way _other_ than directly in the `.env` file, I think Craft CMS doesn't pick it up.

ie, if you're setting it via Nginx config or via Docker or some other method of injecting it, Craft CMS just will not pick up on it, and present it in the auto-complete UI.

**Comment by karensg** [comment] 2021-01-22 16:06
I checked other plugins and they actually had the same issue. Found out what the problem was:
https://github.com/craftcms/cms/issues/5984
Fixed by updating `web/index.php` and `craft` from the latest build.

Thanks for thinking along!
