### ISSUE TITLE
SEOmatic is overriding the target URL of the Entry's Share button

### ISSUE THREAD

**Issue by romainpoirier** [nystudio107/craft-seomatic#684] opened 2020-07-09 08:41 UTC
### Describe the bug
After updating from 3.2.41 to 3.3.8, SEOmatic is now overriding the target URL of the Entry's Share button. This button now redirects to a `seomatic/preview-social-media?elementId={id}&siteId={id}` URL which shows the SEO preview instead of the Entry's URL. Obviously, this happens on entries which have a URL.

The same kind of error happens when trying to get the Preview mode of the Entry. The splitted screen on the right shows the SEO preview instead of the Entry.

### To reproduce
Steps to reproduce the behaviour:
1. Go to an Entry page (`/admin/entries/{section}/{id}-{slug}`)
2. Click on the Share button
3. See the opened page

### Expected behaviour
The Share button should open the Entry URL in a new window.

### Screenshots
![Share button](https://i.imgur.com/EQAqera.png)

### Versions
- Plugin version: 3.3.8
- Craft version: Craft Pro 3.4.27

**Comment by cherrykoda** [comment] 2020-07-12 15:21
I am experiencing the same issue, where the Share button and Preview pane are not working as intended.

### **To reproduce**
Steps to reproduce the behaviour:

1. Go to an Entry page (/admin/entries/{section}/{id}-{slug})
2. Click on the Preview Page
3. See the opened page

### **Expected behaviour**
The Preview button should open the entry preview, with the dropdown for viewing the template or the SEO previews.

### **Screenshots**

![image](https://user-images.githubusercontent.com/3789834/87250190-41868d00-c431-11ea-854e-546bcf9a1d7c.png)

### **Versions**
Plugin version: 3.3.8
Craft version: Craft Pro 3.4.24

**Comment by richcoopa** [comment] 2020-07-13 12:55
Is there an ETA on the fix for this issue? It's affecting our clients' websites and they are losing faith in SEOmatic rapidly.

**Comment by romainpoirier** [comment] 2020-07-13 12:58
@richcoopa, maybe you can try to downgrade if this is very urgent?

**Comment by richcoopa** [comment] 2020-07-13 13:21
That's a good idea @romainpoirier, but no idea in which version this bug was introduced.

**Comment by cherrykoda** [comment] 2020-07-13 13:30
@richcoopa I think it's the latest 3.3.8 try the previous version as I was fine until my latest update on a build cycle.

**Comment by jules1091** [comment] 2020-07-13 14:35
I am experiencing the same issue with the share and the preview button!

**Comment by khalwat** [comment] 2020-07-14 23:51
@richcoopa I'm sorry to hear that they are losing faith rapidly in SEOmatic.

I don't believe this is a bug in SEOmatic; here it is working as expected with version 3.3.10 on the latest version of Craft:

<img width="442" alt="Screen Shot 2020-07-14 at 7 45 09 PM" src="https://user-images.githubusercontent.com/7570798/87487094-c37dde00-c60a-11ea-85ba-5fa2e3f5e9ca.png">

I believe this actually was a result of an update to Craft CMS that resulted in you having no default **Preview Targets**. See:

https://github.com/craftcms/cms/issues/5535
https://github.com/craftcms/cms/issues/5519
https://github.com/craftcms/cms/issues/5844

Since you have no default preview targets, SEOmatic is then the only target, so it appears when you click on Preview.

To fix this, add preview targets by going to Settings -> Sections (click on a Section) and then add **Preview Targets** here:

<img width="1215" alt="Screen Shot 2020-07-14 at 7 45 33 PM" src="https://user-images.githubusercontent.com/7570798/87487481-c200e580-c60b-11ea-852e-1125aa31a6ee.png">

Let me know if you have further issues after creating the missing default Preview Targets

**Closed as completed** 2020-07-14 23:54 UTC
Labels: bug

**Comment by richcoopa** [comment] 2020-07-15 06:30
Thanks so much @khalwat !

**Comment by cherrykoda** [comment] 2020-07-15 17:18
@richcoopa seoMatic has been the best experience for my Craft 3 sites. It'll win your clients over once they get into full-swing. Best of luck!

**Comment by Rubenvandeven01** [comment] 2021-06-08 09:34
Thank you so much @khalwat. This was really helpful! :)

**Comment by arnout-poppr** [comment] 2023-11-29 12:05
Did the trick. Thanks!
