### ISSUE TITLE
"SEO Image Transform Mode" has no effect

### ISSUE THREAD

**Issue by lindseydiloreto** [nystudio107/craft-seomatic#428] opened 2019-06-25 23:34 UTC
Maybe I'm doing it wrong, but it doesn't appear that this field is actually doing anything... 

<img width="707" alt="Ω 2019-06-25 at 4 30 12 PM" src="https://user-images.githubusercontent.com/5309692/60140408-8bd59700-9766-11e9-89a4-da2b56f77d72.png">

It seems like whichever option I choose, the image just gets cropped...

**Twitter:**
<img width="595" alt="Ω 2019-06-25 at 4 27 48 PM" src="https://user-images.githubusercontent.com/5309692/60140416-91cb7800-9766-11e9-86ac-74e3da475430.png">

**Discord:**
<img width="457" alt="Ω 2019-06-25 at 4 25 05 PM" src="https://user-images.githubusercontent.com/5309692/60140425-9728c280-9766-11e9-95d7-0fea586ccb8b.png">

**Slack:**
<img width="598" alt="Ω 2019-06-25 at 4 31 28 PM" src="https://user-images.githubusercontent.com/5309692/60140460-c2131680-9766-11e9-9282-e84637095332.png">

Is this a bug? Or should I be selecting a different option?

---

SEOmatic: 3.2.9
Craft: 3.1.31

**Comment by khalwat** [comment] 2019-06-26 12:15
Looks like a duplicate of https://github.com/nystudio107/craft-seomatic/issues/358

Can you post this over there?

**Closed as completed by khalwat** 2019-06-26 12:15 UTC
