### ISSUE TITLE
Incorrect Image Dimensions for Twitter's "Summary Card with Large Image"

### ISSUE THREAD

**Issue by robmcfadden** [nystudio107/craft-seomatic#232] opened 2018-09-25 18:39 UTC
The Twitter card image is always generating at 800 x 800, which is correct for the "Summary Card" Twitter Card Type, but not for the "Summary Card with Large Image" size.

I believe the following line is not returning true when it should be...

https://github.com/nystudio107/craft-seomatic/blob/37052e99485e85911a693b7035a27c924646da26/src/helpers/PullField.php#L161

PHP 7.1.21
MySQL 5.7.23
Craft Pro 3.0.24
SEOmatic 3.1.20

**Comment by khalwat** [comment] 2018-09-25 19:29
Where do you have it set to "Summary Card with Large Image"? Is that in Global SEO, Content SEO, or in an SEO Settings field?

**Comment by robmcfadden** [comment] 2018-10-02 17:33
Sorry! Missed this. I have it set both in Global SEO and Content SEO for the channel in question. And the preview is showing the correct version of the summary card.

I have the Twitter Card Type hidden in the SEO field on that channel, but I just enabled that and saved an entry with the "Summary Card with Large Image". It worked! So it seems to not be falling back to the Content or Global SEO value which is what I was expecting.

Hope that helps and thanks for your help.

**Comment by khalwat** [comment] 2018-10-15 18:59
Thanks @robmcfadden -- I am working on diagnosing what is going on here.

**Comment by jonlongnecker** [comment] 2018-10-23 19:58
I've noticed this, too. The large card option is cropping really strangely.
<img width="325" alt="screenshot 2018-10-23 13 57 10" src="https://user-images.githubusercontent.com/2390/47387085-961d2e00-d6cb-11e8-8f39-03e07f81383d.png">

The FB and Twitter images should be really close, but the Twitter version does look like it's being cropped from a square or something.

**Comment by khalwat** [comment] 2018-10-23 20:38
This is useful information @jonlongnecker thanks, I'm on it!

**Comment by proposifymax** [comment] 2018-10-29 13:52
I'm experiencing the same issue.

Twitter recommends an aspect ratio of 2:1 not 1:1 for [this card type](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html).

It also seems to ignore the settings for `Transform SEO Image` and `SEO Image Transform Mode` in the global, content, and entry-level settings. The site source for the `twitter:image` meta tag includes the autocrop `_800x800_crop_center-center_82_none` in the path structure.

**Comment by khalwat** [comment] 2018-11-02 14:54
Okay, so here's what is happening. If you set everything up, and you save your Twitter settings, the transform will be correct:

`{seomatic.helper.socialTransform(72, "twitter-large", 1, "crop")}
`

But then if you go back and re-save your General settings, it appears to revert:

`{seomatic.helper.socialTransform(72, "twitter-summary", 1, "crop")}
`

Investigating what could be causing this...

**Comment by khalwat** [comment] 2018-11-02 15:09
Fixed in https://github.com/nystudio107/craft-seomatic/commit/b56ffbc0c9b96ffdc75324eb30b5a55af4f0deca

**Comment by khalwat** [comment] 2018-11-16 21:37
So a variant of this issue _still exists_, which is that if you have and SEO Settings field:

* With only the SEO Image from the General tab available
* With the Twitter tab available, but no Twitter Card Type

What happens is it goes to build the preset pull fields Twig code, but since there's no setting for the Twitter Card Type available in its context, it defaults to the Summary Card, and generates a transform based on that.

The issue is that in the context of editing the field, it doesn't know anything about the Content SEO settings for the section, or the Global SEO settings, so it isn't properly falling back on said data when that context isn't available in the SEO Settings field itself.

**Comment by khalwat** [comment] 2018-11-17 22:57
Once again, with vigor... addressed in https://github.com/nystudio107/craft-seomatic/commit/af1f4562f3e17acfedc5aa5d7eb177fb39ec31d0

**Closed as completed by khalwat** 2018-11-17 22:57 UTC
Labels: bug, need info
