### ISSUE TITLE
Doesn't seem possible to conditionally load gtag

### ISSUE THREAD

**Issue by wuhhh** [nystudio107/craft-seomatic#1334] opened 2023-06-15 11:21 UTC
### Describe the bug
Following advice given on other issues here, I have the following in my default layout:

```
{% if craft.cookies.get('allowCookies') != 'true' %}
  {% do seomatic.script.get('gtag').include(false) %}
  {% do seomatic.script.get('googleTagManager').include(false) %}
  {% do seomatic.script.container().include(false) %}
  {% do seomatic.script.container().clearCache(true) %}
{% endif %}
```

FB Pixel, hubspot etc correctly disappear, however there is still a call made to `https://www.googletagmanager.com/gtag/js?id=xxx`

![Screenshot 2023-06-15 at 12 20 06](https://github.com/nystudio107/craft-seomatic/assets/23365549/0abaa7b4-21f0-4de1-8769-dac9cb9ab8c5)

### Versions
- Plugin version: 4.0.28
- Craft version: 4.4.9 Solo

**Comment by khalwat** [comment] 2023-06-16 22:49
Doing this: 

```twig
  {% do seomatic.script.container().include(false) %}
```

will ensure that _no_ scripts from SEOmatic are rendered. Are you sure this gtag script is actually coming from SEOmatic?

**Comment by wuhhh** [comment] 2023-06-20 08:37
Yes, if I turn it off explicitly in the SEOMatic settings, it disappears. I know `seomatic.script.container().include(false)` is not supposed to render any scripts but it didn't work, so I added the gtag specific exclusion as well which also didn't work.

**Comment by khalwat** [comment] 2023-06-20 15:13
Addressed in: https://github.com/nystudio107/craft-seomatic/commit/eae2cc4e6c0b54c7f4555d049d51ca8d3bfbb0f6 & https://github.com/nystudio107/craft-seomatic/commit/60838de0c6cf663d989fcf8b6ae1e1930259d17b

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.58”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.29”,
```
Then do a `composer clear-cache && composer update`

**Comment by jamesmacwhite** [comment] 2023-07-19 14:32
FYI, I think this has caused a regression on noscript related areas for bodyJS see: #1346 since updating to 3.4.58

**Comment by khalwat** [comment] 2023-07-19 14:32
Yes, you're right. https://github.com/nystudio107/craft-seomatic/issues/1346

**Closed as completed** 2023-07-19 14:33 UTC
Labels: bug

**Comment by khalwat** [comment] 2023-07-22 20:55
So I looked into this further after having to roll back the previous fix that had regressions.

If you put this Twig into the root of the template (not in a `{% block %}` tag:

```
    {% do seomatic.script.container().include(false) %}
```

It will work for you. The issue is that the body script is rendered in a different manner than the rest of the tags, because it can include raw HTML, and due to Twig Processing Order:

https://nystudio107.com/blog/twig-processing-order-and-scope

...the tags are rendered _before_ your code that said not to include the tag is executed. Moving that code outside of the block will cause it to work as expected.

**Comment by khalwat** [comment] 2023-07-22 21:29
I wasn't content with that quirk, so fixed the issue properly.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.60”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.31”,
```
Then do a `composer clear-cache && composer update`
