### ISSUE TITLE
Copy Settings From not working as intended for Content SEO

### ISSUE THREAD

**Issue by nicolascnudde** [nystudio107/craft-seomatic#1368] opened 2023-10-23 12:39 UTC
### Describe the bug
When having multiple sites, the _Copy Settings From_ feature isn't working properly in some cases. We tried doing this in a **section with 5 entry types**.

Adding the correct values works fine on the original site, but when trying to copy settings from the original site onto the new site (eg. English UK → English US), it automatically jumps back to the first entry type in the dropdown list and only the first entry type gets updated.

### To reproduce
Steps to reproduce the behaviour:
1. In Craft CMS, create another site to have a total of at least 2 sites (eg. English UK and English US)
2. Create a section (eg. knowledgeHub) with 5 entry types (eg. webinar, upcomingWebinar, ebook, caseStudy, article).
3. In the **Content SEO** settings, put in different values for each entry type from that section in the original site.
4. In the site dropdown list, click on a site other than the original one. 
5. Choose any entry type other than the first option, and copy the site settings from the original site.
6. Check if the values successfully get copied from the original site and/or if the list of entry types has reverted to the first option.

### Expected behaviour
All the values from the original site should successfully get copied to all the entry types values in the other site(s).

### Screenshots
1~5: original site (en-UK), the different entry types. Tested with the SEO title source value.

![seomatic_issue_1](https://github.com/nystudio107/craft-seomatic/assets/72446674/94333d22-6f71-4941-9e73-d05580222886)

![seomatic_issue_2](https://github.com/nystudio107/craft-seomatic/assets/72446674/de65f6a1-6df8-471f-a07e-aa985f18d85c)

![seomatic_issue_3](https://github.com/nystudio107/craft-seomatic/assets/72446674/7197c2ff-9d4f-4fec-9757-3449ddab9b6d)

![seomatic_issue_4](https://github.com/nystudio107/craft-seomatic/assets/72446674/7a1fcee0-1a17-4574-9487-ac7b3ab6a8f1)

![seomatic_issue_5](https://github.com/nystudio107/craft-seomatic/assets/72446674/d683884c-dc36-4cd4-9d2f-3d3e4f7e9302)

Video: second site (en-US). Process of trying to copy entry types from the original site onto this site.

https://github.com/nystudio107/craft-seomatic/assets/72446674/a753daec-517f-4d92-9c26-a40c15b672f5

### Versions
- Plugin version: 4.0.32
- Craft version: 4.5.6.1

**Comment by khalwat** [comment] 2023-11-02 23:22
Ah I see. I think the issue is that it's not taking the entry type into account.

**Comment by nicolascnudde** [comment] 2023-11-21 09:29
@khalwat is there a way to take it into account, or a workaround? All of our other sections have no issues, only this one for some reason.

We already have a lot of entries for each of these entry types (webinars, e-book, etc.)

**Comment by khalwat** [comment] 2023-11-23 16:43
It's on my list to have a look at -- I just first need to get a setup where I can duplicate the problem, then I can figure out what is wrong and fix it.

You say it only fails to work properly on one particular section? For other sections where it does work, do you have a similar setup of multiple sites with multiple entry types?

**Comment by nicolascnudde** [comment] 2023-12-06 09:54
Sorry for the late reply @khalwat. Yes, that is correct. These are all of the sections that are being used throughout the site:

![Screenshot 2023-12-06 at 10 48 31](https://github.com/nystudio107/craft-seomatic/assets/72446674/1e0ad812-eaa4-4fb1-a8bf-31234ced0363)

The problem is located with the different entry types within the Knowledge hub (channel) section. The Jobs (channel) section only has one (default) entry type so no issues there. And the sections that have the structure type and multiple entry types are working fine.

So perhaps the channel type is causing the issue?

**Comment by nicolascnudde** [comment] 2024-01-16 09:21
Hi. Any update on this yet?

**Comment by khalwat** [comment] 2024-01-24 16:34
Have not forgotten about this, it's on the list for the next update to SEOmatic.

I've been working on porting SEOmatic to Craft 5, which is now done. Thanks for your patience. https://github.com/nystudio107/craft-seomatic/releases/tag/5.0.0-beta.2

**Comment by yannkost** [comment] 2024-03-20 08:53
Can I ask if there is a version for Craft 4 where this bug is fixed? We stumbled upon the same problem.

**Comment by khalwat** [comment] 2024-03-20 17:18
No update yet.

**Comment by khalwat** [comment] 2024-04-03 20:44
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.75”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.46”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.9”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2024-04-03 20:44 UTC
Labels: bug

**Comment by khalwat** [comment] 2024-04-03 21:02
Addressed in the above commits.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop as 3.4.75”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v4 as 4.0.46”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-seomatic": "dev-develop-v5 as 5.0.0-beta.9”,
```
Then do a `composer clear-cache && composer update`
